<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracepb.proto

namespace CrazyGoat\Proto\Tracepb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Report the spans collected when handling a request on a service.
 *
 * Generated from protobuf message <code>tracepb.Report</code>
 */
class Report extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .tracepb.RemoteParentSpan remote_parent_spans = 1;</code>
     */
    private $remote_parent_spans;
    /**
     * Generated from protobuf field <code>repeated .tracepb.Span spans = 2;</code>
     */
    private $spans;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Tracepb\RemoteParentSpan[] $remote_parent_spans
     *     @type \CrazyGoat\Proto\Tracepb\Span[] $spans
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Tracepb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .tracepb.RemoteParentSpan remote_parent_spans = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Tracepb\RemoteParentSpan>
     */
    public function getRemoteParentSpans()
    {
        return $this->remote_parent_spans;
    }

    /**
     * Generated from protobuf field <code>repeated .tracepb.RemoteParentSpan remote_parent_spans = 1;</code>
     * @param \CrazyGoat\Proto\Tracepb\RemoteParentSpan[] $var
     * @return $this
     */
    public function setRemoteParentSpans($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Tracepb\RemoteParentSpan::class);
        $this->remote_parent_spans = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .tracepb.Span spans = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Tracepb\Span>
     */
    public function getSpans()
    {
        return $this->spans;
    }

    /**
     * Generated from protobuf field <code>repeated .tracepb.Span spans = 2;</code>
     * @param \CrazyGoat\Proto\Tracepb\Span[] $var
     * @return $this
     */
    public function setSpans($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Tracepb\Span::class);
        $this->spans = $arr;

        return $this;
    }

}

