<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracepb.proto

namespace CrazyGoat\Proto\Tracepb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The context of the request to be traced.
 *
 * Generated from protobuf message <code>tracepb.TraceContext</code>
 */
class TraceContext extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .tracepb.RemoteParentSpan remote_parent_spans = 1;</code>
     */
    private $remote_parent_spans;
    /**
     * Report the trace records only if the duration of handling the request exceeds the threshold.
     *
     * Generated from protobuf field <code>uint32 duration_threshold_ms = 2;</code>
     */
    protected $duration_threshold_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Tracepb\RemoteParentSpan[] $remote_parent_spans
     *     @type int $duration_threshold_ms
     *           Report the trace records only if the duration of handling the request exceeds the threshold.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Tracepb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .tracepb.RemoteParentSpan remote_parent_spans = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Tracepb\RemoteParentSpan>
     */
    public function getRemoteParentSpans()
    {
        return $this->remote_parent_spans;
    }

    /**
     * Generated from protobuf field <code>repeated .tracepb.RemoteParentSpan remote_parent_spans = 1;</code>
     * @param \CrazyGoat\Proto\Tracepb\RemoteParentSpan[] $var
     * @return $this
     */
    public function setRemoteParentSpans($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Tracepb\RemoteParentSpan::class);
        $this->remote_parent_spans = $arr;

        return $this;
    }

    /**
     * Report the trace records only if the duration of handling the request exceeds the threshold.
     *
     * Generated from protobuf field <code>uint32 duration_threshold_ms = 2;</code>
     * @return int
     */
    public function getDurationThresholdMs()
    {
        return $this->duration_threshold_ms;
    }

    /**
     * Report the trace records only if the duration of handling the request exceeds the threshold.
     *
     * Generated from protobuf field <code>uint32 duration_threshold_ms = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDurationThresholdMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->duration_threshold_ms = $var;

        return $this;
    }

}

