<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb\WriteConflict;

use UnexpectedValueException;

/**
 * Protobuf type <code>kvrpcpb.WriteConflict.Reason</code>
 */
class Reason
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * in optimistic transactions.
     *
     * Generated from protobuf enum <code>Optimistic = 1;</code>
     */
    const Optimistic = 1;
    /**
     * a lock acquisition request waits for a lock and awakes, or meets a newer version of data, let TiDB retry.
     *
     * Generated from protobuf enum <code>PessimisticRetry = 2;</code>
     */
    const PessimisticRetry = 2;
    /**
     * the transaction itself has been rolled back when it tries to prewrite.
     *
     * Generated from protobuf enum <code>SelfRolledBack = 3;</code>
     */
    const SelfRolledBack = 3;
    /**
     * RcCheckTs failure by meeting a newer version, let TiDB retry.
     *
     * Generated from protobuf enum <code>RcCheckTs = 4;</code>
     */
    const RcCheckTs = 4;
    /**
     * write conflict found when deferring constraint checks in pessimistic transactions. Deprecated in next-gen (cloud-storage-engine).
     *
     * Generated from protobuf enum <code>LazyUniquenessCheck = 5;</code>
     */
    const LazyUniquenessCheck = 5;
    /**
     * write conflict found on keys that do not acquire pessimistic locks in pessimistic transactions.
     *
     * Generated from protobuf enum <code>NotLockedKeyConflict = 6;</code>
     */
    const NotLockedKeyConflict = 6;

    private static $valueToName = [
        self::Unknown => 'Unknown',
        self::Optimistic => 'Optimistic',
        self::PessimisticRetry => 'PessimisticRetry',
        self::SelfRolledBack => 'SelfRolledBack',
        self::RcCheckTs => 'RcCheckTs',
        self::LazyUniquenessCheck => 'LazyUniquenessCheck',
        self::NotLockedKeyConflict => 'NotLockedKeyConflict',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

