<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tikvpb.proto

namespace Tikvpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>tikvpb.BatchCommandsEmptyResponse</code>
 */
class BatchCommandsEmptyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the test request.
     *
     * Generated from protobuf field <code>uint64 test_id = 1;</code>
     */
    protected $test_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $test_id
     *           ID of the test request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tikvpb::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the test request.
     *
     * Generated from protobuf field <code>uint64 test_id = 1;</code>
     * @return int|string
     */
    public function getTestId()
    {
        return $this->test_id;
    }

    /**
     * ID of the test request.
     *
     * Generated from protobuf field <code>uint64 test_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTestId($var)
    {
        GPBUtil::checkUint64($var);
        $this->test_id = $var;

        return $this;
    }

}

