<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coprocessor.proto

namespace Coprocessor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * KeyRange with an attached read_ts (version).
 * It is used by TiCI versioned lookup. Callers must ensure `range` is a point range.
 *
 * Generated from protobuf message <code>coprocessor.VersionedKeyRange</code>
 */
class VersionedKeyRange extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.coprocessor.KeyRange range = 1;</code>
     */
    protected $range = null;
    /**
     * Generated from protobuf field <code>uint64 read_ts = 2;</code>
     */
    protected $read_ts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Coprocessor\KeyRange $range
     *     @type int|string $read_ts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Coprocessor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.coprocessor.KeyRange range = 1;</code>
     * @return \Coprocessor\KeyRange|null
     */
    public function getRange()
    {
        return $this->range;
    }

    public function hasRange()
    {
        return isset($this->range);
    }

    public function clearRange()
    {
        unset($this->range);
    }

    /**
     * Generated from protobuf field <code>.coprocessor.KeyRange range = 1;</code>
     * @param \Coprocessor\KeyRange $var
     * @return $this
     */
    public function setRange($var)
    {
        GPBUtil::checkMessage($var, \Coprocessor\KeyRange::class);
        $this->range = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 read_ts = 2;</code>
     * @return int|string
     */
    public function getReadTs()
    {
        return $this->read_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 read_ts = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReadTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->read_ts = $var;

        return $this;
    }

}

