<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metapb.proto

namespace CrazyGoat\Proto\Metapb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>metapb.Buckets</code>
 */
class Buckets extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 region_id = 1;</code>
     */
    protected $region_id = 0;
    /**
     * A hint indicate if keys have changed.
     *
     * Generated from protobuf field <code>uint64 version = 2;</code>
     */
    protected $version = 0;
    /**
     * keys of buckets, include start/end key of region
     *
     * Generated from protobuf field <code>repeated bytes keys = 3;</code>
     */
    private $keys;
    /**
     * bucket stats
     *
     * Generated from protobuf field <code>.metapb.BucketStats stats = 4;</code>
     */
    protected $stats = null;
    /**
     * The period in milliseconds that stats are collected with in
     *
     * Generated from protobuf field <code>uint64 period_in_ms = 5;</code>
     */
    protected $period_in_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $region_id
     *     @type int|string $version
     *           A hint indicate if keys have changed.
     *     @type string[] $keys
     *           keys of buckets, include start/end key of region
     *     @type \CrazyGoat\Proto\Metapb\BucketStats $stats
     *           bucket stats
     *     @type int|string $period_in_ms
     *           The period in milliseconds that stats are collected with in
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Metapb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 region_id = 1;</code>
     * @return int|string
     */
    public function getRegionId()
    {
        return $this->region_id;
    }

    /**
     * Generated from protobuf field <code>uint64 region_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->region_id = $var;

        return $this;
    }

    /**
     * A hint indicate if keys have changed.
     *
     * Generated from protobuf field <code>uint64 version = 2;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * A hint indicate if keys have changed.
     *
     * Generated from protobuf field <code>uint64 version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * keys of buckets, include start/end key of region
     *
     * Generated from protobuf field <code>repeated bytes keys = 3;</code>
     * @return RepeatedField<string>
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * keys of buckets, include start/end key of region
     *
     * Generated from protobuf field <code>repeated bytes keys = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->keys = $arr;

        return $this;
    }

    /**
     * bucket stats
     *
     * Generated from protobuf field <code>.metapb.BucketStats stats = 4;</code>
     * @return \CrazyGoat\Proto\Metapb\BucketStats|null
     */
    public function getStats()
    {
        return $this->stats;
    }

    public function hasStats()
    {
        return isset($this->stats);
    }

    public function clearStats()
    {
        unset($this->stats);
    }

    /**
     * bucket stats
     *
     * Generated from protobuf field <code>.metapb.BucketStats stats = 4;</code>
     * @param \CrazyGoat\Proto\Metapb\BucketStats $var
     * @return $this
     */
    public function setStats($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\BucketStats::class);
        $this->stats = $var;

        return $this;
    }

    /**
     * The period in milliseconds that stats are collected with in
     *
     * Generated from protobuf field <code>uint64 period_in_ms = 5;</code>
     * @return int|string
     */
    public function getPeriodInMs()
    {
        return $this->period_in_ms;
    }

    /**
     * The period in milliseconds that stats are collected with in
     *
     * Generated from protobuf field <code>uint64 period_in_ms = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPeriodInMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->period_in_ms = $var;

        return $this;
    }

}

