<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metapb.proto

namespace CrazyGoat\Proto\Metapb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>metapb.Cluster</code>
 */
class Cluster extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * max peer count for a region.
     * pd will do the auto-balance if region peer count mismatches.
     *
     * Generated from protobuf field <code>uint32 max_peer_count = 2;</code>
     */
    protected $max_peer_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int $max_peer_count
     *           max peer count for a region.
     *           pd will do the auto-balance if region peer count mismatches.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Metapb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * max peer count for a region.
     * pd will do the auto-balance if region peer count mismatches.
     *
     * Generated from protobuf field <code>uint32 max_peer_count = 2;</code>
     * @return int
     */
    public function getMaxPeerCount()
    {
        return $this->max_peer_count;
    }

    /**
     * max peer count for a region.
     * pd will do the auto-balance if region peer count mismatches.
     *
     * Generated from protobuf field <code>uint32 max_peer_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxPeerCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_peer_count = $var;

        return $this;
    }

}

