<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metapb.proto

namespace Metapb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>metapb.Region</code>
 */
class Region extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Region key range [start_key, end_key).
     *
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     */
    protected $start_key = '';
    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     */
    protected $end_key = '';
    /**
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 4;</code>
     */
    protected $region_epoch = null;
    /**
     * Generated from protobuf field <code>repeated .metapb.Peer peers = 5;</code>
     */
    private $peers;
    /**
     * Encryption metadata for start_key and end_key. encryption_meta.iv is IV for start_key.
     * IV for end_key is calculated from (encryption_meta.iv + len(start_key)).
     * The field is only used by PD and should be ignored otherwise.
     * If encryption_meta is empty (i.e. nil), it means start_key and end_key are unencrypted.
     *
     * Generated from protobuf field <code>.encryptionpb.EncryptionMeta encryption_meta = 6;</code>
     */
    protected $encryption_meta = null;
    /**
     * The flashback state indicates whether this region is in the flashback state.
     * TODO: only check by `flashback_start_ts` in the future. Keep for compatibility now.
     *
     * Generated from protobuf field <code>bool is_in_flashback = 7;</code>
     */
    protected $is_in_flashback = false;
    /**
     * The start_ts that the current flashback progress is using.
     *
     * Generated from protobuf field <code>uint64 flashback_start_ts = 8;</code>
     */
    protected $flashback_start_ts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $start_key
     *           Region key range [start_key, end_key).
     *     @type string $end_key
     *     @type \Metapb\RegionEpoch $region_epoch
     *     @type \Metapb\Peer[] $peers
     *     @type \Encryptionpb\EncryptionMeta $encryption_meta
     *           Encryption metadata for start_key and end_key. encryption_meta.iv is IV for start_key.
     *           IV for end_key is calculated from (encryption_meta.iv + len(start_key)).
     *           The field is only used by PD and should be ignored otherwise.
     *           If encryption_meta is empty (i.e. nil), it means start_key and end_key are unencrypted.
     *     @type bool $is_in_flashback
     *           The flashback state indicates whether this region is in the flashback state.
     *           TODO: only check by `flashback_start_ts` in the future. Keep for compatibility now.
     *     @type int|string $flashback_start_ts
     *           The start_ts that the current flashback progress is using.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Metapb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Region key range [start_key, end_key).
     *
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Region key range [start_key, end_key).
     *
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * Generated from protobuf field <code>bytes end_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->end_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 4;</code>
     * @return \Metapb\RegionEpoch|null
     */
    public function getRegionEpoch()
    {
        return $this->region_epoch;
    }

    public function hasRegionEpoch()
    {
        return isset($this->region_epoch);
    }

    public function clearRegionEpoch()
    {
        unset($this->region_epoch);
    }

    /**
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 4;</code>
     * @param \Metapb\RegionEpoch $var
     * @return $this
     */
    public function setRegionEpoch($var)
    {
        GPBUtil::checkMessage($var, \Metapb\RegionEpoch::class);
        $this->region_epoch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .metapb.Peer peers = 5;</code>
     * @return RepeatedField<\Metapb\Peer>
     */
    public function getPeers()
    {
        return $this->peers;
    }

    /**
     * Generated from protobuf field <code>repeated .metapb.Peer peers = 5;</code>
     * @param \Metapb\Peer[] $var
     * @return $this
     */
    public function setPeers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Metapb\Peer::class);
        $this->peers = $arr;

        return $this;
    }

    /**
     * Encryption metadata for start_key and end_key. encryption_meta.iv is IV for start_key.
     * IV for end_key is calculated from (encryption_meta.iv + len(start_key)).
     * The field is only used by PD and should be ignored otherwise.
     * If encryption_meta is empty (i.e. nil), it means start_key and end_key are unencrypted.
     *
     * Generated from protobuf field <code>.encryptionpb.EncryptionMeta encryption_meta = 6;</code>
     * @return \Encryptionpb\EncryptionMeta|null
     */
    public function getEncryptionMeta()
    {
        return $this->encryption_meta;
    }

    public function hasEncryptionMeta()
    {
        return isset($this->encryption_meta);
    }

    public function clearEncryptionMeta()
    {
        unset($this->encryption_meta);
    }

    /**
     * Encryption metadata for start_key and end_key. encryption_meta.iv is IV for start_key.
     * IV for end_key is calculated from (encryption_meta.iv + len(start_key)).
     * The field is only used by PD and should be ignored otherwise.
     * If encryption_meta is empty (i.e. nil), it means start_key and end_key are unencrypted.
     *
     * Generated from protobuf field <code>.encryptionpb.EncryptionMeta encryption_meta = 6;</code>
     * @param \Encryptionpb\EncryptionMeta $var
     * @return $this
     */
    public function setEncryptionMeta($var)
    {
        GPBUtil::checkMessage($var, \Encryptionpb\EncryptionMeta::class);
        $this->encryption_meta = $var;

        return $this;
    }

    /**
     * The flashback state indicates whether this region is in the flashback state.
     * TODO: only check by `flashback_start_ts` in the future. Keep for compatibility now.
     *
     * Generated from protobuf field <code>bool is_in_flashback = 7;</code>
     * @return bool
     */
    public function getIsInFlashback()
    {
        return $this->is_in_flashback;
    }

    /**
     * The flashback state indicates whether this region is in the flashback state.
     * TODO: only check by `flashback_start_ts` in the future. Keep for compatibility now.
     *
     * Generated from protobuf field <code>bool is_in_flashback = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsInFlashback($var)
    {
        GPBUtil::checkBool($var);
        $this->is_in_flashback = $var;

        return $this;
    }

    /**
     * The start_ts that the current flashback progress is using.
     *
     * Generated from protobuf field <code>uint64 flashback_start_ts = 8;</code>
     * @return int|string
     */
    public function getFlashbackStartTs()
    {
        return $this->flashback_start_ts;
    }

    /**
     * The start_ts that the current flashback progress is using.
     *
     * Generated from protobuf field <code>uint64 flashback_start_ts = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFlashbackStartTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->flashback_start_ts = $var;

        return $this;
    }

}

