<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metapb.proto

namespace CrazyGoat\Proto\Metapb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>metapb.RegionEpoch</code>
 */
class RegionEpoch extends \Google\Protobuf\Internal\Message
{
    /**
     * Conf change version, auto increment when add or remove peer
     *
     * Generated from protobuf field <code>uint64 conf_ver = 1;</code>
     */
    protected $conf_ver = 0;
    /**
     * Region version, auto increment when split or merge
     *
     * Generated from protobuf field <code>uint64 version = 2;</code>
     */
    protected $version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $conf_ver
     *           Conf change version, auto increment when add or remove peer
     *     @type int|string $version
     *           Region version, auto increment when split or merge
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Metapb::initOnce();
        parent::__construct($data);
    }

    /**
     * Conf change version, auto increment when add or remove peer
     *
     * Generated from protobuf field <code>uint64 conf_ver = 1;</code>
     * @return int|string
     */
    public function getConfVer()
    {
        return $this->conf_ver;
    }

    /**
     * Conf change version, auto increment when add or remove peer
     *
     * Generated from protobuf field <code>uint64 conf_ver = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConfVer($var)
    {
        GPBUtil::checkUint64($var);
        $this->conf_ver = $var;

        return $this;
    }

    /**
     * Region version, auto increment when split or merge
     *
     * Generated from protobuf field <code>uint64 version = 2;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Region version, auto increment when split or merge
     *
     * Generated from protobuf field <code>uint64 version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

}

