<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metapb.proto

namespace CrazyGoat\Proto\Metapb;

use UnexpectedValueException;

/**
 * Protobuf type <code>metapb.StoreState</code>
 */
class StoreState
{
    /**
     * Generated from protobuf enum <code>Up = 0;</code>
     */
    const Up = 0;
    /**
     * Generated from protobuf enum <code>Offline = 1;</code>
     */
    const Offline = 1;
    /**
     * Generated from protobuf enum <code>Tombstone = 2;</code>
     */
    const Tombstone = 2;

    private static $valueToName = [
        self::Up => 'Up',
        self::Offline => 'Offline',
        self::Tombstone => 'Tombstone',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

