<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_serverpb.proto

namespace CrazyGoat\Proto\RaftServerpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>raft_serverpb.RaftSnapshotData</code>
 */
class RaftSnapshotData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.metapb.Region region = 1;</code>
     */
    protected $region = null;
    /**
     * Generated from protobuf field <code>uint64 file_size = 2;</code>
     */
    protected $file_size = 0;
    /**
     * Generated from protobuf field <code>repeated .raft_serverpb.KeyValue data = 3;</code>
     */
    private $data;
    /**
     * Generated from protobuf field <code>uint64 version = 4;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>.raft_serverpb.SnapshotMeta meta = 5;</code>
     */
    protected $meta = null;
    /**
     * Generated from protobuf field <code>repeated .metapb.Peer removed_records = 6;</code>
     */
    private $removed_records;
    /**
     * Generated from protobuf field <code>repeated .raft_serverpb.MergedRecord merged_records = 7;</code>
     */
    private $merged_records;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Metapb\Region $region
     *     @type int|string $file_size
     *     @type \CrazyGoat\Proto\RaftServerpb\KeyValue[] $data
     *     @type int|string $version
     *     @type \CrazyGoat\Proto\RaftServerpb\SnapshotMeta $meta
     *     @type \CrazyGoat\Proto\Metapb\Peer[] $removed_records
     *     @type \CrazyGoat\Proto\RaftServerpb\MergedRecord[] $merged_records
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\RaftServerpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 1;</code>
     * @return \CrazyGoat\Proto\Metapb\Region|null
     */
    public function getRegion()
    {
        return $this->region;
    }

    public function hasRegion()
    {
        return isset($this->region);
    }

    public function clearRegion()
    {
        unset($this->region);
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 1;</code>
     * @param \CrazyGoat\Proto\Metapb\Region $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\Region::class);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 file_size = 2;</code>
     * @return int|string
     */
    public function getFileSize()
    {
        return $this->file_size;
    }

    /**
     * Generated from protobuf field <code>uint64 file_size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFileSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->file_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .raft_serverpb.KeyValue data = 3;</code>
     * @return RepeatedField<\CrazyGoat\Proto\RaftServerpb\KeyValue>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .raft_serverpb.KeyValue data = 3;</code>
     * @param \CrazyGoat\Proto\RaftServerpb\KeyValue[] $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\RaftServerpb\KeyValue::class);
        $this->data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 version = 4;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint64 version = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.SnapshotMeta meta = 5;</code>
     * @return \CrazyGoat\Proto\RaftServerpb\SnapshotMeta|null
     */
    public function getMeta()
    {
        return $this->meta;
    }

    public function hasMeta()
    {
        return isset($this->meta);
    }

    public function clearMeta()
    {
        unset($this->meta);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.SnapshotMeta meta = 5;</code>
     * @param \CrazyGoat\Proto\RaftServerpb\SnapshotMeta $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\RaftServerpb\SnapshotMeta::class);
        $this->meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .metapb.Peer removed_records = 6;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Metapb\Peer>
     */
    public function getRemovedRecords()
    {
        return $this->removed_records;
    }

    /**
     * Generated from protobuf field <code>repeated .metapb.Peer removed_records = 6;</code>
     * @param \CrazyGoat\Proto\Metapb\Peer[] $var
     * @return $this
     */
    public function setRemovedRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Metapb\Peer::class);
        $this->removed_records = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .raft_serverpb.MergedRecord merged_records = 7;</code>
     * @return RepeatedField<\CrazyGoat\Proto\RaftServerpb\MergedRecord>
     */
    public function getMergedRecords()
    {
        return $this->merged_records;
    }

    /**
     * Generated from protobuf field <code>repeated .raft_serverpb.MergedRecord merged_records = 7;</code>
     * @param \CrazyGoat\Proto\RaftServerpb\MergedRecord[] $var
     * @return $this
     */
    public function setMergedRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\RaftServerpb\MergedRecord::class);
        $this->merged_records = $arr;

        return $this;
    }

}

