<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_serverpb.proto

namespace CrazyGoat\Proto\RaftServerpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>raft_serverpb.SnapshotCFFile</code>
 */
class SnapshotCFFile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cf = 1;</code>
     */
    protected $cf = '';
    /**
     * Generated from protobuf field <code>uint64 size = 2;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>uint32 checksum = 3;</code>
     */
    protected $checksum = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cf
     *     @type int|string $size
     *     @type int $checksum
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\RaftServerpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cf = 1;</code>
     * @return string
     */
    public function getCf()
    {
        return $this->cf;
    }

    /**
     * Generated from protobuf field <code>string cf = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCf($var)
    {
        GPBUtil::checkString($var, True);
        $this->cf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 2;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>uint64 size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 checksum = 3;</code>
     * @return int
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * Generated from protobuf field <code>uint32 checksum = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setChecksum($var)
    {
        GPBUtil::checkUint32($var);
        $this->checksum = $var;

        return $this;
    }

}

