<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_serverpb.proto

namespace CrazyGoat\Proto\RaftServerpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>raft_serverpb.TabletSnapshotFileMeta</code>
 */
class TabletSnapshotFileMeta extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 file_size = 1;</code>
     */
    protected $file_size = 0;
    /**
     * Generated from protobuf field <code>string file_name = 2;</code>
     */
    protected $file_name = '';
    /**
     * Some block data. Unencrypted.
     *
     * Generated from protobuf field <code>bytes head_chunk = 3;</code>
     */
    protected $head_chunk = '';
    /**
     * trailing data including checksum. Unencrypted.
     *
     * Generated from protobuf field <code>bytes trailing_chunk = 4;</code>
     */
    protected $trailing_chunk = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $file_size
     *     @type string $file_name
     *     @type string $head_chunk
     *           Some block data. Unencrypted.
     *     @type string $trailing_chunk
     *           trailing data including checksum. Unencrypted.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\RaftServerpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 file_size = 1;</code>
     * @return int|string
     */
    public function getFileSize()
    {
        return $this->file_size;
    }

    /**
     * Generated from protobuf field <code>uint64 file_size = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFileSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->file_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string file_name = 2;</code>
     * @return string
     */
    public function getFileName()
    {
        return $this->file_name;
    }

    /**
     * Generated from protobuf field <code>string file_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_name = $var;

        return $this;
    }

    /**
     * Some block data. Unencrypted.
     *
     * Generated from protobuf field <code>bytes head_chunk = 3;</code>
     * @return string
     */
    public function getHeadChunk()
    {
        return $this->head_chunk;
    }

    /**
     * Some block data. Unencrypted.
     *
     * Generated from protobuf field <code>bytes head_chunk = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHeadChunk($var)
    {
        GPBUtil::checkString($var, False);
        $this->head_chunk = $var;

        return $this;
    }

    /**
     * trailing data including checksum. Unencrypted.
     *
     * Generated from protobuf field <code>bytes trailing_chunk = 4;</code>
     * @return string
     */
    public function getTrailingChunk()
    {
        return $this->trailing_chunk;
    }

    /**
     * trailing data including checksum. Unencrypted.
     *
     * Generated from protobuf field <code>bytes trailing_chunk = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTrailingChunk($var)
    {
        GPBUtil::checkString($var, False);
        $this->trailing_chunk = $var;

        return $this;
    }

}

