<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.BootstrapRequest</code>
 */
class BootstrapRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.metapb.Store store = 2;</code>
     */
    protected $store = null;
    /**
     * Generated from protobuf field <code>.metapb.Region region = 3;</code>
     */
    protected $region = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\RequestHeader $header
     *     @type \CrazyGoat\Proto\Metapb\Store $store
     *     @type \CrazyGoat\Proto\Metapb\Region $region
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\RequestHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.Store store = 2;</code>
     * @return \CrazyGoat\Proto\Metapb\Store|null
     */
    public function getStore()
    {
        return $this->store;
    }

    public function hasStore()
    {
        return isset($this->store);
    }

    public function clearStore()
    {
        unset($this->store);
    }

    /**
     * Generated from protobuf field <code>.metapb.Store store = 2;</code>
     * @param \CrazyGoat\Proto\Metapb\Store $var
     * @return $this
     */
    public function setStore($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\Store::class);
        $this->store = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 3;</code>
     * @return \CrazyGoat\Proto\Metapb\Region|null
     */
    public function getRegion()
    {
        return $this->region;
    }

    public function hasRegion()
    {
        return isset($this->region);
    }

    public function clearRegion()
    {
        unset($this->region);
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 3;</code>
     * @param \CrazyGoat\Proto\Metapb\Region $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\Region::class);
        $this->region = $var;

        return $this;
    }

}

