<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.DeleteGCBarrierRequest</code>
 */
class DeleteGCBarrierRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.pdpb.KeyspaceScope keyspace_scope = 2;</code>
     */
    protected $keyspace_scope = null;
    /**
     * Generated from protobuf field <code>string barrier_id = 3;</code>
     */
    protected $barrier_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\RequestHeader $header
     *     @type \CrazyGoat\Proto\Pdpb\KeyspaceScope $keyspace_scope
     *     @type string $barrier_id
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\RequestHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pdpb.KeyspaceScope keyspace_scope = 2;</code>
     * @return \CrazyGoat\Proto\Pdpb\KeyspaceScope|null
     */
    public function getKeyspaceScope()
    {
        return $this->keyspace_scope;
    }

    public function hasKeyspaceScope()
    {
        return isset($this->keyspace_scope);
    }

    public function clearKeyspaceScope()
    {
        unset($this->keyspace_scope);
    }

    /**
     * Generated from protobuf field <code>.pdpb.KeyspaceScope keyspace_scope = 2;</code>
     * @param \CrazyGoat\Proto\Pdpb\KeyspaceScope $var
     * @return $this
     */
    public function setKeyspaceScope($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\KeyspaceScope::class);
        $this->keyspace_scope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string barrier_id = 3;</code>
     * @return string
     */
    public function getBarrierId()
    {
        return $this->barrier_id;
    }

    /**
     * Generated from protobuf field <code>string barrier_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBarrierId($var)
    {
        GPBUtil::checkString($var, True);
        $this->barrier_id = $var;

        return $this;
    }

}

