<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.DfsStatScope</code>
 */
class DfsStatScope extends \Google\Protobuf\Internal\Message
{
    /**
     * When true, the statistic is not tied to any keyspace.
     *
     * Generated from protobuf field <code>bool is_global = 1;</code>
     */
    protected $is_global = false;
    /**
     * The keyspace of this statistic. Ignore when is_global is true.
     *
     * Generated from protobuf field <code>uint32 keyspace_id = 2;</code>
     */
    protected $keyspace_id = 0;
    /**
     * The component that provides the statistic.
     *
     * Generated from protobuf field <code>string component = 3;</code>
     */
    protected $component = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_global
     *           When true, the statistic is not tied to any keyspace.
     *     @type int $keyspace_id
     *           The keyspace of this statistic. Ignore when is_global is true.
     *     @type string $component
     *           The component that provides the statistic.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * When true, the statistic is not tied to any keyspace.
     *
     * Generated from protobuf field <code>bool is_global = 1;</code>
     * @return bool
     */
    public function getIsGlobal()
    {
        return $this->is_global;
    }

    /**
     * When true, the statistic is not tied to any keyspace.
     *
     * Generated from protobuf field <code>bool is_global = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsGlobal($var)
    {
        GPBUtil::checkBool($var);
        $this->is_global = $var;

        return $this;
    }

    /**
     * The keyspace of this statistic. Ignore when is_global is true.
     *
     * Generated from protobuf field <code>uint32 keyspace_id = 2;</code>
     * @return int
     */
    public function getKeyspaceId()
    {
        return $this->keyspace_id;
    }

    /**
     * The keyspace of this statistic. Ignore when is_global is true.
     *
     * Generated from protobuf field <code>uint32 keyspace_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKeyspaceId($var)
    {
        GPBUtil::checkUint32($var);
        $this->keyspace_id = $var;

        return $this;
    }

    /**
     * The component that provides the statistic.
     *
     * Generated from protobuf field <code>string component = 3;</code>
     * @return string
     */
    public function getComponent()
    {
        return $this->component;
    }

    /**
     * The component that provides the statistic.
     *
     * Generated from protobuf field <code>string component = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setComponent($var)
    {
        GPBUtil::checkString($var, True);
        $this->component = $var;

        return $this;
    }

}

