<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.GCState</code>
 */
class GCState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.KeyspaceScope keyspace_scope = 1;</code>
     */
    protected $keyspace_scope = null;
    /**
     * Generated from protobuf field <code>bool is_keyspace_level_gc = 2;</code>
     */
    protected $is_keyspace_level_gc = false;
    /**
     * Generated from protobuf field <code>uint64 txn_safe_point = 3;</code>
     */
    protected $txn_safe_point = 0;
    /**
     * Generated from protobuf field <code>uint64 gc_safe_point = 4;</code>
     */
    protected $gc_safe_point = 0;
    /**
     * Generated from protobuf field <code>repeated .pdpb.GCBarrierInfo gc_barriers = 5;</code>
     */
    private $gc_barriers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\KeyspaceScope $keyspace_scope
     *     @type bool $is_keyspace_level_gc
     *     @type int|string $txn_safe_point
     *     @type int|string $gc_safe_point
     *     @type \CrazyGoat\Proto\Pdpb\GCBarrierInfo[] $gc_barriers
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.KeyspaceScope keyspace_scope = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\KeyspaceScope|null
     */
    public function getKeyspaceScope()
    {
        return $this->keyspace_scope;
    }

    public function hasKeyspaceScope()
    {
        return isset($this->keyspace_scope);
    }

    public function clearKeyspaceScope()
    {
        unset($this->keyspace_scope);
    }

    /**
     * Generated from protobuf field <code>.pdpb.KeyspaceScope keyspace_scope = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\KeyspaceScope $var
     * @return $this
     */
    public function setKeyspaceScope($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\KeyspaceScope::class);
        $this->keyspace_scope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_keyspace_level_gc = 2;</code>
     * @return bool
     */
    public function getIsKeyspaceLevelGc()
    {
        return $this->is_keyspace_level_gc;
    }

    /**
     * Generated from protobuf field <code>bool is_keyspace_level_gc = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsKeyspaceLevelGc($var)
    {
        GPBUtil::checkBool($var);
        $this->is_keyspace_level_gc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 txn_safe_point = 3;</code>
     * @return int|string
     */
    public function getTxnSafePoint()
    {
        return $this->txn_safe_point;
    }

    /**
     * Generated from protobuf field <code>uint64 txn_safe_point = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxnSafePoint($var)
    {
        GPBUtil::checkUint64($var);
        $this->txn_safe_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 gc_safe_point = 4;</code>
     * @return int|string
     */
    public function getGcSafePoint()
    {
        return $this->gc_safe_point;
    }

    /**
     * Generated from protobuf field <code>uint64 gc_safe_point = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGcSafePoint($var)
    {
        GPBUtil::checkUint64($var);
        $this->gc_safe_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pdpb.GCBarrierInfo gc_barriers = 5;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Pdpb\GCBarrierInfo>
     */
    public function getGcBarriers()
    {
        return $this->gc_barriers;
    }

    /**
     * Generated from protobuf field <code>repeated .pdpb.GCBarrierInfo gc_barriers = 5;</code>
     * @param \CrazyGoat\Proto\Pdpb\GCBarrierInfo[] $var
     * @return $this
     */
    public function setGcBarriers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Pdpb\GCBarrierInfo::class);
        $this->gc_barriers = $arr;

        return $this;
    }

}

