<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.GetGCStateResponse</code>
 */
class GetGCStateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.pdpb.GCState gc_state = 2;</code>
     */
    protected $gc_state = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pdpb\ResponseHeader $header
     *     @type \Pdpb\GCState $gc_state
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pdpb.GCState gc_state = 2;</code>
     * @return \Pdpb\GCState|null
     */
    public function getGcState()
    {
        return $this->gc_state;
    }

    public function hasGcState()
    {
        return isset($this->gc_state);
    }

    public function clearGcState()
    {
        unset($this->gc_state);
    }

    /**
     * Generated from protobuf field <code>.pdpb.GCState gc_state = 2;</code>
     * @param \Pdpb\GCState $var
     * @return $this
     */
    public function setGcState($var)
    {
        GPBUtil::checkMessage($var, \Pdpb\GCState::class);
        $this->gc_state = $var;

        return $this;
    }

}

