<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.IsSnapshotRecoveringResponse</code>
 */
class IsSnapshotRecoveringResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>bool marked = 2;</code>
     */
    protected $marked = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\ResponseHeader $header
     *     @type bool $marked
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool marked = 2;</code>
     * @return bool
     */
    public function getMarked()
    {
        return $this->marked;
    }

    /**
     * Generated from protobuf field <code>bool marked = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setMarked($var)
    {
        GPBUtil::checkBool($var);
        $this->marked = $var;

        return $this;
    }

}

