<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A wrapper over keyspace_id.
 * When a field is not specified in proto3, its value will be regarded as 0; however, keyspace_id = 0 is regarded as a valid keyspace (which
 * is the "DEFAULT" keyspace). To distinguish unspecified keyspace (NullKeyspace, 0xffffffff) and the default keyspace in some APIs as well
 * as preventing potential misuse, we wrap the keyspace_id into a message type which is nullable.
 *
 * Generated from protobuf message <code>pdpb.KeyspaceScope</code>
 */
class KeyspaceScope extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 keyspace_id = 1;</code>
     */
    protected $keyspace_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $keyspace_id
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 keyspace_id = 1;</code>
     * @return int
     */
    public function getKeyspaceId()
    {
        return $this->keyspace_id;
    }

    /**
     * Generated from protobuf field <code>uint32 keyspace_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKeyspaceId($var)
    {
        GPBUtil::checkUint32($var);
        $this->keyspace_id = $var;

        return $this;
    }

}

