<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.LoadGlobalConfigRequest</code>
 */
class LoadGlobalConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string names = 1;</code>
     */
    private $names;
    /**
     * Generated from protobuf field <code>string config_path = 2;</code>
     */
    protected $config_path = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $names
     *     @type string $config_path
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string names = 1;</code>
     * @return RepeatedField<string>
     */
    public function getNames()
    {
        return $this->names;
    }

    /**
     * Generated from protobuf field <code>repeated string names = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string config_path = 2;</code>
     * @return string
     */
    public function getConfigPath()
    {
        return $this->config_path;
    }

    /**
     * Generated from protobuf field <code>string config_path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setConfigPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->config_path = $var;

        return $this;
    }

}

