<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.Member</code>
 */
class Member extends \Google\Protobuf\Internal\Message
{
    /**
     * name is the name of the PD member.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * member_id is the unique id of the PD member.
     *
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     */
    protected $member_id = 0;
    /**
     * Generated from protobuf field <code>repeated string peer_urls = 3;</code>
     */
    private $peer_urls;
    /**
     * Generated from protobuf field <code>repeated string client_urls = 4;</code>
     */
    private $client_urls;
    /**
     * Generated from protobuf field <code>int32 leader_priority = 5;</code>
     */
    protected $leader_priority = 0;
    /**
     * Generated from protobuf field <code>string deploy_path = 6;</code>
     */
    protected $deploy_path = '';
    /**
     * Generated from protobuf field <code>string binary_version = 7;</code>
     */
    protected $binary_version = '';
    /**
     * Generated from protobuf field <code>string git_hash = 8;</code>
     */
    protected $git_hash = '';
    /**
     * Generated from protobuf field <code>string dc_location = 9;</code>
     */
    protected $dc_location = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           name is the name of the PD member.
     *     @type int|string $member_id
     *           member_id is the unique id of the PD member.
     *     @type string[] $peer_urls
     *     @type string[] $client_urls
     *     @type int $leader_priority
     *     @type string $deploy_path
     *     @type string $binary_version
     *     @type string $git_hash
     *     @type string $dc_location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * name is the name of the PD member.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name is the name of the PD member.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * member_id is the unique id of the PD member.
     *
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     * @return int|string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     * member_id is the unique id of the PD member.
     *
     * Generated from protobuf field <code>uint64 member_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkUint64($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string peer_urls = 3;</code>
     * @return RepeatedField<string>
     */
    public function getPeerUrls()
    {
        return $this->peer_urls;
    }

    /**
     * Generated from protobuf field <code>repeated string peer_urls = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPeerUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->peer_urls = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string client_urls = 4;</code>
     * @return RepeatedField<string>
     */
    public function getClientUrls()
    {
        return $this->client_urls;
    }

    /**
     * Generated from protobuf field <code>repeated string client_urls = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setClientUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->client_urls = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 leader_priority = 5;</code>
     * @return int
     */
    public function getLeaderPriority()
    {
        return $this->leader_priority;
    }

    /**
     * Generated from protobuf field <code>int32 leader_priority = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLeaderPriority($var)
    {
        GPBUtil::checkInt32($var);
        $this->leader_priority = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deploy_path = 6;</code>
     * @return string
     */
    public function getDeployPath()
    {
        return $this->deploy_path;
    }

    /**
     * Generated from protobuf field <code>string deploy_path = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDeployPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->deploy_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string binary_version = 7;</code>
     * @return string
     */
    public function getBinaryVersion()
    {
        return $this->binary_version;
    }

    /**
     * Generated from protobuf field <code>string binary_version = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setBinaryVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->binary_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string git_hash = 8;</code>
     * @return string
     */
    public function getGitHash()
    {
        return $this->git_hash;
    }

    /**
     * Generated from protobuf field <code>string git_hash = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setGitHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->git_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dc_location = 9;</code>
     * @return string
     */
    public function getDcLocation()
    {
        return $this->dc_location;
    }

    /**
     * Generated from protobuf field <code>string dc_location = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDcLocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->dc_location = $var;

        return $this;
    }

}

