<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.QueryRegionRequest</code>
 */
class QueryRegionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Whether to include the buckets info within the response.
     *
     * Generated from protobuf field <code>bool need_buckets = 2;</code>
     */
    protected $need_buckets = false;
    /**
     * The region IDs to query.
     *
     * Generated from protobuf field <code>repeated uint64 ids = 3;</code>
     */
    private $ids;
    /**
     * The region keys to query.
     *
     * Generated from protobuf field <code>repeated bytes keys = 4;</code>
     */
    private $keys;
    /**
     * The previous region keys to query.
     *
     * Generated from protobuf field <code>repeated bytes prev_keys = 5;</code>
     */
    private $prev_keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pdpb\RequestHeader $header
     *     @type bool $need_buckets
     *           Whether to include the buckets info within the response.
     *     @type int[]|string[] $ids
     *           The region IDs to query.
     *     @type string[] $keys
     *           The region keys to query.
     *     @type string[] $prev_keys
     *           The previous region keys to query.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Pdpb\RequestHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Whether to include the buckets info within the response.
     *
     * Generated from protobuf field <code>bool need_buckets = 2;</code>
     * @return bool
     */
    public function getNeedBuckets()
    {
        return $this->need_buckets;
    }

    /**
     * Whether to include the buckets info within the response.
     *
     * Generated from protobuf field <code>bool need_buckets = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedBuckets($var)
    {
        GPBUtil::checkBool($var);
        $this->need_buckets = $var;

        return $this;
    }

    /**
     * The region IDs to query.
     *
     * Generated from protobuf field <code>repeated uint64 ids = 3;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * The region IDs to query.
     *
     * Generated from protobuf field <code>repeated uint64 ids = 3;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->ids = $arr;

        return $this;
    }

    /**
     * The region keys to query.
     *
     * Generated from protobuf field <code>repeated bytes keys = 4;</code>
     * @return RepeatedField<string>
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * The region keys to query.
     *
     * Generated from protobuf field <code>repeated bytes keys = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->keys = $arr;

        return $this;
    }

    /**
     * The previous region keys to query.
     *
     * Generated from protobuf field <code>repeated bytes prev_keys = 5;</code>
     * @return RepeatedField<string>
     */
    public function getPrevKeys()
    {
        return $this->prev_keys;
    }

    /**
     * The previous region keys to query.
     *
     * Generated from protobuf field <code>repeated bytes prev_keys = 5;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPrevKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->prev_keys = $arr;

        return $this;
    }

}

