<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.RegionHeartbeatRequest</code>
 */
class RegionHeartbeatRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     */
    protected $region = null;
    /**
     * Leader Peer sending the heartbeat.
     *
     * Generated from protobuf field <code>.metapb.Peer leader = 3;</code>
     */
    protected $leader = null;
    /**
     * Leader considers that these peers are down.
     *
     * Generated from protobuf field <code>repeated .pdpb.PeerStats down_peers = 4;</code>
     */
    private $down_peers;
    /**
     * Pending peers are the peers that the leader can't consider as
     * working followers.
     *
     * Generated from protobuf field <code>repeated .metapb.Peer pending_peers = 5;</code>
     */
    private $pending_peers;
    /**
     * Bytes read/written during this period.
     *
     * Generated from protobuf field <code>uint64 bytes_written = 6;</code>
     */
    protected $bytes_written = 0;
    /**
     * Generated from protobuf field <code>uint64 bytes_read = 7;</code>
     */
    protected $bytes_read = 0;
    /**
     * Keys read/written during this period.
     *
     * Generated from protobuf field <code>uint64 keys_written = 8;</code>
     */
    protected $keys_written = 0;
    /**
     * Generated from protobuf field <code>uint64 keys_read = 9;</code>
     */
    protected $keys_read = 0;
    /**
     * Approximate region size.
     *
     * Generated from protobuf field <code>uint64 approximate_size = 10;</code>
     */
    protected $approximate_size = 0;
    /**
     * Actually reported time interval
     *
     * Generated from protobuf field <code>.pdpb.TimeInterval interval = 12;</code>
     */
    protected $interval = null;
    /**
     * Approximate number of keys.
     *
     * Generated from protobuf field <code>uint64 approximate_keys = 13;</code>
     */
    protected $approximate_keys = 0;
    /**
     * Term is the term of raft group.
     *
     * Generated from protobuf field <code>uint64 term = 14;</code>
     */
    protected $term = 0;
    /**
     * Generated from protobuf field <code>.replication_modepb.RegionReplicationStatus replication_status = 15;</code>
     */
    protected $replication_status = null;
    /**
     * QueryStats reported write query stats, and there are read query stats in store heartbeat
     *
     * Generated from protobuf field <code>.pdpb.QueryStats query_stats = 16;</code>
     */
    protected $query_stats = null;
    /**
     * cpu_usage is the total CPU time usage of the leader region since the last heartbeat,
     * which is calculated by cpu_time_delta/heartbeat_reported_interval.
     * Deprecated: use cpu_stats instead.
     *
     * Generated from protobuf field <code>uint64 cpu_usage = 17 [deprecated = true];</code>
     * @deprecated
     */
    protected $cpu_usage = 0;
    /**
     * cpu_stats reports CPU usage breakdown for the leader region by kind
     * (e.g. unified read).
     *
     * Generated from protobuf field <code>.pdpb.CPUStats cpu_stats = 21;</code>
     */
    protected $cpu_stats = null;
    /**
     * Approximate size of row-based key-value pairs for billing.
     * It's counted on size of user key & value (excluding metadata fields), before compression, and latest versions only.
     *
     * Generated from protobuf field <code>uint64 approximate_kv_size = 18;</code>
     */
    protected $approximate_kv_size = 0;
    /**
     * Approximate size of column-based key-value pairs for billing.
     * It's counted on size of user key & value (excluding metadata fields), before compression, and latest versions only.
     *
     * Generated from protobuf field <code>uint64 approximate_columnar_kv_size = 19;</code>
     */
    protected $approximate_columnar_kv_size = 0;
    /**
     * BucketMeta is the bucket version and keys of this region if TiKV enabled the bucket feature
     *
     * Generated from protobuf field <code>.metapb.BucketMeta bucket_meta = 20;</code>
     */
    protected $bucket_meta = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\RequestHeader $header
     *     @type \CrazyGoat\Proto\Metapb\Region $region
     *     @type \CrazyGoat\Proto\Metapb\Peer $leader
     *           Leader Peer sending the heartbeat.
     *     @type \CrazyGoat\Proto\Pdpb\PeerStats[] $down_peers
     *           Leader considers that these peers are down.
     *     @type \CrazyGoat\Proto\Metapb\Peer[] $pending_peers
     *           Pending peers are the peers that the leader can't consider as
     *           working followers.
     *     @type int|string $bytes_written
     *           Bytes read/written during this period.
     *     @type int|string $bytes_read
     *     @type int|string $keys_written
     *           Keys read/written during this period.
     *     @type int|string $keys_read
     *     @type int|string $approximate_size
     *           Approximate region size.
     *     @type \CrazyGoat\Proto\Pdpb\TimeInterval $interval
     *           Actually reported time interval
     *     @type int|string $approximate_keys
     *           Approximate number of keys.
     *     @type int|string $term
     *           Term is the term of raft group.
     *     @type \CrazyGoat\Proto\ReplicationModepb\RegionReplicationStatus $replication_status
     *     @type \CrazyGoat\Proto\Pdpb\QueryStats $query_stats
     *           QueryStats reported write query stats, and there are read query stats in store heartbeat
     *     @type int|string $cpu_usage
     *           cpu_usage is the total CPU time usage of the leader region since the last heartbeat,
     *           which is calculated by cpu_time_delta/heartbeat_reported_interval.
     *           Deprecated: use cpu_stats instead.
     *     @type \CrazyGoat\Proto\Pdpb\CPUStats $cpu_stats
     *           cpu_stats reports CPU usage breakdown for the leader region by kind
     *           (e.g. unified read).
     *     @type int|string $approximate_kv_size
     *           Approximate size of row-based key-value pairs for billing.
     *           It's counted on size of user key & value (excluding metadata fields), before compression, and latest versions only.
     *     @type int|string $approximate_columnar_kv_size
     *           Approximate size of column-based key-value pairs for billing.
     *           It's counted on size of user key & value (excluding metadata fields), before compression, and latest versions only.
     *     @type \CrazyGoat\Proto\Metapb\BucketMeta $bucket_meta
     *           BucketMeta is the bucket version and keys of this region if TiKV enabled the bucket feature
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\RequestHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     * @return \CrazyGoat\Proto\Metapb\Region|null
     */
    public function getRegion()
    {
        return $this->region;
    }

    public function hasRegion()
    {
        return isset($this->region);
    }

    public function clearRegion()
    {
        unset($this->region);
    }

    /**
     * Generated from protobuf field <code>.metapb.Region region = 2;</code>
     * @param \CrazyGoat\Proto\Metapb\Region $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\Region::class);
        $this->region = $var;

        return $this;
    }

    /**
     * Leader Peer sending the heartbeat.
     *
     * Generated from protobuf field <code>.metapb.Peer leader = 3;</code>
     * @return \CrazyGoat\Proto\Metapb\Peer|null
     */
    public function getLeader()
    {
        return $this->leader;
    }

    public function hasLeader()
    {
        return isset($this->leader);
    }

    public function clearLeader()
    {
        unset($this->leader);
    }

    /**
     * Leader Peer sending the heartbeat.
     *
     * Generated from protobuf field <code>.metapb.Peer leader = 3;</code>
     * @param \CrazyGoat\Proto\Metapb\Peer $var
     * @return $this
     */
    public function setLeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\Peer::class);
        $this->leader = $var;

        return $this;
    }

    /**
     * Leader considers that these peers are down.
     *
     * Generated from protobuf field <code>repeated .pdpb.PeerStats down_peers = 4;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Pdpb\PeerStats>
     */
    public function getDownPeers()
    {
        return $this->down_peers;
    }

    /**
     * Leader considers that these peers are down.
     *
     * Generated from protobuf field <code>repeated .pdpb.PeerStats down_peers = 4;</code>
     * @param \CrazyGoat\Proto\Pdpb\PeerStats[] $var
     * @return $this
     */
    public function setDownPeers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Pdpb\PeerStats::class);
        $this->down_peers = $arr;

        return $this;
    }

    /**
     * Pending peers are the peers that the leader can't consider as
     * working followers.
     *
     * Generated from protobuf field <code>repeated .metapb.Peer pending_peers = 5;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Metapb\Peer>
     */
    public function getPendingPeers()
    {
        return $this->pending_peers;
    }

    /**
     * Pending peers are the peers that the leader can't consider as
     * working followers.
     *
     * Generated from protobuf field <code>repeated .metapb.Peer pending_peers = 5;</code>
     * @param \CrazyGoat\Proto\Metapb\Peer[] $var
     * @return $this
     */
    public function setPendingPeers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Metapb\Peer::class);
        $this->pending_peers = $arr;

        return $this;
    }

    /**
     * Bytes read/written during this period.
     *
     * Generated from protobuf field <code>uint64 bytes_written = 6;</code>
     * @return int|string
     */
    public function getBytesWritten()
    {
        return $this->bytes_written;
    }

    /**
     * Bytes read/written during this period.
     *
     * Generated from protobuf field <code>uint64 bytes_written = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBytesWritten($var)
    {
        GPBUtil::checkUint64($var);
        $this->bytes_written = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 bytes_read = 7;</code>
     * @return int|string
     */
    public function getBytesRead()
    {
        return $this->bytes_read;
    }

    /**
     * Generated from protobuf field <code>uint64 bytes_read = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBytesRead($var)
    {
        GPBUtil::checkUint64($var);
        $this->bytes_read = $var;

        return $this;
    }

    /**
     * Keys read/written during this period.
     *
     * Generated from protobuf field <code>uint64 keys_written = 8;</code>
     * @return int|string
     */
    public function getKeysWritten()
    {
        return $this->keys_written;
    }

    /**
     * Keys read/written during this period.
     *
     * Generated from protobuf field <code>uint64 keys_written = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setKeysWritten($var)
    {
        GPBUtil::checkUint64($var);
        $this->keys_written = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 keys_read = 9;</code>
     * @return int|string
     */
    public function getKeysRead()
    {
        return $this->keys_read;
    }

    /**
     * Generated from protobuf field <code>uint64 keys_read = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setKeysRead($var)
    {
        GPBUtil::checkUint64($var);
        $this->keys_read = $var;

        return $this;
    }

    /**
     * Approximate region size.
     *
     * Generated from protobuf field <code>uint64 approximate_size = 10;</code>
     * @return int|string
     */
    public function getApproximateSize()
    {
        return $this->approximate_size;
    }

    /**
     * Approximate region size.
     *
     * Generated from protobuf field <code>uint64 approximate_size = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApproximateSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->approximate_size = $var;

        return $this;
    }

    /**
     * Actually reported time interval
     *
     * Generated from protobuf field <code>.pdpb.TimeInterval interval = 12;</code>
     * @return \CrazyGoat\Proto\Pdpb\TimeInterval|null
     */
    public function getInterval()
    {
        return $this->interval;
    }

    public function hasInterval()
    {
        return isset($this->interval);
    }

    public function clearInterval()
    {
        unset($this->interval);
    }

    /**
     * Actually reported time interval
     *
     * Generated from protobuf field <code>.pdpb.TimeInterval interval = 12;</code>
     * @param \CrazyGoat\Proto\Pdpb\TimeInterval $var
     * @return $this
     */
    public function setInterval($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\TimeInterval::class);
        $this->interval = $var;

        return $this;
    }

    /**
     * Approximate number of keys.
     *
     * Generated from protobuf field <code>uint64 approximate_keys = 13;</code>
     * @return int|string
     */
    public function getApproximateKeys()
    {
        return $this->approximate_keys;
    }

    /**
     * Approximate number of keys.
     *
     * Generated from protobuf field <code>uint64 approximate_keys = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApproximateKeys($var)
    {
        GPBUtil::checkUint64($var);
        $this->approximate_keys = $var;

        return $this;
    }

    /**
     * Term is the term of raft group.
     *
     * Generated from protobuf field <code>uint64 term = 14;</code>
     * @return int|string
     */
    public function getTerm()
    {
        return $this->term;
    }

    /**
     * Term is the term of raft group.
     *
     * Generated from protobuf field <code>uint64 term = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTerm($var)
    {
        GPBUtil::checkUint64($var);
        $this->term = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.replication_modepb.RegionReplicationStatus replication_status = 15;</code>
     * @return \CrazyGoat\Proto\ReplicationModepb\RegionReplicationStatus|null
     */
    public function getReplicationStatus()
    {
        return $this->replication_status;
    }

    public function hasReplicationStatus()
    {
        return isset($this->replication_status);
    }

    public function clearReplicationStatus()
    {
        unset($this->replication_status);
    }

    /**
     * Generated from protobuf field <code>.replication_modepb.RegionReplicationStatus replication_status = 15;</code>
     * @param \CrazyGoat\Proto\ReplicationModepb\RegionReplicationStatus $var
     * @return $this
     */
    public function setReplicationStatus($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\ReplicationModepb\RegionReplicationStatus::class);
        $this->replication_status = $var;

        return $this;
    }

    /**
     * QueryStats reported write query stats, and there are read query stats in store heartbeat
     *
     * Generated from protobuf field <code>.pdpb.QueryStats query_stats = 16;</code>
     * @return \CrazyGoat\Proto\Pdpb\QueryStats|null
     */
    public function getQueryStats()
    {
        return $this->query_stats;
    }

    public function hasQueryStats()
    {
        return isset($this->query_stats);
    }

    public function clearQueryStats()
    {
        unset($this->query_stats);
    }

    /**
     * QueryStats reported write query stats, and there are read query stats in store heartbeat
     *
     * Generated from protobuf field <code>.pdpb.QueryStats query_stats = 16;</code>
     * @param \CrazyGoat\Proto\Pdpb\QueryStats $var
     * @return $this
     */
    public function setQueryStats($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\QueryStats::class);
        $this->query_stats = $var;

        return $this;
    }

    /**
     * cpu_usage is the total CPU time usage of the leader region since the last heartbeat,
     * which is calculated by cpu_time_delta/heartbeat_reported_interval.
     * Deprecated: use cpu_stats instead.
     *
     * Generated from protobuf field <code>uint64 cpu_usage = 17 [deprecated = true];</code>
     * @return int|string
     * @deprecated
     */
    public function getCpuUsage()
    {
        if ($this->cpu_usage !== 0) {
            @trigger_error('cpu_usage is deprecated.', E_USER_DEPRECATED);
        }
        return $this->cpu_usage;
    }

    /**
     * cpu_usage is the total CPU time usage of the leader region since the last heartbeat,
     * which is calculated by cpu_time_delta/heartbeat_reported_interval.
     * Deprecated: use cpu_stats instead.
     *
     * Generated from protobuf field <code>uint64 cpu_usage = 17 [deprecated = true];</code>
     * @param int|string $var
     * @return $this
     * @deprecated
     */
    public function setCpuUsage($var)
    {
        @trigger_error('cpu_usage is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkUint64($var);
        $this->cpu_usage = $var;

        return $this;
    }

    /**
     * cpu_stats reports CPU usage breakdown for the leader region by kind
     * (e.g. unified read).
     *
     * Generated from protobuf field <code>.pdpb.CPUStats cpu_stats = 21;</code>
     * @return \CrazyGoat\Proto\Pdpb\CPUStats|null
     */
    public function getCpuStats()
    {
        return $this->cpu_stats;
    }

    public function hasCpuStats()
    {
        return isset($this->cpu_stats);
    }

    public function clearCpuStats()
    {
        unset($this->cpu_stats);
    }

    /**
     * cpu_stats reports CPU usage breakdown for the leader region by kind
     * (e.g. unified read).
     *
     * Generated from protobuf field <code>.pdpb.CPUStats cpu_stats = 21;</code>
     * @param \CrazyGoat\Proto\Pdpb\CPUStats $var
     * @return $this
     */
    public function setCpuStats($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\CPUStats::class);
        $this->cpu_stats = $var;

        return $this;
    }

    /**
     * Approximate size of row-based key-value pairs for billing.
     * It's counted on size of user key & value (excluding metadata fields), before compression, and latest versions only.
     *
     * Generated from protobuf field <code>uint64 approximate_kv_size = 18;</code>
     * @return int|string
     */
    public function getApproximateKvSize()
    {
        return $this->approximate_kv_size;
    }

    /**
     * Approximate size of row-based key-value pairs for billing.
     * It's counted on size of user key & value (excluding metadata fields), before compression, and latest versions only.
     *
     * Generated from protobuf field <code>uint64 approximate_kv_size = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApproximateKvSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->approximate_kv_size = $var;

        return $this;
    }

    /**
     * Approximate size of column-based key-value pairs for billing.
     * It's counted on size of user key & value (excluding metadata fields), before compression, and latest versions only.
     *
     * Generated from protobuf field <code>uint64 approximate_columnar_kv_size = 19;</code>
     * @return int|string
     */
    public function getApproximateColumnarKvSize()
    {
        return $this->approximate_columnar_kv_size;
    }

    /**
     * Approximate size of column-based key-value pairs for billing.
     * It's counted on size of user key & value (excluding metadata fields), before compression, and latest versions only.
     *
     * Generated from protobuf field <code>uint64 approximate_columnar_kv_size = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setApproximateColumnarKvSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->approximate_columnar_kv_size = $var;

        return $this;
    }

    /**
     * BucketMeta is the bucket version and keys of this region if TiKV enabled the bucket feature
     *
     * Generated from protobuf field <code>.metapb.BucketMeta bucket_meta = 20;</code>
     * @return \CrazyGoat\Proto\Metapb\BucketMeta|null
     */
    public function getBucketMeta()
    {
        return $this->bucket_meta;
    }

    public function hasBucketMeta()
    {
        return isset($this->bucket_meta);
    }

    public function clearBucketMeta()
    {
        unset($this->bucket_meta);
    }

    /**
     * BucketMeta is the bucket version and keys of this region if TiKV enabled the bucket feature
     *
     * Generated from protobuf field <code>.metapb.BucketMeta bucket_meta = 20;</code>
     * @param \CrazyGoat\Proto\Metapb\BucketMeta $var
     * @return $this
     */
    public function setBucketMeta($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\BucketMeta::class);
        $this->bucket_meta = $var;

        return $this;
    }

}

