<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.ReportBucketsRequest</code>
 */
class ReportBucketsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 2;</code>
     */
    protected $region_epoch = null;
    /**
     * Generated from protobuf field <code>.metapb.Buckets buckets = 3;</code>
     */
    protected $buckets = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\RequestHeader $header
     *     @type \CrazyGoat\Proto\Metapb\RegionEpoch $region_epoch
     *     @type \CrazyGoat\Proto\Metapb\Buckets $buckets
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\RequestHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 2;</code>
     * @return \CrazyGoat\Proto\Metapb\RegionEpoch|null
     */
    public function getRegionEpoch()
    {
        return $this->region_epoch;
    }

    public function hasRegionEpoch()
    {
        return isset($this->region_epoch);
    }

    public function clearRegionEpoch()
    {
        unset($this->region_epoch);
    }

    /**
     * Generated from protobuf field <code>.metapb.RegionEpoch region_epoch = 2;</code>
     * @param \CrazyGoat\Proto\Metapb\RegionEpoch $var
     * @return $this
     */
    public function setRegionEpoch($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\RegionEpoch::class);
        $this->region_epoch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.Buckets buckets = 3;</code>
     * @return \CrazyGoat\Proto\Metapb\Buckets|null
     */
    public function getBuckets()
    {
        return $this->buckets;
    }

    public function hasBuckets()
    {
        return isset($this->buckets);
    }

    public function clearBuckets()
    {
        unset($this->buckets);
    }

    /**
     * Generated from protobuf field <code>.metapb.Buckets buckets = 3;</code>
     * @param \CrazyGoat\Proto\Metapb\Buckets $var
     * @return $this
     */
    public function setBuckets($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Metapb\Buckets::class);
        $this->buckets = $var;

        return $this;
    }

}

