<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.ScatterRegionRequest</code>
 */
class ScatterRegionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>uint64 region_id = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $region_id = 0;
    /**
     * PD will use these region information if it can't find the region.
     * For example, the region is just split and hasn't report to PD yet.
     *
     * Generated from protobuf field <code>.metapb.Region region = 3;</code>
     */
    protected $region = null;
    /**
     * Generated from protobuf field <code>.metapb.Peer leader = 4;</code>
     */
    protected $leader = null;
    /**
     * If group is defined, the regions with the same group would be scattered as a whole group.
     * If not defined, the regions would be scattered in a cluster level.
     *
     * Generated from protobuf field <code>string group = 5;</code>
     */
    protected $group = '';
    /**
     * If regions_id is defined, the region_id would be ignored.
     *
     * Generated from protobuf field <code>repeated uint64 regions_id = 6;</code>
     */
    private $regions_id;
    /**
     * Generated from protobuf field <code>uint64 retry_limit = 7;</code>
     */
    protected $retry_limit = 0;
    /**
     * Generated from protobuf field <code>bool skip_store_limit = 8;</code>
     */
    protected $skip_store_limit = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pdpb\RequestHeader $header
     *     @type int|string $region_id
     *     @type \Metapb\Region $region
     *           PD will use these region information if it can't find the region.
     *           For example, the region is just split and hasn't report to PD yet.
     *     @type \Metapb\Peer $leader
     *     @type string $group
     *           If group is defined, the regions with the same group would be scattered as a whole group.
     *           If not defined, the regions would be scattered in a cluster level.
     *     @type int[]|string[] $regions_id
     *           If regions_id is defined, the region_id would be ignored.
     *     @type int|string $retry_limit
     *     @type bool $skip_store_limit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Pdpb\RequestHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 region_id = 2 [deprecated = true];</code>
     * @return int|string
     * @deprecated
     */
    public function getRegionId()
    {
        if ($this->region_id !== 0) {
            @trigger_error('region_id is deprecated.', E_USER_DEPRECATED);
        }
        return $this->region_id;
    }

    /**
     * Generated from protobuf field <code>uint64 region_id = 2 [deprecated = true];</code>
     * @param int|string $var
     * @return $this
     * @deprecated
     */
    public function setRegionId($var)
    {
        @trigger_error('region_id is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkUint64($var);
        $this->region_id = $var;

        return $this;
    }

    /**
     * PD will use these region information if it can't find the region.
     * For example, the region is just split and hasn't report to PD yet.
     *
     * Generated from protobuf field <code>.metapb.Region region = 3;</code>
     * @return \Metapb\Region|null
     */
    public function getRegion()
    {
        return $this->region;
    }

    public function hasRegion()
    {
        return isset($this->region);
    }

    public function clearRegion()
    {
        unset($this->region);
    }

    /**
     * PD will use these region information if it can't find the region.
     * For example, the region is just split and hasn't report to PD yet.
     *
     * Generated from protobuf field <code>.metapb.Region region = 3;</code>
     * @param \Metapb\Region $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkMessage($var, \Metapb\Region::class);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.metapb.Peer leader = 4;</code>
     * @return \Metapb\Peer|null
     */
    public function getLeader()
    {
        return $this->leader;
    }

    public function hasLeader()
    {
        return isset($this->leader);
    }

    public function clearLeader()
    {
        unset($this->leader);
    }

    /**
     * Generated from protobuf field <code>.metapb.Peer leader = 4;</code>
     * @param \Metapb\Peer $var
     * @return $this
     */
    public function setLeader($var)
    {
        GPBUtil::checkMessage($var, \Metapb\Peer::class);
        $this->leader = $var;

        return $this;
    }

    /**
     * If group is defined, the regions with the same group would be scattered as a whole group.
     * If not defined, the regions would be scattered in a cluster level.
     *
     * Generated from protobuf field <code>string group = 5;</code>
     * @return string
     */
    public function getGroup()
    {
        return $this->group;
    }

    /**
     * If group is defined, the regions with the same group would be scattered as a whole group.
     * If not defined, the regions would be scattered in a cluster level.
     *
     * Generated from protobuf field <code>string group = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->group = $var;

        return $this;
    }

    /**
     * If regions_id is defined, the region_id would be ignored.
     *
     * Generated from protobuf field <code>repeated uint64 regions_id = 6;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getRegionsId()
    {
        return $this->regions_id;
    }

    /**
     * If regions_id is defined, the region_id would be ignored.
     *
     * Generated from protobuf field <code>repeated uint64 regions_id = 6;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setRegionsId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->regions_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 retry_limit = 7;</code>
     * @return int|string
     */
    public function getRetryLimit()
    {
        return $this->retry_limit;
    }

    /**
     * Generated from protobuf field <code>uint64 retry_limit = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRetryLimit($var)
    {
        GPBUtil::checkUint64($var);
        $this->retry_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool skip_store_limit = 8;</code>
     * @return bool
     */
    public function getSkipStoreLimit()
    {
        return $this->skip_store_limit;
    }

    /**
     * Generated from protobuf field <code>bool skip_store_limit = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setSkipStoreLimit($var)
    {
        GPBUtil::checkBool($var);
        $this->skip_store_limit = $var;

        return $this;
    }

}

