<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.SplitID</code>
 */
class SplitID extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 new_region_id = 1;</code>
     */
    protected $new_region_id = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 new_peer_ids = 2;</code>
     */
    private $new_peer_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $new_region_id
     *     @type int[]|string[] $new_peer_ids
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 new_region_id = 1;</code>
     * @return int|string
     */
    public function getNewRegionId()
    {
        return $this->new_region_id;
    }

    /**
     * Generated from protobuf field <code>uint64 new_region_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNewRegionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->new_region_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 new_peer_ids = 2;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getNewPeerIds()
    {
        return $this->new_peer_ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 new_peer_ids = 2;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setNewPeerIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->new_peer_ids = $arr;

        return $this;
    }

}

