<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.SplitRegionsResponse</code>
 */
class SplitRegionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>uint64 finished_percentage = 2;</code>
     */
    protected $finished_percentage = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 regions_id = 3;</code>
     */
    private $regions_id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pdpb\ResponseHeader $header
     *     @type int|string $finished_percentage
     *     @type int[]|string[] $regions_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 finished_percentage = 2;</code>
     * @return int|string
     */
    public function getFinishedPercentage()
    {
        return $this->finished_percentage;
    }

    /**
     * Generated from protobuf field <code>uint64 finished_percentage = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFinishedPercentage($var)
    {
        GPBUtil::checkUint64($var);
        $this->finished_percentage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 regions_id = 3;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getRegionsId()
    {
        return $this->regions_id;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 regions_id = 3;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setRegionsId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->regions_id = $arr;

        return $this;
    }

}

