<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.StoreHeartbeatResponse</code>
 */
class StoreHeartbeatResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.replication_modepb.ReplicationStatus replication_status = 2;</code>
     */
    protected $replication_status = null;
    /**
     * Generated from protobuf field <code>string cluster_version = 3;</code>
     */
    protected $cluster_version = '';
    /**
     * Used by online unsafe recovery to request store report.
     * Now it's substituted by reusing recovery_plan field. PD will send a empty
     * recovery plan instead to request store report.
     *
     * Generated from protobuf field <code>bool require_detailed_report = 4 [deprecated = true];</code>
     * @deprecated
     */
    protected $require_detailed_report = false;
    /**
     * Operations of recovery. After the plan is executed, TiKV should attach the
     * store report in store heartbeat.
     *
     * Generated from protobuf field <code>.pdpb.RecoveryPlan recovery_plan = 5;</code>
     */
    protected $recovery_plan = null;
    /**
     * Pd can return awaken_regions to let TiKV awaken hibernated regions itself.
     *
     * Generated from protobuf field <code>.pdpb.AwakenRegions awaken_regions = 6;</code>
     */
    protected $awaken_regions = null;
    /**
     * Pd can return operations to let TiKV forcely PAUSE | RESUME grpc server.
     *
     * Generated from protobuf field <code>.pdpb.ControlGrpc control_grpc = 7;</code>
     */
    protected $control_grpc = null;
    /**
     * NodeState is going to mark the state of the store.
     *
     * Generated from protobuf field <code>.metapb.NodeState state = 8;</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\ResponseHeader $header
     *     @type \CrazyGoat\Proto\ReplicationModepb\ReplicationStatus $replication_status
     *     @type string $cluster_version
     *     @type bool $require_detailed_report
     *           Used by online unsafe recovery to request store report.
     *           Now it's substituted by reusing recovery_plan field. PD will send a empty
     *           recovery plan instead to request store report.
     *     @type \CrazyGoat\Proto\Pdpb\RecoveryPlan $recovery_plan
     *           Operations of recovery. After the plan is executed, TiKV should attach the
     *           store report in store heartbeat.
     *     @type \CrazyGoat\Proto\Pdpb\AwakenRegions $awaken_regions
     *           Pd can return awaken_regions to let TiKV awaken hibernated regions itself.
     *     @type \CrazyGoat\Proto\Pdpb\ControlGrpc $control_grpc
     *           Pd can return operations to let TiKV forcely PAUSE | RESUME grpc server.
     *     @type int $state
     *           NodeState is going to mark the state of the store.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.replication_modepb.ReplicationStatus replication_status = 2;</code>
     * @return \CrazyGoat\Proto\ReplicationModepb\ReplicationStatus|null
     */
    public function getReplicationStatus()
    {
        return $this->replication_status;
    }

    public function hasReplicationStatus()
    {
        return isset($this->replication_status);
    }

    public function clearReplicationStatus()
    {
        unset($this->replication_status);
    }

    /**
     * Generated from protobuf field <code>.replication_modepb.ReplicationStatus replication_status = 2;</code>
     * @param \CrazyGoat\Proto\ReplicationModepb\ReplicationStatus $var
     * @return $this
     */
    public function setReplicationStatus($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\ReplicationModepb\ReplicationStatus::class);
        $this->replication_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cluster_version = 3;</code>
     * @return string
     */
    public function getClusterVersion()
    {
        return $this->cluster_version;
    }

    /**
     * Generated from protobuf field <code>string cluster_version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClusterVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->cluster_version = $var;

        return $this;
    }

    /**
     * Used by online unsafe recovery to request store report.
     * Now it's substituted by reusing recovery_plan field. PD will send a empty
     * recovery plan instead to request store report.
     *
     * Generated from protobuf field <code>bool require_detailed_report = 4 [deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getRequireDetailedReport()
    {
        if ($this->require_detailed_report !== false) {
            @trigger_error('require_detailed_report is deprecated.', E_USER_DEPRECATED);
        }
        return $this->require_detailed_report;
    }

    /**
     * Used by online unsafe recovery to request store report.
     * Now it's substituted by reusing recovery_plan field. PD will send a empty
     * recovery plan instead to request store report.
     *
     * Generated from protobuf field <code>bool require_detailed_report = 4 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setRequireDetailedReport($var)
    {
        @trigger_error('require_detailed_report is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkBool($var);
        $this->require_detailed_report = $var;

        return $this;
    }

    /**
     * Operations of recovery. After the plan is executed, TiKV should attach the
     * store report in store heartbeat.
     *
     * Generated from protobuf field <code>.pdpb.RecoveryPlan recovery_plan = 5;</code>
     * @return \CrazyGoat\Proto\Pdpb\RecoveryPlan|null
     */
    public function getRecoveryPlan()
    {
        return $this->recovery_plan;
    }

    public function hasRecoveryPlan()
    {
        return isset($this->recovery_plan);
    }

    public function clearRecoveryPlan()
    {
        unset($this->recovery_plan);
    }

    /**
     * Operations of recovery. After the plan is executed, TiKV should attach the
     * store report in store heartbeat.
     *
     * Generated from protobuf field <code>.pdpb.RecoveryPlan recovery_plan = 5;</code>
     * @param \CrazyGoat\Proto\Pdpb\RecoveryPlan $var
     * @return $this
     */
    public function setRecoveryPlan($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\RecoveryPlan::class);
        $this->recovery_plan = $var;

        return $this;
    }

    /**
     * Pd can return awaken_regions to let TiKV awaken hibernated regions itself.
     *
     * Generated from protobuf field <code>.pdpb.AwakenRegions awaken_regions = 6;</code>
     * @return \CrazyGoat\Proto\Pdpb\AwakenRegions|null
     */
    public function getAwakenRegions()
    {
        return $this->awaken_regions;
    }

    public function hasAwakenRegions()
    {
        return isset($this->awaken_regions);
    }

    public function clearAwakenRegions()
    {
        unset($this->awaken_regions);
    }

    /**
     * Pd can return awaken_regions to let TiKV awaken hibernated regions itself.
     *
     * Generated from protobuf field <code>.pdpb.AwakenRegions awaken_regions = 6;</code>
     * @param \CrazyGoat\Proto\Pdpb\AwakenRegions $var
     * @return $this
     */
    public function setAwakenRegions($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\AwakenRegions::class);
        $this->awaken_regions = $var;

        return $this;
    }

    /**
     * Pd can return operations to let TiKV forcely PAUSE | RESUME grpc server.
     *
     * Generated from protobuf field <code>.pdpb.ControlGrpc control_grpc = 7;</code>
     * @return \CrazyGoat\Proto\Pdpb\ControlGrpc|null
     */
    public function getControlGrpc()
    {
        return $this->control_grpc;
    }

    public function hasControlGrpc()
    {
        return isset($this->control_grpc);
    }

    public function clearControlGrpc()
    {
        unset($this->control_grpc);
    }

    /**
     * Pd can return operations to let TiKV forcely PAUSE | RESUME grpc server.
     *
     * Generated from protobuf field <code>.pdpb.ControlGrpc control_grpc = 7;</code>
     * @param \CrazyGoat\Proto\Pdpb\ControlGrpc $var
     * @return $this
     */
    public function setControlGrpc($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\ControlGrpc::class);
        $this->control_grpc = $var;

        return $this;
    }

    /**
     * NodeState is going to mark the state of the store.
     *
     * Generated from protobuf field <code>.metapb.NodeState state = 8;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * NodeState is going to mark the state of the store.
     *
     * Generated from protobuf field <code>.metapb.NodeState state = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Metapb\NodeState::class);
        $this->state = $var;

        return $this;
    }

}

