<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.SwitchWitness</code>
 */
class SwitchWitness extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 peer_id = 1;</code>
     */
    protected $peer_id = 0;
    /**
     * Generated from protobuf field <code>bool is_witness = 2;</code>
     */
    protected $is_witness = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $peer_id
     *     @type bool $is_witness
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 peer_id = 1;</code>
     * @return int|string
     */
    public function getPeerId()
    {
        return $this->peer_id;
    }

    /**
     * Generated from protobuf field <code>uint64 peer_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPeerId($var)
    {
        GPBUtil::checkUint64($var);
        $this->peer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_witness = 2;</code>
     * @return bool
     */
    public function getIsWitness()
    {
        return $this->is_witness;
    }

    /**
     * Generated from protobuf field <code>bool is_witness = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsWitness($var)
    {
        GPBUtil::checkBool($var);
        $this->is_witness = $var;

        return $this;
    }

}

