<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.SyncMaxTSResponse</code>
 */
class SyncMaxTSResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.pdpb.Timestamp max_local_ts = 2;</code>
     */
    protected $max_local_ts = null;
    /**
     * Generated from protobuf field <code>repeated string synced_dcs = 3;</code>
     */
    private $synced_dcs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\ResponseHeader $header
     *     @type \CrazyGoat\Proto\Pdpb\Timestamp $max_local_ts
     *     @type string[] $synced_dcs
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pdpb.Timestamp max_local_ts = 2;</code>
     * @return \CrazyGoat\Proto\Pdpb\Timestamp|null
     */
    public function getMaxLocalTs()
    {
        return $this->max_local_ts;
    }

    public function hasMaxLocalTs()
    {
        return isset($this->max_local_ts);
    }

    public function clearMaxLocalTs()
    {
        unset($this->max_local_ts);
    }

    /**
     * Generated from protobuf field <code>.pdpb.Timestamp max_local_ts = 2;</code>
     * @param \CrazyGoat\Proto\Pdpb\Timestamp $var
     * @return $this
     */
    public function setMaxLocalTs($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\Timestamp::class);
        $this->max_local_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string synced_dcs = 3;</code>
     * @return RepeatedField<string>
     */
    public function getSyncedDcs()
    {
        return $this->synced_dcs;
    }

    /**
     * Generated from protobuf field <code>repeated string synced_dcs = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSyncedDcs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->synced_dcs = $arr;

        return $this;
    }

}

