<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.SyncMaxTSRequest</code>
 */
class SyncMaxTSRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>.pdpb.Timestamp max_ts = 2;</code>
     */
    protected $max_ts = null;
    /**
     * If skip_check is true, the sync will try to write the max_ts without checking whether it's bigger.
     *
     * Generated from protobuf field <code>bool skip_check = 3;</code>
     */
    protected $skip_check = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\RequestHeader $header
     *     @type \CrazyGoat\Proto\Pdpb\Timestamp $max_ts
     *     @type bool $skip_check
     *           If skip_check is true, the sync will try to write the max_ts without checking whether it's bigger.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\RequestHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pdpb.Timestamp max_ts = 2;</code>
     * @return \CrazyGoat\Proto\Pdpb\Timestamp|null
     */
    public function getMaxTs()
    {
        return $this->max_ts;
    }

    public function hasMaxTs()
    {
        return isset($this->max_ts);
    }

    public function clearMaxTs()
    {
        unset($this->max_ts);
    }

    /**
     * Generated from protobuf field <code>.pdpb.Timestamp max_ts = 2;</code>
     * @param \CrazyGoat\Proto\Pdpb\Timestamp $var
     * @return $this
     */
    public function setMaxTs($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\Timestamp::class);
        $this->max_ts = $var;

        return $this;
    }

    /**
     * If skip_check is true, the sync will try to write the max_ts without checking whether it's bigger.
     *
     * Generated from protobuf field <code>bool skip_check = 3;</code>
     * @return bool
     */
    public function getSkipCheck()
    {
        return $this->skip_check;
    }

    /**
     * If skip_check is true, the sync will try to write the max_ts without checking whether it's bigger.
     *
     * Generated from protobuf field <code>bool skip_check = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSkipCheck($var)
    {
        GPBUtil::checkBool($var);
        $this->skip_check = $var;

        return $this;
    }

}

