<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.UpdateServiceGCSafePointResponse</code>
 */
class UpdateServiceGCSafePointResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>bytes service_id = 2;</code>
     */
    protected $service_id = '';
    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     */
    protected $TTL = 0;
    /**
     * Generated from protobuf field <code>uint64 min_safe_point = 4;</code>
     */
    protected $min_safe_point = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pdpb\ResponseHeader $header
     *     @type string $service_id
     *     @type int|string $TTL
     *     @type int|string $min_safe_point
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes service_id = 2;</code>
     * @return string
     */
    public function getServiceId()
    {
        return $this->service_id;
    }

    /**
     * Generated from protobuf field <code>bytes service_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     * @return int|string
     */
    public function getTTL()
    {
        return $this->TTL;
    }

    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTTL($var)
    {
        GPBUtil::checkInt64($var);
        $this->TTL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 min_safe_point = 4;</code>
     * @return int|string
     */
    public function getMinSafePoint()
    {
        return $this->min_safe_point;
    }

    /**
     * Generated from protobuf field <code>uint64 min_safe_point = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinSafePoint($var)
    {
        GPBUtil::checkUint64($var);
        $this->min_safe_point = $var;

        return $this;
    }

}

