<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace CrazyGoat\Proto\Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.UpdateServiceGCSafePointRequest</code>
 */
class UpdateServiceGCSafePointRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>bytes service_id = 2;</code>
     */
    protected $service_id = '';
    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     */
    protected $TTL = 0;
    /**
     * Generated from protobuf field <code>uint64 safe_point = 4;</code>
     */
    protected $safe_point = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Pdpb\RequestHeader $header
     *     @type string $service_id
     *     @type int|string $TTL
     *     @type int|string $safe_point
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @return \CrazyGoat\Proto\Pdpb\RequestHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.RequestHeader header = 1;</code>
     * @param \CrazyGoat\Proto\Pdpb\RequestHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Pdpb\RequestHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes service_id = 2;</code>
     * @return string
     */
    public function getServiceId()
    {
        return $this->service_id;
    }

    /**
     * Generated from protobuf field <code>bytes service_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkString($var, False);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     * @return int|string
     */
    public function getTTL()
    {
        return $this->TTL;
    }

    /**
     * Generated from protobuf field <code>int64 TTL = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTTL($var)
    {
        GPBUtil::checkInt64($var);
        $this->TTL = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 safe_point = 4;</code>
     * @return int|string
     */
    public function getSafePoint()
    {
        return $this->safe_point;
    }

    /**
     * Generated from protobuf field <code>uint64 safe_point = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSafePoint($var)
    {
        GPBUtil::checkUint64($var);
        $this->safe_point = $var;

        return $this;
    }

}

