<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.WatchGlobalConfigResponse</code>
 */
class WatchGlobalConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pdpb.GlobalConfigItem changes = 1;</code>
     */
    private $changes;
    /**
     * Generated from protobuf field <code>int64 revision = 2;</code>
     */
    protected $revision = 0;
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 3;</code>
     */
    protected $header = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pdpb\GlobalConfigItem[] $changes
     *     @type int|string $revision
     *     @type \Pdpb\ResponseHeader $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pdpb.GlobalConfigItem changes = 1;</code>
     * @return RepeatedField<\Pdpb\GlobalConfigItem>
     */
    public function getChanges()
    {
        return $this->changes;
    }

    /**
     * Generated from protobuf field <code>repeated .pdpb.GlobalConfigItem changes = 1;</code>
     * @param \Pdpb\GlobalConfigItem[] $var
     * @return $this
     */
    public function setChanges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pdpb\GlobalConfigItem::class);
        $this->changes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 revision = 2;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * Generated from protobuf field <code>int64 revision = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->revision = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 3;</code>
     * @return \Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 3;</code>
     * @param \Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

}

