<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pdpb.proto

namespace Pdpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>pdpb.WatchGCSafePointV2Response</code>
 */
class WatchGCSafePointV2Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>repeated .pdpb.SafePointEvent events = 2;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>int64 revision = 3;</code>
     */
    protected $revision = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pdpb\ResponseHeader $header
     *     @type \Pdpb\SafePointEvent[] $events
     *     @type int|string $revision
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pdpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @return \Pdpb\ResponseHeader|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.pdpb.ResponseHeader header = 1;</code>
     * @param \Pdpb\ResponseHeader $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Pdpb\ResponseHeader::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .pdpb.SafePointEvent events = 2;</code>
     * @return RepeatedField<\Pdpb\SafePointEvent>
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .pdpb.SafePointEvent events = 2;</code>
     * @param \Pdpb\SafePointEvent[] $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pdpb\SafePointEvent::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 revision = 3;</code>
     * @return int|string
     */
    public function getRevision()
    {
        return $this->revision;
    }

    /**
     * Generated from protobuf field <code>int64 revision = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRevision($var)
    {
        GPBUtil::checkInt64($var);
        $this->revision = $var;

        return $this;
    }

}

