<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace CrazyGoat\Proto\ResourceManager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resource_manager.ListResourceGroupsResponse</code>
 */
class ListResourceGroupsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.resource_manager.Error error = 1;</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>repeated .resource_manager.ResourceGroup groups = 2;</code>
     */
    private $groups;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\ResourceManager\Error $error
     *     @type \CrazyGoat\Proto\ResourceManager\ResourceGroup[] $groups
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ResourceManager::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.resource_manager.Error error = 1;</code>
     * @return \CrazyGoat\Proto\ResourceManager\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.resource_manager.Error error = 1;</code>
     * @param \CrazyGoat\Proto\ResourceManager\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\ResourceManager\Error::class);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .resource_manager.ResourceGroup groups = 2;</code>
     * @return RepeatedField<\CrazyGoat\Proto\ResourceManager\ResourceGroup>
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Generated from protobuf field <code>repeated .resource_manager.ResourceGroup groups = 2;</code>
     * @param \CrazyGoat\Proto\ResourceManager\ResourceGroup[] $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\ResourceManager\ResourceGroup::class);
        $this->groups = $arr;

        return $this;
    }

}

