<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace CrazyGoat\Proto\ResourceManager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resource_manager.ListResourceGroupsRequest</code>
 */
class ListResourceGroupsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool with_ru_stats = 1;</code>
     */
    protected $with_ru_stats = false;
    /**
     * There're two cases for this field:
     *   - If the keyspace ID is not set, it means this may be a message from an older version.
     *     To maintain compatibility, we will treat it as a null keyspace ID, which is uint32.Max.
     *   - If the keyspace ID is set to a valid value, the listed resource groups will be filtered
     *     by the given keyspace ID.
     *
     * Generated from protobuf field <code>.resource_manager.KeyspaceIDValue keyspace_id = 2;</code>
     */
    protected $keyspace_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $with_ru_stats
     *     @type \CrazyGoat\Proto\ResourceManager\KeyspaceIDValue $keyspace_id
     *           There're two cases for this field:
     *             - If the keyspace ID is not set, it means this may be a message from an older version.
     *               To maintain compatibility, we will treat it as a null keyspace ID, which is uint32.Max.
     *             - If the keyspace ID is set to a valid value, the listed resource groups will be filtered
     *               by the given keyspace ID.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ResourceManager::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool with_ru_stats = 1;</code>
     * @return bool
     */
    public function getWithRuStats()
    {
        return $this->with_ru_stats;
    }

    /**
     * Generated from protobuf field <code>bool with_ru_stats = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setWithRuStats($var)
    {
        GPBUtil::checkBool($var);
        $this->with_ru_stats = $var;

        return $this;
    }

    /**
     * There're two cases for this field:
     *   - If the keyspace ID is not set, it means this may be a message from an older version.
     *     To maintain compatibility, we will treat it as a null keyspace ID, which is uint32.Max.
     *   - If the keyspace ID is set to a valid value, the listed resource groups will be filtered
     *     by the given keyspace ID.
     *
     * Generated from protobuf field <code>.resource_manager.KeyspaceIDValue keyspace_id = 2;</code>
     * @return \CrazyGoat\Proto\ResourceManager\KeyspaceIDValue|null
     */
    public function getKeyspaceId()
    {
        return $this->keyspace_id;
    }

    public function hasKeyspaceId()
    {
        return isset($this->keyspace_id);
    }

    public function clearKeyspaceId()
    {
        unset($this->keyspace_id);
    }

    /**
     * There're two cases for this field:
     *   - If the keyspace ID is not set, it means this may be a message from an older version.
     *     To maintain compatibility, we will treat it as a null keyspace ID, which is uint32.Max.
     *   - If the keyspace ID is set to a valid value, the listed resource groups will be filtered
     *     by the given keyspace ID.
     *
     * Generated from protobuf field <code>.resource_manager.KeyspaceIDValue keyspace_id = 2;</code>
     * @param \CrazyGoat\Proto\ResourceManager\KeyspaceIDValue $var
     * @return $this
     */
    public function setKeyspaceId($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\ResourceManager\KeyspaceIDValue::class);
        $this->keyspace_id = $var;

        return $this;
    }

}

