<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace CrazyGoat\Proto\ResourceManager;

use UnexpectedValueException;

/**
 * Protobuf type <code>resource_manager.RunawayWatchType</code>
 */
class RunawayWatchType
{
    /**
     * Generated from protobuf enum <code>NoneWatch = 0;</code>
     */
    const NoneWatch = 0;
    /**
     * Generated from protobuf enum <code>Exact = 1;</code>
     */
    const Exact = 1;
    /**
     * Generated from protobuf enum <code>Similar = 2;</code>
     */
    const Similar = 2;
    /**
     * Generated from protobuf enum <code>Plan = 3;</code>
     */
    const Plan = 3;

    private static $valueToName = [
        self::NoneWatch => 'NoneWatch',
        self::Exact => 'Exact',
        self::Similar => 'Similar',
        self::Plan => 'Plan',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

