<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace CrazyGoat\Proto\ResourceManager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resource_manager.TokenBucketsRequest</code>
 */
class TokenBucketsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .resource_manager.TokenBucketRequest requests = 1;</code>
     */
    private $requests;
    /**
     * Generated from protobuf field <code>uint64 target_request_period_ms = 2;</code>
     */
    protected $target_request_period_ms = 0;
    /**
     * Generated from protobuf field <code>uint64 client_unique_id = 3;</code>
     */
    protected $client_unique_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\ResourceManager\TokenBucketRequest[] $requests
     *     @type int|string $target_request_period_ms
     *     @type int|string $client_unique_id
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ResourceManager::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .resource_manager.TokenBucketRequest requests = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\ResourceManager\TokenBucketRequest>
     */
    public function getRequests()
    {
        return $this->requests;
    }

    /**
     * Generated from protobuf field <code>repeated .resource_manager.TokenBucketRequest requests = 1;</code>
     * @param \CrazyGoat\Proto\ResourceManager\TokenBucketRequest[] $var
     * @return $this
     */
    public function setRequests($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\ResourceManager\TokenBucketRequest::class);
        $this->requests = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 target_request_period_ms = 2;</code>
     * @return int|string
     */
    public function getTargetRequestPeriodMs()
    {
        return $this->target_request_period_ms;
    }

    /**
     * Generated from protobuf field <code>uint64 target_request_period_ms = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTargetRequestPeriodMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->target_request_period_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 client_unique_id = 3;</code>
     * @return int|string
     */
    public function getClientUniqueId()
    {
        return $this->client_unique_id;
    }

    /**
     * Generated from protobuf field <code>uint64 client_unique_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientUniqueId($var)
    {
        GPBUtil::checkUint64($var);
        $this->client_unique_id = $var;

        return $this;
    }

}

