<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace CrazyGoat\Proto\ResourceManager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resource_manager.TokenLimitSettings</code>
 */
class TokenLimitSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 fill_rate = 1;</code>
     */
    protected $fill_rate = 0;
    /**
     * Generated from protobuf field <code>int64 burst_limit = 2;</code>
     */
    protected $burst_limit = 0;
    /**
     * Generated from protobuf field <code>double max_tokens = 3;</code>
     */
    protected $max_tokens = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $fill_rate
     *     @type int|string $burst_limit
     *     @type float $max_tokens
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\ResourceManager::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 fill_rate = 1;</code>
     * @return int|string
     */
    public function getFillRate()
    {
        return $this->fill_rate;
    }

    /**
     * Generated from protobuf field <code>uint64 fill_rate = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFillRate($var)
    {
        GPBUtil::checkUint64($var);
        $this->fill_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 burst_limit = 2;</code>
     * @return int|string
     */
    public function getBurstLimit()
    {
        return $this->burst_limit;
    }

    /**
     * Generated from protobuf field <code>int64 burst_limit = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBurstLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->burst_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double max_tokens = 3;</code>
     * @return float
     */
    public function getMaxTokens()
    {
        return $this->max_tokens;
    }

    /**
     * Generated from protobuf field <code>double max_tokens = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxTokens($var)
    {
        GPBUtil::checkDouble($var);
        $this->max_tokens = $var;

        return $this;
    }

}

