<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpp.proto

namespace CrazyGoat\Proto\Mpp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Dipsatch the task request to different tiflash servers.
 *
 * Generated from protobuf message <code>mpp.DispatchTaskRequest</code>
 */
class DispatchTaskRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.mpp.TaskMeta meta = 1;</code>
     */
    protected $meta = null;
    /**
     * Generated from protobuf field <code>bytes encoded_plan = 2;</code>
     */
    protected $encoded_plan = '';
    /**
     * Generated from protobuf field <code>int64 timeout = 3;</code>
     */
    protected $timeout = 0;
    /**
     * Generated from protobuf field <code>repeated .coprocessor.RegionInfo regions = 4;</code>
     */
    private $regions;
    /**
     * If this task contains table scan, we still need their region info.
     *
     * Generated from protobuf field <code>int64 schema_ver = 5;</code>
     */
    protected $schema_ver = 0;
    /**
     * Used for partition table scan
     *
     * Generated from protobuf field <code>repeated .coprocessor.TableRegions table_regions = 6;</code>
     */
    private $table_regions;
    /**
     * Shard infos for TiCI/FTS routing in MPP dispatch path.
     *
     * Generated from protobuf field <code>repeated .coprocessor.TableShardInfos table_shard_infos = 7;</code>
     */
    private $table_shard_infos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Mpp\TaskMeta $meta
     *     @type string $encoded_plan
     *     @type int|string $timeout
     *     @type \CrazyGoat\Proto\Coprocessor\RegionInfo[] $regions
     *     @type int|string $schema_ver
     *           If this task contains table scan, we still need their region info.
     *     @type \CrazyGoat\Proto\Coprocessor\TableRegions[] $table_regions
     *           Used for partition table scan
     *     @type \CrazyGoat\Proto\Coprocessor\TableShardInfos[] $table_shard_infos
     *           Shard infos for TiCI/FTS routing in MPP dispatch path.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Mpp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.mpp.TaskMeta meta = 1;</code>
     * @return \CrazyGoat\Proto\Mpp\TaskMeta|null
     */
    public function getMeta()
    {
        return $this->meta;
    }

    public function hasMeta()
    {
        return isset($this->meta);
    }

    public function clearMeta()
    {
        unset($this->meta);
    }

    /**
     * Generated from protobuf field <code>.mpp.TaskMeta meta = 1;</code>
     * @param \CrazyGoat\Proto\Mpp\TaskMeta $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Mpp\TaskMeta::class);
        $this->meta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes encoded_plan = 2;</code>
     * @return string
     */
    public function getEncodedPlan()
    {
        return $this->encoded_plan;
    }

    /**
     * Generated from protobuf field <code>bytes encoded_plan = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEncodedPlan($var)
    {
        GPBUtil::checkString($var, False);
        $this->encoded_plan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timeout = 3;</code>
     * @return int|string
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>int64 timeout = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkInt64($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .coprocessor.RegionInfo regions = 4;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Coprocessor\RegionInfo>
     */
    public function getRegions()
    {
        return $this->regions;
    }

    /**
     * Generated from protobuf field <code>repeated .coprocessor.RegionInfo regions = 4;</code>
     * @param \CrazyGoat\Proto\Coprocessor\RegionInfo[] $var
     * @return $this
     */
    public function setRegions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Coprocessor\RegionInfo::class);
        $this->regions = $arr;

        return $this;
    }

    /**
     * If this task contains table scan, we still need their region info.
     *
     * Generated from protobuf field <code>int64 schema_ver = 5;</code>
     * @return int|string
     */
    public function getSchemaVer()
    {
        return $this->schema_ver;
    }

    /**
     * If this task contains table scan, we still need their region info.
     *
     * Generated from protobuf field <code>int64 schema_ver = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSchemaVer($var)
    {
        GPBUtil::checkInt64($var);
        $this->schema_ver = $var;

        return $this;
    }

    /**
     * Used for partition table scan
     *
     * Generated from protobuf field <code>repeated .coprocessor.TableRegions table_regions = 6;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Coprocessor\TableRegions>
     */
    public function getTableRegions()
    {
        return $this->table_regions;
    }

    /**
     * Used for partition table scan
     *
     * Generated from protobuf field <code>repeated .coprocessor.TableRegions table_regions = 6;</code>
     * @param \CrazyGoat\Proto\Coprocessor\TableRegions[] $var
     * @return $this
     */
    public function setTableRegions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Coprocessor\TableRegions::class);
        $this->table_regions = $arr;

        return $this;
    }

    /**
     * Shard infos for TiCI/FTS routing in MPP dispatch path.
     *
     * Generated from protobuf field <code>repeated .coprocessor.TableShardInfos table_shard_infos = 7;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Coprocessor\TableShardInfos>
     */
    public function getTableShardInfos()
    {
        return $this->table_shard_infos;
    }

    /**
     * Shard infos for TiCI/FTS routing in MPP dispatch path.
     *
     * Generated from protobuf field <code>repeated .coprocessor.TableShardInfos table_shard_infos = 7;</code>
     * @param \CrazyGoat\Proto\Coprocessor\TableShardInfos[] $var
     * @return $this
     */
    public function setTableShardInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Coprocessor\TableShardInfos::class);
        $this->table_shard_infos = $arr;

        return $this;
    }

}

