<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deadlock.proto

namespace Deadlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>deadlock.ReplaceLocksByKeysRequest</code>
 */
class ReplaceLocksByKeysRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .deadlock.ReplaceLockByKeyItem items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Deadlock\ReplaceLockByKeyItem[] $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Deadlock::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .deadlock.ReplaceLockByKeyItem items = 1;</code>
     * @return RepeatedField<\Deadlock\ReplaceLockByKeyItem>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .deadlock.ReplaceLockByKeyItem items = 1;</code>
     * @param \Deadlock\ReplaceLockByKeyItem[] $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Deadlock\ReplaceLockByKeyItem::class);
        $this->items = $arr;

        return $this;
    }

}

