<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deadlock.proto

namespace Deadlock;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>deadlock.ReplaceLockByKeyItem</code>
 */
class ReplaceLockByKeyItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 key_hash = 1;</code>
     */
    protected $key_hash = 0;
    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>uint64 old_lock_ts = 3;</code>
     */
    protected $old_lock_ts = 0;
    /**
     * Generated from protobuf field <code>uint64 new_lock_ts = 4;</code>
     */
    protected $new_lock_ts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $key_hash
     *     @type string $key
     *     @type int|string $old_lock_ts
     *     @type int|string $new_lock_ts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Deadlock::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 key_hash = 1;</code>
     * @return int|string
     */
    public function getKeyHash()
    {
        return $this->key_hash;
    }

    /**
     * Generated from protobuf field <code>uint64 key_hash = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setKeyHash($var)
    {
        GPBUtil::checkUint64($var);
        $this->key_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 old_lock_ts = 3;</code>
     * @return int|string
     */
    public function getOldLockTs()
    {
        return $this->old_lock_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 old_lock_ts = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOldLockTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->old_lock_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 new_lock_ts = 4;</code>
     * @return int|string
     */
    public function getNewLockTs()
    {
        return $this->new_lock_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 new_lock_ts = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNewLockTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->new_lock_ts = $var;

        return $this;
    }

}

