<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace Resource_manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resource_manager.GroupRawResourceSettings</code>
 */
class GroupRawResourceSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket cpu = 1;</code>
     */
    protected $cpu = null;
    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket io_read = 2;</code>
     */
    protected $io_read = null;
    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket io_write = 3;</code>
     */
    protected $io_write = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Resource_manager\TokenBucket $cpu
     *     @type \Resource_manager\TokenBucket $io_read
     *     @type \Resource_manager\TokenBucket $io_write
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ResourceManager::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket cpu = 1;</code>
     * @return \Resource_manager\TokenBucket|null
     */
    public function getCpu()
    {
        return $this->cpu;
    }

    public function hasCpu()
    {
        return isset($this->cpu);
    }

    public function clearCpu()
    {
        unset($this->cpu);
    }

    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket cpu = 1;</code>
     * @param \Resource_manager\TokenBucket $var
     * @return $this
     */
    public function setCpu($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\TokenBucket::class);
        $this->cpu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket io_read = 2;</code>
     * @return \Resource_manager\TokenBucket|null
     */
    public function getIoRead()
    {
        return $this->io_read;
    }

    public function hasIoRead()
    {
        return isset($this->io_read);
    }

    public function clearIoRead()
    {
        unset($this->io_read);
    }

    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket io_read = 2;</code>
     * @param \Resource_manager\TokenBucket $var
     * @return $this
     */
    public function setIoRead($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\TokenBucket::class);
        $this->io_read = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket io_write = 3;</code>
     * @return \Resource_manager\TokenBucket|null
     */
    public function getIoWrite()
    {
        return $this->io_write;
    }

    public function hasIoWrite()
    {
        return isset($this->io_write);
    }

    public function clearIoWrite()
    {
        unset($this->io_write);
    }

    /**
     * Generated from protobuf field <code>.resource_manager.TokenBucket io_write = 3;</code>
     * @param \Resource_manager\TokenBucket $var
     * @return $this
     */
    public function setIoWrite($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\TokenBucket::class);
        $this->io_write = $var;

        return $this;
    }

}

