<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace Resource_manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>resource_manager.PutResourceGroupRequest</code>
 */
class PutResourceGroupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.resource_manager.ResourceGroup group = 1;</code>
     */
    protected $group = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Resource_manager\ResourceGroup $group
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ResourceManager::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.resource_manager.ResourceGroup group = 1;</code>
     * @return \Resource_manager\ResourceGroup|null
     */
    public function getGroup()
    {
        return $this->group;
    }

    public function hasGroup()
    {
        return isset($this->group);
    }

    public function clearGroup()
    {
        unset($this->group);
    }

    /**
     * Generated from protobuf field <code>.resource_manager.ResourceGroup group = 1;</code>
     * @param \Resource_manager\ResourceGroup $var
     * @return $this
     */
    public function setGroup($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\ResourceGroup::class);
        $this->group = $var;

        return $this;
    }

}

