<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace Resource_manager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ResourceGroup the settings definitions.
 *
 * Generated from protobuf message <code>resource_manager.ResourceGroup</code>
 */
class ResourceGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.resource_manager.GroupMode mode = 2;</code>
     */
    protected $mode = 0;
    /**
     * Used in RU mode, group settings with WRU/RRU etc resource abstract unit.
     *
     * Generated from protobuf field <code>.resource_manager.GroupRequestUnitSettings r_u_settings = 3;</code>
     */
    protected $r_u_settings = null;
    /**
     * Used in Raw mode, group settings with CPU/IO etc resource unit.
     *
     * Generated from protobuf field <code>.resource_manager.GroupRawResourceSettings raw_resource_settings = 4;</code>
     */
    protected $raw_resource_settings = null;
    /**
     * The task scheduling priority
     *
     * Generated from protobuf field <code>uint32 priority = 5;</code>
     */
    protected $priority = 0;
    /**
     * Runaway queries settings
     *
     * Generated from protobuf field <code>.resource_manager.RunawaySettings runaway_settings = 6;</code>
     */
    protected $runaway_settings = null;
    /**
     * Background task control settings.
     *
     * Generated from protobuf field <code>.resource_manager.BackgroundSettings background_settings = 7;</code>
     */
    protected $background_settings = null;
    /**
     * RU consumption statistics.
     *
     * Generated from protobuf field <code>.resource_manager.Consumption RUStats = 8;</code>
     */
    protected $RUStats = null;
    /**
     * The keyspace ID that the resource group belongs to.
     * There're two cases for this field:
     *   - If the keyspace ID is not set, it means this may be a message from an older version.
     *     To maintain compatibility, we will treat it as a null keyspace ID, which is uint32.Max.
     *   - If the keyspace ID is set to a valid value, it will directly be used.
     *
     * Generated from protobuf field <code>.resource_manager.KeyspaceIDValue keyspace_id = 9;</code>
     */
    protected $keyspace_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $mode
     *     @type \Resource_manager\GroupRequestUnitSettings $r_u_settings
     *           Used in RU mode, group settings with WRU/RRU etc resource abstract unit.
     *     @type \Resource_manager\GroupRawResourceSettings $raw_resource_settings
     *           Used in Raw mode, group settings with CPU/IO etc resource unit.
     *     @type int $priority
     *           The task scheduling priority
     *     @type \Resource_manager\RunawaySettings $runaway_settings
     *           Runaway queries settings
     *     @type \Resource_manager\BackgroundSettings $background_settings
     *           Background task control settings.
     *     @type \Resource_manager\Consumption $RUStats
     *           RU consumption statistics.
     *     @type \Resource_manager\KeyspaceIDValue $keyspace_id
     *           The keyspace ID that the resource group belongs to.
     *           There're two cases for this field:
     *             - If the keyspace ID is not set, it means this may be a message from an older version.
     *               To maintain compatibility, we will treat it as a null keyspace ID, which is uint32.Max.
     *             - If the keyspace ID is set to a valid value, it will directly be used.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ResourceManager::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.resource_manager.GroupMode mode = 2;</code>
     * @return int
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>.resource_manager.GroupMode mode = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMode($var)
    {
        GPBUtil::checkEnum($var, \Resource_manager\GroupMode::class);
        $this->mode = $var;

        return $this;
    }

    /**
     * Used in RU mode, group settings with WRU/RRU etc resource abstract unit.
     *
     * Generated from protobuf field <code>.resource_manager.GroupRequestUnitSettings r_u_settings = 3;</code>
     * @return \Resource_manager\GroupRequestUnitSettings|null
     */
    public function getRUSettings()
    {
        return $this->r_u_settings;
    }

    public function hasRUSettings()
    {
        return isset($this->r_u_settings);
    }

    public function clearRUSettings()
    {
        unset($this->r_u_settings);
    }

    /**
     * Used in RU mode, group settings with WRU/RRU etc resource abstract unit.
     *
     * Generated from protobuf field <code>.resource_manager.GroupRequestUnitSettings r_u_settings = 3;</code>
     * @param \Resource_manager\GroupRequestUnitSettings $var
     * @return $this
     */
    public function setRUSettings($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\GroupRequestUnitSettings::class);
        $this->r_u_settings = $var;

        return $this;
    }

    /**
     * Used in Raw mode, group settings with CPU/IO etc resource unit.
     *
     * Generated from protobuf field <code>.resource_manager.GroupRawResourceSettings raw_resource_settings = 4;</code>
     * @return \Resource_manager\GroupRawResourceSettings|null
     */
    public function getRawResourceSettings()
    {
        return $this->raw_resource_settings;
    }

    public function hasRawResourceSettings()
    {
        return isset($this->raw_resource_settings);
    }

    public function clearRawResourceSettings()
    {
        unset($this->raw_resource_settings);
    }

    /**
     * Used in Raw mode, group settings with CPU/IO etc resource unit.
     *
     * Generated from protobuf field <code>.resource_manager.GroupRawResourceSettings raw_resource_settings = 4;</code>
     * @param \Resource_manager\GroupRawResourceSettings $var
     * @return $this
     */
    public function setRawResourceSettings($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\GroupRawResourceSettings::class);
        $this->raw_resource_settings = $var;

        return $this;
    }

    /**
     * The task scheduling priority
     *
     * Generated from protobuf field <code>uint32 priority = 5;</code>
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * The task scheduling priority
     *
     * Generated from protobuf field <code>uint32 priority = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkUint32($var);
        $this->priority = $var;

        return $this;
    }

    /**
     * Runaway queries settings
     *
     * Generated from protobuf field <code>.resource_manager.RunawaySettings runaway_settings = 6;</code>
     * @return \Resource_manager\RunawaySettings|null
     */
    public function getRunawaySettings()
    {
        return $this->runaway_settings;
    }

    public function hasRunawaySettings()
    {
        return isset($this->runaway_settings);
    }

    public function clearRunawaySettings()
    {
        unset($this->runaway_settings);
    }

    /**
     * Runaway queries settings
     *
     * Generated from protobuf field <code>.resource_manager.RunawaySettings runaway_settings = 6;</code>
     * @param \Resource_manager\RunawaySettings $var
     * @return $this
     */
    public function setRunawaySettings($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\RunawaySettings::class);
        $this->runaway_settings = $var;

        return $this;
    }

    /**
     * Background task control settings.
     *
     * Generated from protobuf field <code>.resource_manager.BackgroundSettings background_settings = 7;</code>
     * @return \Resource_manager\BackgroundSettings|null
     */
    public function getBackgroundSettings()
    {
        return $this->background_settings;
    }

    public function hasBackgroundSettings()
    {
        return isset($this->background_settings);
    }

    public function clearBackgroundSettings()
    {
        unset($this->background_settings);
    }

    /**
     * Background task control settings.
     *
     * Generated from protobuf field <code>.resource_manager.BackgroundSettings background_settings = 7;</code>
     * @param \Resource_manager\BackgroundSettings $var
     * @return $this
     */
    public function setBackgroundSettings($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\BackgroundSettings::class);
        $this->background_settings = $var;

        return $this;
    }

    /**
     * RU consumption statistics.
     *
     * Generated from protobuf field <code>.resource_manager.Consumption RUStats = 8;</code>
     * @return \Resource_manager\Consumption|null
     */
    public function getRUStats()
    {
        return $this->RUStats;
    }

    public function hasRUStats()
    {
        return isset($this->RUStats);
    }

    public function clearRUStats()
    {
        unset($this->RUStats);
    }

    /**
     * RU consumption statistics.
     *
     * Generated from protobuf field <code>.resource_manager.Consumption RUStats = 8;</code>
     * @param \Resource_manager\Consumption $var
     * @return $this
     */
    public function setRUStats($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\Consumption::class);
        $this->RUStats = $var;

        return $this;
    }

    /**
     * The keyspace ID that the resource group belongs to.
     * There're two cases for this field:
     *   - If the keyspace ID is not set, it means this may be a message from an older version.
     *     To maintain compatibility, we will treat it as a null keyspace ID, which is uint32.Max.
     *   - If the keyspace ID is set to a valid value, it will directly be used.
     *
     * Generated from protobuf field <code>.resource_manager.KeyspaceIDValue keyspace_id = 9;</code>
     * @return \Resource_manager\KeyspaceIDValue|null
     */
    public function getKeyspaceId()
    {
        return $this->keyspace_id;
    }

    public function hasKeyspaceId()
    {
        return isset($this->keyspace_id);
    }

    public function clearKeyspaceId()
    {
        unset($this->keyspace_id);
    }

    /**
     * The keyspace ID that the resource group belongs to.
     * There're two cases for this field:
     *   - If the keyspace ID is not set, it means this may be a message from an older version.
     *     To maintain compatibility, we will treat it as a null keyspace ID, which is uint32.Max.
     *   - If the keyspace ID is set to a valid value, it will directly be used.
     *
     * Generated from protobuf field <code>.resource_manager.KeyspaceIDValue keyspace_id = 9;</code>
     * @param \Resource_manager\KeyspaceIDValue $var
     * @return $this
     */
    public function setKeyspaceId($var)
    {
        GPBUtil::checkMessage($var, \Resource_manager\KeyspaceIDValue::class);
        $this->keyspace_id = $var;

        return $this;
    }

}

