<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_manager.proto

namespace Resource_manager;

use UnexpectedValueException;

/**
 * Protobuf type <code>resource_manager.RunawayAction</code>
 */
class RunawayAction
{
    /**
     * Generated from protobuf enum <code>NoneAction = 0;</code>
     */
    const NoneAction = 0;
    /**
     * do nothing
     *
     * Generated from protobuf enum <code>DryRun = 1;</code>
     */
    const DryRun = 1;
    /**
     * deprioritize the task
     *
     * Generated from protobuf enum <code>CoolDown = 2;</code>
     */
    const CoolDown = 2;
    /**
     * kill the task
     *
     * Generated from protobuf enum <code>Kill = 3;</code>
     */
    const Kill = 3;
    /**
     * switch the task to another group
     *
     * Generated from protobuf enum <code>SwitchGroup = 4;</code>
     */
    const SwitchGroup = 4;

    private static $valueToName = [
        self::NoneAction => 'NoneAction',
        self::DryRun => 'DryRun',
        self::CoolDown => 'CoolDown',
        self::Kill => 'Kill',
        self::SwitchGroup => 'SwitchGroup',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

