<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tikvpb.proto

namespace CrazyGoat\Proto\Tikvpb\BatchCommandsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>tikvpb.BatchCommandsResponse.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    protected $cmd;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\GetResponse $Get
     *     @type \CrazyGoat\Proto\Kvrpcpb\ScanResponse $Scan
     *     @type \CrazyGoat\Proto\Kvrpcpb\PrewriteResponse $Prewrite
     *     @type \CrazyGoat\Proto\Kvrpcpb\CommitResponse $Commit
     *     @type \CrazyGoat\Proto\Kvrpcpb\ImportResponse $Import
     *     @type \CrazyGoat\Proto\Kvrpcpb\CleanupResponse $Cleanup
     *     @type \CrazyGoat\Proto\Kvrpcpb\BatchGetResponse $BatchGet
     *     @type \CrazyGoat\Proto\Kvrpcpb\BatchRollbackResponse $BatchRollback
     *     @type \CrazyGoat\Proto\Kvrpcpb\ScanLockResponse $ScanLock
     *     @type \CrazyGoat\Proto\Kvrpcpb\ResolveLockResponse $ResolveLock
     *     @type \CrazyGoat\Proto\Kvrpcpb\GCResponse $GC
     *     @type \CrazyGoat\Proto\Kvrpcpb\DeleteRangeResponse $DeleteRange
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawGetResponse $RawGet
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawBatchGetResponse $RawBatchGet
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawPutResponse $RawPut
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawBatchPutResponse $RawBatchPut
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawDeleteResponse $RawDelete
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawBatchDeleteResponse $RawBatchDelete
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawScanResponse $RawScan
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawDeleteRangeResponse $RawDeleteRange
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawBatchScanResponse $RawBatchScan
     *     @type \CrazyGoat\Proto\Coprocessor\Response $Coprocessor
     *     @type \CrazyGoat\Proto\Kvrpcpb\PessimisticLockResponse $PessimisticLock
     *     @type \CrazyGoat\Proto\Kvrpcpb\PessimisticRollbackResponse $PessimisticRollback
     *     @type \CrazyGoat\Proto\Kvrpcpb\CheckTxnStatusResponse $CheckTxnStatus
     *     @type \CrazyGoat\Proto\Kvrpcpb\TxnHeartBeatResponse $TxnHeartBeat
     *     @type \CrazyGoat\Proto\Kvrpcpb\CheckSecondaryLocksResponse $CheckSecondaryLocks
     *     @type \CrazyGoat\Proto\Kvrpcpb\RawCoprocessorResponse $RawCoprocessor
     *     @type \CrazyGoat\Proto\Kvrpcpb\FlashbackToVersionResponse $FlashbackToVersion
     *     @type \CrazyGoat\Proto\Kvrpcpb\PrepareFlashbackToVersionResponse $PrepareFlashbackToVersion
     *     @type \CrazyGoat\Proto\Kvrpcpb\FlushResponse $Flush
     *     @type \CrazyGoat\Proto\Kvrpcpb\BufferBatchGetResponse $BufferBatchGet
     *     @type \CrazyGoat\Proto\Kvrpcpb\GetHealthFeedbackResponse $GetHealthFeedback
     *     @type \CrazyGoat\Proto\Kvrpcpb\BroadcastTxnStatusResponse $BroadcastTxnStatus
     *     @type \CrazyGoat\Proto\Tikvpb\BatchCommandsEmptyResponse $Empty
     *           For some test cases.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Tikvpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GetResponse Get = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\GetResponse|null
     */
    public function getGet()
    {
        return $this->readOneof(1);
    }

    public function hasGet()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GetResponse Get = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\GetResponse $var
     * @return $this
     */
    public function setGet($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\GetResponse::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanResponse Scan = 2;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ScanResponse|null
     */
    public function getScan()
    {
        return $this->readOneof(2);
    }

    public function hasScan()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanResponse Scan = 2;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ScanResponse $var
     * @return $this
     */
    public function setScan($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\ScanResponse::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PrewriteResponse Prewrite = 3;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PrewriteResponse|null
     */
    public function getPrewrite()
    {
        return $this->readOneof(3);
    }

    public function hasPrewrite()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PrewriteResponse Prewrite = 3;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PrewriteResponse $var
     * @return $this
     */
    public function setPrewrite($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\PrewriteResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CommitResponse Commit = 4;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CommitResponse|null
     */
    public function getCommit()
    {
        return $this->readOneof(4);
    }

    public function hasCommit()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CommitResponse Commit = 4;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CommitResponse $var
     * @return $this
     */
    public function setCommit($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\CommitResponse::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ImportResponse Import = 5;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ImportResponse|null
     */
    public function getImport()
    {
        return $this->readOneof(5);
    }

    public function hasImport()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ImportResponse Import = 5;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ImportResponse $var
     * @return $this
     */
    public function setImport($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\ImportResponse::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CleanupResponse Cleanup = 6;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CleanupResponse|null
     */
    public function getCleanup()
    {
        return $this->readOneof(6);
    }

    public function hasCleanup()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CleanupResponse Cleanup = 6;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CleanupResponse $var
     * @return $this
     */
    public function setCleanup($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\CleanupResponse::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BatchGetResponse BatchGet = 7;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\BatchGetResponse|null
     */
    public function getBatchGet()
    {
        return $this->readOneof(7);
    }

    public function hasBatchGet()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BatchGetResponse BatchGet = 7;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\BatchGetResponse $var
     * @return $this
     */
    public function setBatchGet($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\BatchGetResponse::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BatchRollbackResponse BatchRollback = 8;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\BatchRollbackResponse|null
     */
    public function getBatchRollback()
    {
        return $this->readOneof(8);
    }

    public function hasBatchRollback()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BatchRollbackResponse BatchRollback = 8;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\BatchRollbackResponse $var
     * @return $this
     */
    public function setBatchRollback($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\BatchRollbackResponse::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanLockResponse ScanLock = 9;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ScanLockResponse|null
     */
    public function getScanLock()
    {
        return $this->readOneof(9);
    }

    public function hasScanLock()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanLockResponse ScanLock = 9;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ScanLockResponse $var
     * @return $this
     */
    public function setScanLock($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\ScanLockResponse::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ResolveLockResponse ResolveLock = 10;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ResolveLockResponse|null
     */
    public function getResolveLock()
    {
        return $this->readOneof(10);
    }

    public function hasResolveLock()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ResolveLockResponse ResolveLock = 10;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ResolveLockResponse $var
     * @return $this
     */
    public function setResolveLock($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\ResolveLockResponse::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GCResponse GC = 11;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\GCResponse|null
     */
    public function getGC()
    {
        return $this->readOneof(11);
    }

    public function hasGC()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GCResponse GC = 11;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\GCResponse $var
     * @return $this
     */
    public function setGC($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\GCResponse::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.DeleteRangeResponse DeleteRange = 12;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\DeleteRangeResponse|null
     */
    public function getDeleteRange()
    {
        return $this->readOneof(12);
    }

    public function hasDeleteRange()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.DeleteRangeResponse DeleteRange = 12;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\DeleteRangeResponse $var
     * @return $this
     */
    public function setDeleteRange($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\DeleteRangeResponse::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawGetResponse RawGet = 13;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawGetResponse|null
     */
    public function getRawGet()
    {
        return $this->readOneof(13);
    }

    public function hasRawGet()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawGetResponse RawGet = 13;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawGetResponse $var
     * @return $this
     */
    public function setRawGet($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawGetResponse::class);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchGetResponse RawBatchGet = 14;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawBatchGetResponse|null
     */
    public function getRawBatchGet()
    {
        return $this->readOneof(14);
    }

    public function hasRawBatchGet()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchGetResponse RawBatchGet = 14;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawBatchGetResponse $var
     * @return $this
     */
    public function setRawBatchGet($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawBatchGetResponse::class);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawPutResponse RawPut = 15;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawPutResponse|null
     */
    public function getRawPut()
    {
        return $this->readOneof(15);
    }

    public function hasRawPut()
    {
        return $this->hasOneof(15);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawPutResponse RawPut = 15;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawPutResponse $var
     * @return $this
     */
    public function setRawPut($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawPutResponse::class);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchPutResponse RawBatchPut = 16;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawBatchPutResponse|null
     */
    public function getRawBatchPut()
    {
        return $this->readOneof(16);
    }

    public function hasRawBatchPut()
    {
        return $this->hasOneof(16);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchPutResponse RawBatchPut = 16;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawBatchPutResponse $var
     * @return $this
     */
    public function setRawBatchPut($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawBatchPutResponse::class);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawDeleteResponse RawDelete = 17;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawDeleteResponse|null
     */
    public function getRawDelete()
    {
        return $this->readOneof(17);
    }

    public function hasRawDelete()
    {
        return $this->hasOneof(17);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawDeleteResponse RawDelete = 17;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawDeleteResponse $var
     * @return $this
     */
    public function setRawDelete($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawDeleteResponse::class);
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchDeleteResponse RawBatchDelete = 18;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawBatchDeleteResponse|null
     */
    public function getRawBatchDelete()
    {
        return $this->readOneof(18);
    }

    public function hasRawBatchDelete()
    {
        return $this->hasOneof(18);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchDeleteResponse RawBatchDelete = 18;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawBatchDeleteResponse $var
     * @return $this
     */
    public function setRawBatchDelete($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawBatchDeleteResponse::class);
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawScanResponse RawScan = 19;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawScanResponse|null
     */
    public function getRawScan()
    {
        return $this->readOneof(19);
    }

    public function hasRawScan()
    {
        return $this->hasOneof(19);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawScanResponse RawScan = 19;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawScanResponse $var
     * @return $this
     */
    public function setRawScan($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawScanResponse::class);
        $this->writeOneof(19, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawDeleteRangeResponse RawDeleteRange = 20;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawDeleteRangeResponse|null
     */
    public function getRawDeleteRange()
    {
        return $this->readOneof(20);
    }

    public function hasRawDeleteRange()
    {
        return $this->hasOneof(20);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawDeleteRangeResponse RawDeleteRange = 20;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawDeleteRangeResponse $var
     * @return $this
     */
    public function setRawDeleteRange($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawDeleteRangeResponse::class);
        $this->writeOneof(20, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchScanResponse RawBatchScan = 21;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawBatchScanResponse|null
     */
    public function getRawBatchScan()
    {
        return $this->readOneof(21);
    }

    public function hasRawBatchScan()
    {
        return $this->hasOneof(21);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawBatchScanResponse RawBatchScan = 21;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawBatchScanResponse $var
     * @return $this
     */
    public function setRawBatchScan($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawBatchScanResponse::class);
        $this->writeOneof(21, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.coprocessor.Response Coprocessor = 22;</code>
     * @return \CrazyGoat\Proto\Coprocessor\Response|null
     */
    public function getCoprocessor()
    {
        return $this->readOneof(22);
    }

    public function hasCoprocessor()
    {
        return $this->hasOneof(22);
    }

    /**
     * Generated from protobuf field <code>.coprocessor.Response Coprocessor = 22;</code>
     * @param \CrazyGoat\Proto\Coprocessor\Response $var
     * @return $this
     */
    public function setCoprocessor($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Coprocessor\Response::class);
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PessimisticLockResponse PessimisticLock = 23;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PessimisticLockResponse|null
     */
    public function getPessimisticLock()
    {
        return $this->readOneof(23);
    }

    public function hasPessimisticLock()
    {
        return $this->hasOneof(23);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PessimisticLockResponse PessimisticLock = 23;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PessimisticLockResponse $var
     * @return $this
     */
    public function setPessimisticLock($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\PessimisticLockResponse::class);
        $this->writeOneof(23, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PessimisticRollbackResponse PessimisticRollback = 24;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PessimisticRollbackResponse|null
     */
    public function getPessimisticRollback()
    {
        return $this->readOneof(24);
    }

    public function hasPessimisticRollback()
    {
        return $this->hasOneof(24);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PessimisticRollbackResponse PessimisticRollback = 24;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PessimisticRollbackResponse $var
     * @return $this
     */
    public function setPessimisticRollback($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\PessimisticRollbackResponse::class);
        $this->writeOneof(24, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CheckTxnStatusResponse CheckTxnStatus = 25;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CheckTxnStatusResponse|null
     */
    public function getCheckTxnStatus()
    {
        return $this->readOneof(25);
    }

    public function hasCheckTxnStatus()
    {
        return $this->hasOneof(25);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CheckTxnStatusResponse CheckTxnStatus = 25;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CheckTxnStatusResponse $var
     * @return $this
     */
    public function setCheckTxnStatus($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\CheckTxnStatusResponse::class);
        $this->writeOneof(25, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.TxnHeartBeatResponse TxnHeartBeat = 26;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\TxnHeartBeatResponse|null
     */
    public function getTxnHeartBeat()
    {
        return $this->readOneof(26);
    }

    public function hasTxnHeartBeat()
    {
        return $this->hasOneof(26);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.TxnHeartBeatResponse TxnHeartBeat = 26;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\TxnHeartBeatResponse $var
     * @return $this
     */
    public function setTxnHeartBeat($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\TxnHeartBeatResponse::class);
        $this->writeOneof(26, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CheckSecondaryLocksResponse CheckSecondaryLocks = 33;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CheckSecondaryLocksResponse|null
     */
    public function getCheckSecondaryLocks()
    {
        return $this->readOneof(33);
    }

    public function hasCheckSecondaryLocks()
    {
        return $this->hasOneof(33);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.CheckSecondaryLocksResponse CheckSecondaryLocks = 33;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CheckSecondaryLocksResponse $var
     * @return $this
     */
    public function setCheckSecondaryLocks($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\CheckSecondaryLocksResponse::class);
        $this->writeOneof(33, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawCoprocessorResponse RawCoprocessor = 34;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\RawCoprocessorResponse|null
     */
    public function getRawCoprocessor()
    {
        return $this->readOneof(34);
    }

    public function hasRawCoprocessor()
    {
        return $this->hasOneof(34);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.RawCoprocessorResponse RawCoprocessor = 34;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\RawCoprocessorResponse $var
     * @return $this
     */
    public function setRawCoprocessor($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\RawCoprocessorResponse::class);
        $this->writeOneof(34, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.FlashbackToVersionResponse FlashbackToVersion = 35;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\FlashbackToVersionResponse|null
     */
    public function getFlashbackToVersion()
    {
        return $this->readOneof(35);
    }

    public function hasFlashbackToVersion()
    {
        return $this->hasOneof(35);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.FlashbackToVersionResponse FlashbackToVersion = 35;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\FlashbackToVersionResponse $var
     * @return $this
     */
    public function setFlashbackToVersion($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\FlashbackToVersionResponse::class);
        $this->writeOneof(35, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PrepareFlashbackToVersionResponse PrepareFlashbackToVersion = 36;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PrepareFlashbackToVersionResponse|null
     */
    public function getPrepareFlashbackToVersion()
    {
        return $this->readOneof(36);
    }

    public function hasPrepareFlashbackToVersion()
    {
        return $this->hasOneof(36);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.PrepareFlashbackToVersionResponse PrepareFlashbackToVersion = 36;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PrepareFlashbackToVersionResponse $var
     * @return $this
     */
    public function setPrepareFlashbackToVersion($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\PrepareFlashbackToVersionResponse::class);
        $this->writeOneof(36, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.FlushResponse Flush = 37;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\FlushResponse|null
     */
    public function getFlush()
    {
        return $this->readOneof(37);
    }

    public function hasFlush()
    {
        return $this->hasOneof(37);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.FlushResponse Flush = 37;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\FlushResponse $var
     * @return $this
     */
    public function setFlush($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\FlushResponse::class);
        $this->writeOneof(37, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BufferBatchGetResponse BufferBatchGet = 38;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\BufferBatchGetResponse|null
     */
    public function getBufferBatchGet()
    {
        return $this->readOneof(38);
    }

    public function hasBufferBatchGet()
    {
        return $this->hasOneof(38);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BufferBatchGetResponse BufferBatchGet = 38;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\BufferBatchGetResponse $var
     * @return $this
     */
    public function setBufferBatchGet($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\BufferBatchGetResponse::class);
        $this->writeOneof(38, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GetHealthFeedbackResponse GetHealthFeedback = 39;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\GetHealthFeedbackResponse|null
     */
    public function getGetHealthFeedback()
    {
        return $this->readOneof(39);
    }

    public function hasGetHealthFeedback()
    {
        return $this->hasOneof(39);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.GetHealthFeedbackResponse GetHealthFeedback = 39;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\GetHealthFeedbackResponse $var
     * @return $this
     */
    public function setGetHealthFeedback($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\GetHealthFeedbackResponse::class);
        $this->writeOneof(39, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BroadcastTxnStatusResponse BroadcastTxnStatus = 40;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\BroadcastTxnStatusResponse|null
     */
    public function getBroadcastTxnStatus()
    {
        return $this->readOneof(40);
    }

    public function hasBroadcastTxnStatus()
    {
        return $this->hasOneof(40);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.BroadcastTxnStatusResponse BroadcastTxnStatus = 40;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\BroadcastTxnStatusResponse $var
     * @return $this
     */
    public function setBroadcastTxnStatus($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\BroadcastTxnStatusResponse::class);
        $this->writeOneof(40, $var);

        return $this;
    }

    /**
     * For some test cases.
     *
     * Generated from protobuf field <code>.tikvpb.BatchCommandsEmptyResponse Empty = 255;</code>
     * @return \CrazyGoat\Proto\Tikvpb\BatchCommandsEmptyResponse|null
     */
    public function getEmpty()
    {
        return $this->readOneof(255);
    }

    public function hasEmpty()
    {
        return $this->hasOneof(255);
    }

    /**
     * For some test cases.
     *
     * Generated from protobuf field <code>.tikvpb.BatchCommandsEmptyResponse Empty = 255;</code>
     * @param \CrazyGoat\Proto\Tikvpb\BatchCommandsEmptyResponse $var
     * @return $this
     */
    public function setEmpty($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Tikvpb\BatchCommandsEmptyResponse::class);
        $this->writeOneof(255, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getCmd()
    {
        return $this->whichOneof("cmd");
    }

}

