<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use UnexpectedValueException;

/**
 * The API version the server and the client is using.
 * See more details in https://github.com/tikv/rfcs/blob/master/text/0069-api-v2.md.
 *
 * Protobuf type <code>kvrpcpb.APIVersion</code>
 */
class APIVersion
{
    /**
     * `V1` is mainly for TiDB & TxnKV, and is not safe to use RawKV along with the others.
     * V1 server only accepts V1 requests. V1 raw requests with TTL will be rejected.
     *
     * Generated from protobuf enum <code>V1 = 0;</code>
     */
    const V1 = 0;
    /**
     * `V1TTL` is only available to RawKV, and 8 bytes representing the unix timestamp in
     * seconds for expiring time will be append to the value of all RawKV entries. For example:
     * ------------------------------------------------------------
     * | User value     | Expire Ts                               |
     * ------------------------------------------------------------
     * | 0x12 0x34 0x56 | 0x00 0x00 0x00 0x00 0x00 0x00 0xff 0xff |
     * ------------------------------------------------------------
     * V1TTL server only accepts V1 raw requests.
     * V1 client should not use `V1TTL` in request. V1 client should always send `V1`.
     *
     * Generated from protobuf enum <code>V1TTL = 1;</code>
     */
    const V1TTL = 1;
    /**
     * `V2` use new encoding for RawKV & TxnKV to support more features.
     * Key Encoding:
     *  TiDB: start with `m` or `t`, the same as `V1`.
     *  TxnKV: prefix with `x`, encoded as `MCE( x{keyspace id} + {user key} ) + timestamp`.
     *  RawKV: prefix with `r`, encoded as `MCE( r{keyspace id} + {user key} ) + timestamp`.
     *  Where the `{keyspace id}` is fixed-length of 3 bytes in network byte order.
     *  Besides, RawKV entires must be in `default` CF.
     * Value Encoding:
     *  TiDB & TxnKV: the same as `V1`.
     *  RawKV: `{user value} + {optional fields} + {meta flag}`. The last byte in the
     *  raw value must be meta flags. For example:
     *  --------------------------------------
     *  | User value     | Meta flags        |
     *  --------------------------------------
     *  | 0x12 0x34 0x56 | 0x00 (0b00000000) |
     *  --------------------------------------
     *  Bit 0 of meta flags is for TTL. If set, the value contains 8 bytes expiring time as
     *  unix timestamp in seconds at the very left to the meta flags.
     *  --------------------------------------------------------------------------------
     *  | User value     | Expiring time                           | Meta flags        |
     *  --------------------------------------------------------------------------------
     *  | 0x12 0x34 0x56 | 0x00 0x00 0x00 0x00 0x00 0x00 0xff 0xff | 0x01 (0b00000001) |
     *  --------------------------------------------------------------------------------
     *  Bit 1 is for deletion. If set, the entry is logical deleted.
     *  ---------------------
     *  | Meta flags        |
     *  ---------------------
     *  | 0x02 (0b00000010) |
     *  ---------------------
     * V2 server accpets V2 requests and V1 transactional requests that statrts with TiDB key
     * prefix (`m` and `t`).
     *
     * Generated from protobuf enum <code>V2 = 2;</code>
     */
    const V2 = 2;

    private static $valueToName = [
        self::V1 => 'V1',
        self::V1TTL => 'V1TTL',
        self::V2 => 'V2',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

