<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use UnexpectedValueException;

/**
 * Protobuf type <code>kvrpcpb.AssertionLevel</code>
 */
class AssertionLevel
{
    /**
     * No assertion.
     *
     * Generated from protobuf enum <code>Off = 0;</code>
     */
    const Off = 0;
    /**
     * Assertion is enabled, but not enforced when it might affect performance.
     *
     * Generated from protobuf enum <code>Fast = 1;</code>
     */
    const Fast = 1;
    /**
     * Assertion is enabled and enforced.
     *
     * Generated from protobuf enum <code>Strict = 2;</code>
     */
    const Strict = 2;

    private static $valueToName = [
        self::Off => 'Off',
        self::Fast => 'Fast',
        self::Strict => 'Strict',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

