<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.CommitResponse</code>
 */
class CommitResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     */
    protected $region_error = null;
    /**
     * Generated from protobuf field <code>.kvrpcpb.KeyError error = 2;</code>
     */
    protected $error = null;
    /**
     * If the commit ts is derived from min_commit_ts, this field should be set.
     *
     * Generated from protobuf field <code>uint64 commit_version = 3;</code>
     */
    protected $commit_version = 0;
    /**
     * Execution details about the request processing.
     *
     * Generated from protobuf field <code>.kvrpcpb.ExecDetailsV2 exec_details_v2 = 4;</code>
     */
    protected $exec_details_v2 = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Errorpb\Error $region_error
     *     @type \CrazyGoat\Proto\Kvrpcpb\KeyError $error
     *     @type int|string $commit_version
     *           If the commit ts is derived from min_commit_ts, this field should be set.
     *     @type \CrazyGoat\Proto\Kvrpcpb\ExecDetailsV2 $exec_details_v2
     *           Execution details about the request processing.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @return \CrazyGoat\Proto\Errorpb\Error|null
     */
    public function getRegionError()
    {
        return $this->region_error;
    }

    public function hasRegionError()
    {
        return isset($this->region_error);
    }

    public function clearRegionError()
    {
        unset($this->region_error);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @param \CrazyGoat\Proto\Errorpb\Error $var
     * @return $this
     */
    public function setRegionError($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Errorpb\Error::class);
        $this->region_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.KeyError error = 2;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\KeyError|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.KeyError error = 2;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\KeyError $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\KeyError::class);
        $this->error = $var;

        return $this;
    }

    /**
     * If the commit ts is derived from min_commit_ts, this field should be set.
     *
     * Generated from protobuf field <code>uint64 commit_version = 3;</code>
     * @return int|string
     */
    public function getCommitVersion()
    {
        return $this->commit_version;
    }

    /**
     * If the commit ts is derived from min_commit_ts, this field should be set.
     *
     * Generated from protobuf field <code>uint64 commit_version = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommitVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->commit_version = $var;

        return $this;
    }

    /**
     * Execution details about the request processing.
     *
     * Generated from protobuf field <code>.kvrpcpb.ExecDetailsV2 exec_details_v2 = 4;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\ExecDetailsV2|null
     */
    public function getExecDetailsV2()
    {
        return $this->exec_details_v2;
    }

    public function hasExecDetailsV2()
    {
        return isset($this->exec_details_v2);
    }

    public function clearExecDetailsV2()
    {
        unset($this->exec_details_v2);
    }

    /**
     * Execution details about the request processing.
     *
     * Generated from protobuf field <code>.kvrpcpb.ExecDetailsV2 exec_details_v2 = 4;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\ExecDetailsV2 $var
     * @return $this
     */
    public function setExecDetailsV2($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\ExecDetailsV2::class);
        $this->exec_details_v2 = $var;

        return $this;
    }

}

