<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.CommitTsExpired</code>
 */
class CommitTsExpired extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 start_ts = 1;</code>
     */
    protected $start_ts = 0;
    /**
     * Generated from protobuf field <code>uint64 attempted_commit_ts = 2;</code>
     */
    protected $attempted_commit_ts = 0;
    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>uint64 min_commit_ts = 4;</code>
     */
    protected $min_commit_ts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $start_ts
     *     @type int|string $attempted_commit_ts
     *     @type string $key
     *     @type int|string $min_commit_ts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 start_ts = 1;</code>
     * @return int|string
     */
    public function getStartTs()
    {
        return $this->start_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 start_ts = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 attempted_commit_ts = 2;</code>
     * @return int|string
     */
    public function getAttemptedCommitTs()
    {
        return $this->attempted_commit_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 attempted_commit_ts = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAttemptedCommitTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->attempted_commit_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 min_commit_ts = 4;</code>
     * @return int|string
     */
    public function getMinCommitTs()
    {
        return $this->min_commit_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 min_commit_ts = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinCommitTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->min_commit_ts = $var;

        return $this;
    }

}

