<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.ExecutorInputs</code>
 */
class ExecutorInputs extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_index_scan = 1;</code>
     */
    protected $tikv_coprocessor_executor_work_total_batch_index_scan = 0;
    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_table_scan = 2;</code>
     */
    protected $tikv_coprocessor_executor_work_total_batch_table_scan = 0;
    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_selection = 3;</code>
     */
    protected $tikv_coprocessor_executor_work_total_batch_selection = 0;
    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_top_n = 4;</code>
     */
    protected $tikv_coprocessor_executor_work_total_batch_top_n = 0;
    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_limit = 5;</code>
     */
    protected $tikv_coprocessor_executor_work_total_batch_limit = 0;
    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_simple_aggr = 6;</code>
     */
    protected $tikv_coprocessor_executor_work_total_batch_simple_aggr = 0;
    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_fast_hash_aggr = 7;</code>
     */
    protected $tikv_coprocessor_executor_work_total_batch_fast_hash_aggr = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $tikv_coprocessor_executor_work_total_batch_index_scan
     *     @type int|string $tikv_coprocessor_executor_work_total_batch_table_scan
     *     @type int|string $tikv_coprocessor_executor_work_total_batch_selection
     *     @type int|string $tikv_coprocessor_executor_work_total_batch_top_n
     *     @type int|string $tikv_coprocessor_executor_work_total_batch_limit
     *     @type int|string $tikv_coprocessor_executor_work_total_batch_simple_aggr
     *     @type int|string $tikv_coprocessor_executor_work_total_batch_fast_hash_aggr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_index_scan = 1;</code>
     * @return int|string
     */
    public function getTikvCoprocessorExecutorWorkTotalBatchIndexScan()
    {
        return $this->tikv_coprocessor_executor_work_total_batch_index_scan;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_index_scan = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTikvCoprocessorExecutorWorkTotalBatchIndexScan($var)
    {
        GPBUtil::checkUint64($var);
        $this->tikv_coprocessor_executor_work_total_batch_index_scan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_table_scan = 2;</code>
     * @return int|string
     */
    public function getTikvCoprocessorExecutorWorkTotalBatchTableScan()
    {
        return $this->tikv_coprocessor_executor_work_total_batch_table_scan;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_table_scan = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTikvCoprocessorExecutorWorkTotalBatchTableScan($var)
    {
        GPBUtil::checkUint64($var);
        $this->tikv_coprocessor_executor_work_total_batch_table_scan = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_selection = 3;</code>
     * @return int|string
     */
    public function getTikvCoprocessorExecutorWorkTotalBatchSelection()
    {
        return $this->tikv_coprocessor_executor_work_total_batch_selection;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_selection = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTikvCoprocessorExecutorWorkTotalBatchSelection($var)
    {
        GPBUtil::checkUint64($var);
        $this->tikv_coprocessor_executor_work_total_batch_selection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_top_n = 4;</code>
     * @return int|string
     */
    public function getTikvCoprocessorExecutorWorkTotalBatchTopN()
    {
        return $this->tikv_coprocessor_executor_work_total_batch_top_n;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_top_n = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTikvCoprocessorExecutorWorkTotalBatchTopN($var)
    {
        GPBUtil::checkUint64($var);
        $this->tikv_coprocessor_executor_work_total_batch_top_n = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_limit = 5;</code>
     * @return int|string
     */
    public function getTikvCoprocessorExecutorWorkTotalBatchLimit()
    {
        return $this->tikv_coprocessor_executor_work_total_batch_limit;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_limit = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTikvCoprocessorExecutorWorkTotalBatchLimit($var)
    {
        GPBUtil::checkUint64($var);
        $this->tikv_coprocessor_executor_work_total_batch_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_simple_aggr = 6;</code>
     * @return int|string
     */
    public function getTikvCoprocessorExecutorWorkTotalBatchSimpleAggr()
    {
        return $this->tikv_coprocessor_executor_work_total_batch_simple_aggr;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_simple_aggr = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTikvCoprocessorExecutorWorkTotalBatchSimpleAggr($var)
    {
        GPBUtil::checkUint64($var);
        $this->tikv_coprocessor_executor_work_total_batch_simple_aggr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_fast_hash_aggr = 7;</code>
     * @return int|string
     */
    public function getTikvCoprocessorExecutorWorkTotalBatchFastHashAggr()
    {
        return $this->tikv_coprocessor_executor_work_total_batch_fast_hash_aggr;
    }

    /**
     * Generated from protobuf field <code>uint64 tikv_coprocessor_executor_work_total_batch_fast_hash_aggr = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTikvCoprocessorExecutorWorkTotalBatchFastHashAggr($var)
    {
        GPBUtil::checkUint64($var);
        $this->tikv_coprocessor_executor_work_total_batch_fast_hash_aggr = $var;

        return $this;
    }

}

