<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Not yet implemented.
 *
 * Generated from protobuf message <code>kvrpcpb.ImportRequest</code>
 */
class ImportRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.Mutation mutations = 1;</code>
     */
    private $mutations;
    /**
     * Generated from protobuf field <code>uint64 commit_version = 2;</code>
     */
    protected $commit_version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\Mutation[] $mutations
     *     @type int|string $commit_version
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.Mutation mutations = 1;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Kvrpcpb\Mutation>
     */
    public function getMutations()
    {
        return $this->mutations;
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.Mutation mutations = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Mutation[] $var
     * @return $this
     */
    public function setMutations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Kvrpcpb\Mutation::class);
        $this->mutations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 commit_version = 2;</code>
     * @return int|string
     */
    public function getCommitVersion()
    {
        return $this->commit_version;
    }

    /**
     * Generated from protobuf field <code>uint64 commit_version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommitVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->commit_version = $var;

        return $this;
    }

}

