<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use UnexpectedValueException;

/**
 * Protobuf type <code>kvrpcpb.IsolationLevel</code>
 */
class IsolationLevel
{
    /**
     * SI = snapshot isolation
     *
     * Generated from protobuf enum <code>SI = 0;</code>
     */
    const SI = 0;
    /**
     * RC = read committed
     *
     * Generated from protobuf enum <code>RC = 1;</code>
     */
    const RC = 1;
    /**
     * RC read and it's needed to check if there exists more recent versions.
     *
     * Generated from protobuf enum <code>RCCheckTS = 2;</code>
     */
    const RCCheckTS = 2;

    private static $valueToName = [
        self::SI => 'SI',
        self::RC => 'RC',
        self::RCCheckTS => 'RCCheckTS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

