<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.KeyError</code>
 */
class KeyError extends \Google\Protobuf\Internal\Message
{
    /**
     * Client should backoff or cleanup the lock then retry.
     *
     * Generated from protobuf field <code>.kvrpcpb.LockInfo locked = 1;</code>
     */
    protected $locked = null;
    /**
     * Client may restart the txn. e.g write conflict.
     *
     * Generated from protobuf field <code>string retryable = 2;</code>
     */
    protected $retryable = '';
    /**
     * Client should abort the txn.
     *
     * Generated from protobuf field <code>string abort = 3;</code>
     */
    protected $abort = '';
    /**
     * Write conflict is moved from retryable to here.
     *
     * Generated from protobuf field <code>.kvrpcpb.WriteConflict conflict = 4;</code>
     */
    protected $conflict = null;
    /**
     * Key already exists
     *
     * Generated from protobuf field <code>.kvrpcpb.AlreadyExist already_exist = 5;</code>
     */
    protected $already_exist = null;
    /**
     * Deadlock is used in pessimistic transaction for single statement rollback.
     *
     * Generated from protobuf field <code>.kvrpcpb.Deadlock deadlock = 6;</code>
     */
    protected $deadlock = null;
    /**
     * Commit ts is earlier than min commit ts of a transaction.
     *
     * Generated from protobuf field <code>.kvrpcpb.CommitTsExpired commit_ts_expired = 7;</code>
     */
    protected $commit_ts_expired = null;
    /**
     * Txn not found when checking txn status.
     *
     * Generated from protobuf field <code>.kvrpcpb.TxnNotFound txn_not_found = 8;</code>
     */
    protected $txn_not_found = null;
    /**
     * Calculated commit TS exceeds the limit given by the user.
     *
     * Generated from protobuf field <code>.kvrpcpb.CommitTsTooLarge commit_ts_too_large = 9;</code>
     */
    protected $commit_ts_too_large = null;
    /**
     * Assertion of a `Mutation` is evaluated as a failure.
     *
     * Generated from protobuf field <code>.kvrpcpb.AssertionFailed assertion_failed = 10;</code>
     */
    protected $assertion_failed = null;
    /**
     * CheckTxnStatus is sent to a lock that's not the primary.
     *
     * Generated from protobuf field <code>.kvrpcpb.PrimaryMismatch primary_mismatch = 11;</code>
     */
    protected $primary_mismatch = null;
    /**
     * TxnLockNotFound indicates the txn lock is not found.
     *
     * Generated from protobuf field <code>.kvrpcpb.TxnLockNotFound txn_lock_not_found = 12;</code>
     */
    protected $txn_lock_not_found = null;
    /**
     * Extra information for error debugging
     *
     * Generated from protobuf field <code>.kvrpcpb.DebugInfo debug_info = 100;</code>
     */
    protected $debug_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\LockInfo $locked
     *           Client should backoff or cleanup the lock then retry.
     *     @type string $retryable
     *           Client may restart the txn. e.g write conflict.
     *     @type string $abort
     *           Client should abort the txn.
     *     @type \CrazyGoat\Proto\Kvrpcpb\WriteConflict $conflict
     *           Write conflict is moved from retryable to here.
     *     @type \CrazyGoat\Proto\Kvrpcpb\AlreadyExist $already_exist
     *           Key already exists
     *     @type \CrazyGoat\Proto\Kvrpcpb\Deadlock $deadlock
     *           Deadlock is used in pessimistic transaction for single statement rollback.
     *     @type \CrazyGoat\Proto\Kvrpcpb\CommitTsExpired $commit_ts_expired
     *           Commit ts is earlier than min commit ts of a transaction.
     *     @type \CrazyGoat\Proto\Kvrpcpb\TxnNotFound $txn_not_found
     *           Txn not found when checking txn status.
     *     @type \CrazyGoat\Proto\Kvrpcpb\CommitTsTooLarge $commit_ts_too_large
     *           Calculated commit TS exceeds the limit given by the user.
     *     @type \CrazyGoat\Proto\Kvrpcpb\AssertionFailed $assertion_failed
     *           Assertion of a `Mutation` is evaluated as a failure.
     *     @type \CrazyGoat\Proto\Kvrpcpb\PrimaryMismatch $primary_mismatch
     *           CheckTxnStatus is sent to a lock that's not the primary.
     *     @type \CrazyGoat\Proto\Kvrpcpb\TxnLockNotFound $txn_lock_not_found
     *           TxnLockNotFound indicates the txn lock is not found.
     *     @type \CrazyGoat\Proto\Kvrpcpb\DebugInfo $debug_info
     *           Extra information for error debugging
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Client should backoff or cleanup the lock then retry.
     *
     * Generated from protobuf field <code>.kvrpcpb.LockInfo locked = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\LockInfo|null
     */
    public function getLocked()
    {
        return $this->locked;
    }

    public function hasLocked()
    {
        return isset($this->locked);
    }

    public function clearLocked()
    {
        unset($this->locked);
    }

    /**
     * Client should backoff or cleanup the lock then retry.
     *
     * Generated from protobuf field <code>.kvrpcpb.LockInfo locked = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\LockInfo $var
     * @return $this
     */
    public function setLocked($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\LockInfo::class);
        $this->locked = $var;

        return $this;
    }

    /**
     * Client may restart the txn. e.g write conflict.
     *
     * Generated from protobuf field <code>string retryable = 2;</code>
     * @return string
     */
    public function getRetryable()
    {
        return $this->retryable;
    }

    /**
     * Client may restart the txn. e.g write conflict.
     *
     * Generated from protobuf field <code>string retryable = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRetryable($var)
    {
        GPBUtil::checkString($var, True);
        $this->retryable = $var;

        return $this;
    }

    /**
     * Client should abort the txn.
     *
     * Generated from protobuf field <code>string abort = 3;</code>
     * @return string
     */
    public function getAbort()
    {
        return $this->abort;
    }

    /**
     * Client should abort the txn.
     *
     * Generated from protobuf field <code>string abort = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAbort($var)
    {
        GPBUtil::checkString($var, True);
        $this->abort = $var;

        return $this;
    }

    /**
     * Write conflict is moved from retryable to here.
     *
     * Generated from protobuf field <code>.kvrpcpb.WriteConflict conflict = 4;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\WriteConflict|null
     */
    public function getConflict()
    {
        return $this->conflict;
    }

    public function hasConflict()
    {
        return isset($this->conflict);
    }

    public function clearConflict()
    {
        unset($this->conflict);
    }

    /**
     * Write conflict is moved from retryable to here.
     *
     * Generated from protobuf field <code>.kvrpcpb.WriteConflict conflict = 4;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\WriteConflict $var
     * @return $this
     */
    public function setConflict($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\WriteConflict::class);
        $this->conflict = $var;

        return $this;
    }

    /**
     * Key already exists
     *
     * Generated from protobuf field <code>.kvrpcpb.AlreadyExist already_exist = 5;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\AlreadyExist|null
     */
    public function getAlreadyExist()
    {
        return $this->already_exist;
    }

    public function hasAlreadyExist()
    {
        return isset($this->already_exist);
    }

    public function clearAlreadyExist()
    {
        unset($this->already_exist);
    }

    /**
     * Key already exists
     *
     * Generated from protobuf field <code>.kvrpcpb.AlreadyExist already_exist = 5;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\AlreadyExist $var
     * @return $this
     */
    public function setAlreadyExist($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\AlreadyExist::class);
        $this->already_exist = $var;

        return $this;
    }

    /**
     * Deadlock is used in pessimistic transaction for single statement rollback.
     *
     * Generated from protobuf field <code>.kvrpcpb.Deadlock deadlock = 6;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Deadlock|null
     */
    public function getDeadlock()
    {
        return $this->deadlock;
    }

    public function hasDeadlock()
    {
        return isset($this->deadlock);
    }

    public function clearDeadlock()
    {
        unset($this->deadlock);
    }

    /**
     * Deadlock is used in pessimistic transaction for single statement rollback.
     *
     * Generated from protobuf field <code>.kvrpcpb.Deadlock deadlock = 6;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Deadlock $var
     * @return $this
     */
    public function setDeadlock($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\Deadlock::class);
        $this->deadlock = $var;

        return $this;
    }

    /**
     * Commit ts is earlier than min commit ts of a transaction.
     *
     * Generated from protobuf field <code>.kvrpcpb.CommitTsExpired commit_ts_expired = 7;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CommitTsExpired|null
     */
    public function getCommitTsExpired()
    {
        return $this->commit_ts_expired;
    }

    public function hasCommitTsExpired()
    {
        return isset($this->commit_ts_expired);
    }

    public function clearCommitTsExpired()
    {
        unset($this->commit_ts_expired);
    }

    /**
     * Commit ts is earlier than min commit ts of a transaction.
     *
     * Generated from protobuf field <code>.kvrpcpb.CommitTsExpired commit_ts_expired = 7;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CommitTsExpired $var
     * @return $this
     */
    public function setCommitTsExpired($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\CommitTsExpired::class);
        $this->commit_ts_expired = $var;

        return $this;
    }

    /**
     * Txn not found when checking txn status.
     *
     * Generated from protobuf field <code>.kvrpcpb.TxnNotFound txn_not_found = 8;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\TxnNotFound|null
     */
    public function getTxnNotFound()
    {
        return $this->txn_not_found;
    }

    public function hasTxnNotFound()
    {
        return isset($this->txn_not_found);
    }

    public function clearTxnNotFound()
    {
        unset($this->txn_not_found);
    }

    /**
     * Txn not found when checking txn status.
     *
     * Generated from protobuf field <code>.kvrpcpb.TxnNotFound txn_not_found = 8;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\TxnNotFound $var
     * @return $this
     */
    public function setTxnNotFound($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\TxnNotFound::class);
        $this->txn_not_found = $var;

        return $this;
    }

    /**
     * Calculated commit TS exceeds the limit given by the user.
     *
     * Generated from protobuf field <code>.kvrpcpb.CommitTsTooLarge commit_ts_too_large = 9;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\CommitTsTooLarge|null
     */
    public function getCommitTsTooLarge()
    {
        return $this->commit_ts_too_large;
    }

    public function hasCommitTsTooLarge()
    {
        return isset($this->commit_ts_too_large);
    }

    public function clearCommitTsTooLarge()
    {
        unset($this->commit_ts_too_large);
    }

    /**
     * Calculated commit TS exceeds the limit given by the user.
     *
     * Generated from protobuf field <code>.kvrpcpb.CommitTsTooLarge commit_ts_too_large = 9;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\CommitTsTooLarge $var
     * @return $this
     */
    public function setCommitTsTooLarge($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\CommitTsTooLarge::class);
        $this->commit_ts_too_large = $var;

        return $this;
    }

    /**
     * Assertion of a `Mutation` is evaluated as a failure.
     *
     * Generated from protobuf field <code>.kvrpcpb.AssertionFailed assertion_failed = 10;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\AssertionFailed|null
     */
    public function getAssertionFailed()
    {
        return $this->assertion_failed;
    }

    public function hasAssertionFailed()
    {
        return isset($this->assertion_failed);
    }

    public function clearAssertionFailed()
    {
        unset($this->assertion_failed);
    }

    /**
     * Assertion of a `Mutation` is evaluated as a failure.
     *
     * Generated from protobuf field <code>.kvrpcpb.AssertionFailed assertion_failed = 10;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\AssertionFailed $var
     * @return $this
     */
    public function setAssertionFailed($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\AssertionFailed::class);
        $this->assertion_failed = $var;

        return $this;
    }

    /**
     * CheckTxnStatus is sent to a lock that's not the primary.
     *
     * Generated from protobuf field <code>.kvrpcpb.PrimaryMismatch primary_mismatch = 11;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\PrimaryMismatch|null
     */
    public function getPrimaryMismatch()
    {
        return $this->primary_mismatch;
    }

    public function hasPrimaryMismatch()
    {
        return isset($this->primary_mismatch);
    }

    public function clearPrimaryMismatch()
    {
        unset($this->primary_mismatch);
    }

    /**
     * CheckTxnStatus is sent to a lock that's not the primary.
     *
     * Generated from protobuf field <code>.kvrpcpb.PrimaryMismatch primary_mismatch = 11;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\PrimaryMismatch $var
     * @return $this
     */
    public function setPrimaryMismatch($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\PrimaryMismatch::class);
        $this->primary_mismatch = $var;

        return $this;
    }

    /**
     * TxnLockNotFound indicates the txn lock is not found.
     *
     * Generated from protobuf field <code>.kvrpcpb.TxnLockNotFound txn_lock_not_found = 12;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\TxnLockNotFound|null
     */
    public function getTxnLockNotFound()
    {
        return $this->txn_lock_not_found;
    }

    public function hasTxnLockNotFound()
    {
        return isset($this->txn_lock_not_found);
    }

    public function clearTxnLockNotFound()
    {
        unset($this->txn_lock_not_found);
    }

    /**
     * TxnLockNotFound indicates the txn lock is not found.
     *
     * Generated from protobuf field <code>.kvrpcpb.TxnLockNotFound txn_lock_not_found = 12;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\TxnLockNotFound $var
     * @return $this
     */
    public function setTxnLockNotFound($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\TxnLockNotFound::class);
        $this->txn_lock_not_found = $var;

        return $this;
    }

    /**
     * Extra information for error debugging
     *
     * Generated from protobuf field <code>.kvrpcpb.DebugInfo debug_info = 100;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\DebugInfo|null
     */
    public function getDebugInfo()
    {
        return $this->debug_info;
    }

    public function hasDebugInfo()
    {
        return isset($this->debug_info);
    }

    public function clearDebugInfo()
    {
        unset($this->debug_info);
    }

    /**
     * Extra information for error debugging
     *
     * Generated from protobuf field <code>.kvrpcpb.DebugInfo debug_info = 100;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\DebugInfo $var
     * @return $this
     */
    public function setDebugInfo($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\DebugInfo::class);
        $this->debug_info = $var;

        return $this;
    }

}

