<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.LockInfo</code>
 */
class LockInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes primary_lock = 1;</code>
     */
    protected $primary_lock = '';
    /**
     * Generated from protobuf field <code>uint64 lock_version = 2;</code>
     */
    protected $lock_version = 0;
    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>uint64 lock_ttl = 4;</code>
     */
    protected $lock_ttl = 0;
    /**
     * How many keys this transaction involves in this region.
     *
     * Generated from protobuf field <code>uint64 txn_size = 5;</code>
     */
    protected $txn_size = 0;
    /**
     * Generated from protobuf field <code>.kvrpcpb.Op lock_type = 6;</code>
     */
    protected $lock_type = 0;
    /**
     * Generated from protobuf field <code>uint64 lock_for_update_ts = 7;</code>
     */
    protected $lock_for_update_ts = 0;
    /**
     * Fields for transactions that are using Async Commit.
     *
     * Generated from protobuf field <code>bool use_async_commit = 8;</code>
     */
    protected $use_async_commit = false;
    /**
     * Generated from protobuf field <code>uint64 min_commit_ts = 9;</code>
     */
    protected $min_commit_ts = 0;
    /**
     * Generated from protobuf field <code>repeated bytes secondaries = 10;</code>
     */
    private $secondaries;
    /**
     * The time elapsed since last update of lock wait info when waiting.
     * It's used in timeout errors. 0 means unknown or not applicable.
     * It can be used to help the client decide whether to try resolving the lock.
     *
     * Generated from protobuf field <code>uint64 duration_to_last_update_ms = 11;</code>
     */
    protected $duration_to_last_update_ms = 0;
    /**
     * When lock_type is SharedLock, this describes transactions holding the shared lock.
     * Important: when lock_type is SharedLock, all shared locks must use shared_lock_infos;
     * DO NOT read from the wrapper LockInfo.
     * TODO(slock): tidb should send requests with a feature flag to indicate whether it
     * supports shared locks, so that tikv can fail the requests from old tidb versions
     * when needed.
     *
     * Generated from protobuf field <code>repeated .kvrpcpb.LockInfo shared_lock_infos = 12;</code>
     */
    private $shared_lock_infos;
    /**
     * Reserved for file based transaction.
     *
     * Generated from protobuf field <code>bool is_txn_file = 100;</code>
     */
    protected $is_txn_file = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $primary_lock
     *     @type int|string $lock_version
     *     @type string $key
     *     @type int|string $lock_ttl
     *     @type int|string $txn_size
     *           How many keys this transaction involves in this region.
     *     @type int $lock_type
     *     @type int|string $lock_for_update_ts
     *     @type bool $use_async_commit
     *           Fields for transactions that are using Async Commit.
     *     @type int|string $min_commit_ts
     *     @type string[] $secondaries
     *     @type int|string $duration_to_last_update_ms
     *           The time elapsed since last update of lock wait info when waiting.
     *           It's used in timeout errors. 0 means unknown or not applicable.
     *           It can be used to help the client decide whether to try resolving the lock.
     *     @type \Kvrpcpb\LockInfo[] $shared_lock_infos
     *           When lock_type is SharedLock, this describes transactions holding the shared lock.
     *           Important: when lock_type is SharedLock, all shared locks must use shared_lock_infos;
     *           DO NOT read from the wrapper LockInfo.
     *           TODO(slock): tidb should send requests with a feature flag to indicate whether it
     *           supports shared locks, so that tikv can fail the requests from old tidb versions
     *           when needed.
     *     @type bool $is_txn_file
     *           Reserved for file based transaction.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes primary_lock = 1;</code>
     * @return string
     */
    public function getPrimaryLock()
    {
        return $this->primary_lock;
    }

    /**
     * Generated from protobuf field <code>bytes primary_lock = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimaryLock($var)
    {
        GPBUtil::checkString($var, False);
        $this->primary_lock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 lock_version = 2;</code>
     * @return int|string
     */
    public function getLockVersion()
    {
        return $this->lock_version;
    }

    /**
     * Generated from protobuf field <code>uint64 lock_version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLockVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->lock_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 lock_ttl = 4;</code>
     * @return int|string
     */
    public function getLockTtl()
    {
        return $this->lock_ttl;
    }

    /**
     * Generated from protobuf field <code>uint64 lock_ttl = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLockTtl($var)
    {
        GPBUtil::checkUint64($var);
        $this->lock_ttl = $var;

        return $this;
    }

    /**
     * How many keys this transaction involves in this region.
     *
     * Generated from protobuf field <code>uint64 txn_size = 5;</code>
     * @return int|string
     */
    public function getTxnSize()
    {
        return $this->txn_size;
    }

    /**
     * How many keys this transaction involves in this region.
     *
     * Generated from protobuf field <code>uint64 txn_size = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxnSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->txn_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Op lock_type = 6;</code>
     * @return int
     */
    public function getLockType()
    {
        return $this->lock_type;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Op lock_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLockType($var)
    {
        GPBUtil::checkEnum($var, \Kvrpcpb\Op::class);
        $this->lock_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 lock_for_update_ts = 7;</code>
     * @return int|string
     */
    public function getLockForUpdateTs()
    {
        return $this->lock_for_update_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 lock_for_update_ts = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLockForUpdateTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->lock_for_update_ts = $var;

        return $this;
    }

    /**
     * Fields for transactions that are using Async Commit.
     *
     * Generated from protobuf field <code>bool use_async_commit = 8;</code>
     * @return bool
     */
    public function getUseAsyncCommit()
    {
        return $this->use_async_commit;
    }

    /**
     * Fields for transactions that are using Async Commit.
     *
     * Generated from protobuf field <code>bool use_async_commit = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseAsyncCommit($var)
    {
        GPBUtil::checkBool($var);
        $this->use_async_commit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 min_commit_ts = 9;</code>
     * @return int|string
     */
    public function getMinCommitTs()
    {
        return $this->min_commit_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 min_commit_ts = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinCommitTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->min_commit_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes secondaries = 10;</code>
     * @return RepeatedField<string>
     */
    public function getSecondaries()
    {
        return $this->secondaries;
    }

    /**
     * Generated from protobuf field <code>repeated bytes secondaries = 10;</code>
     * @param string[] $var
     * @return $this
     */
    public function setSecondaries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->secondaries = $arr;

        return $this;
    }

    /**
     * The time elapsed since last update of lock wait info when waiting.
     * It's used in timeout errors. 0 means unknown or not applicable.
     * It can be used to help the client decide whether to try resolving the lock.
     *
     * Generated from protobuf field <code>uint64 duration_to_last_update_ms = 11;</code>
     * @return int|string
     */
    public function getDurationToLastUpdateMs()
    {
        return $this->duration_to_last_update_ms;
    }

    /**
     * The time elapsed since last update of lock wait info when waiting.
     * It's used in timeout errors. 0 means unknown or not applicable.
     * It can be used to help the client decide whether to try resolving the lock.
     *
     * Generated from protobuf field <code>uint64 duration_to_last_update_ms = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDurationToLastUpdateMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->duration_to_last_update_ms = $var;

        return $this;
    }

    /**
     * When lock_type is SharedLock, this describes transactions holding the shared lock.
     * Important: when lock_type is SharedLock, all shared locks must use shared_lock_infos;
     * DO NOT read from the wrapper LockInfo.
     * TODO(slock): tidb should send requests with a feature flag to indicate whether it
     * supports shared locks, so that tikv can fail the requests from old tidb versions
     * when needed.
     *
     * Generated from protobuf field <code>repeated .kvrpcpb.LockInfo shared_lock_infos = 12;</code>
     * @return RepeatedField<\Kvrpcpb\LockInfo>
     */
    public function getSharedLockInfos()
    {
        return $this->shared_lock_infos;
    }

    /**
     * When lock_type is SharedLock, this describes transactions holding the shared lock.
     * Important: when lock_type is SharedLock, all shared locks must use shared_lock_infos;
     * DO NOT read from the wrapper LockInfo.
     * TODO(slock): tidb should send requests with a feature flag to indicate whether it
     * supports shared locks, so that tikv can fail the requests from old tidb versions
     * when needed.
     *
     * Generated from protobuf field <code>repeated .kvrpcpb.LockInfo shared_lock_infos = 12;</code>
     * @param \Kvrpcpb\LockInfo[] $var
     * @return $this
     */
    public function setSharedLockInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Kvrpcpb\LockInfo::class);
        $this->shared_lock_infos = $arr;

        return $this;
    }

    /**
     * Reserved for file based transaction.
     *
     * Generated from protobuf field <code>bool is_txn_file = 100;</code>
     * @return bool
     */
    public function getIsTxnFile()
    {
        return $this->is_txn_file;
    }

    /**
     * Reserved for file based transaction.
     *
     * Generated from protobuf field <code>bool is_txn_file = 100;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTxnFile($var)
    {
        GPBUtil::checkBool($var);
        $this->is_txn_file = $var;

        return $this;
    }

}

