<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.PhysicalScanLockResponse</code>
 */
class PhysicalScanLockResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string error = 1;</code>
     */
    protected $error = '';
    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.LockInfo locks = 2;</code>
     */
    private $locks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $error
     *     @type \Kvrpcpb\LockInfo[] $locks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string error = 1;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.LockInfo locks = 2;</code>
     * @return RepeatedField<\Kvrpcpb\LockInfo>
     */
    public function getLocks()
    {
        return $this->locks;
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.LockInfo locks = 2;</code>
     * @param \Kvrpcpb\LockInfo[] $var
     * @return $this
     */
    public function setLocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Kvrpcpb\LockInfo::class);
        $this->locks = $arr;

        return $this;
    }

}

