<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.RawCoprocessorResponse</code>
 */
class RawCoprocessorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     */
    protected $region_error = null;
    /**
     * Error message for cases like if no coprocessor with a matching name is found
     * or on a version mismatch between plugin_api and the coprocessor.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     */
    protected $error = '';
    /**
     * Generated from protobuf field <code>bytes data = 3;</code>
     */
    protected $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Errorpb\Error $region_error
     *     @type string $error
     *           Error message for cases like if no coprocessor with a matching name is found
     *           or on a version mismatch between plugin_api and the coprocessor.
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @return \CrazyGoat\Proto\Errorpb\Error|null
     */
    public function getRegionError()
    {
        return $this->region_error;
    }

    public function hasRegionError()
    {
        return isset($this->region_error);
    }

    public function clearRegionError()
    {
        unset($this->region_error);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @param \CrazyGoat\Proto\Errorpb\Error $var
     * @return $this
     */
    public function setRegionError($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Errorpb\Error::class);
        $this->region_error = $var;

        return $this;
    }

    /**
     * Error message for cases like if no coprocessor with a matching name is found
     * or on a version mismatch between plugin_api and the coprocessor.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Error message for cases like if no coprocessor with a matching name is found
     * or on a version mismatch between plugin_api and the coprocessor.
     *
     * Generated from protobuf field <code>string error = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

