<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.RawChecksumRequest</code>
 */
class RawChecksumRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     */
    protected $context = null;
    /**
     * Generated from protobuf field <code>.kvrpcpb.ChecksumAlgorithm algorithm = 2;</code>
     */
    protected $algorithm = 0;
    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange ranges = 3;</code>
     */
    private $ranges;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     *     @type int $algorithm
     *     @type \CrazyGoat\Proto\Kvrpcpb\KeyRange[] $ranges
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ChecksumAlgorithm algorithm = 2;</code>
     * @return int
     */
    public function getAlgorithm()
    {
        return $this->algorithm;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ChecksumAlgorithm algorithm = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAlgorithm($var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Kvrpcpb\ChecksumAlgorithm::class);
        $this->algorithm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange ranges = 3;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Kvrpcpb\KeyRange>
     */
    public function getRanges()
    {
        return $this->ranges;
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange ranges = 3;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\KeyRange[] $var
     * @return $this
     */
    public function setRanges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Kvrpcpb\KeyRange::class);
        $this->ranges = $arr;

        return $this;
    }

}

