<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.RawGetResponse</code>
 */
class RawGetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     */
    protected $region_error = null;
    /**
     * Generated from protobuf field <code>string error = 2;</code>
     */
    protected $error = '';
    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>bool not_found = 4;</code>
     */
    protected $not_found = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Errorpb\Error $region_error
     *     @type string $error
     *     @type string $value
     *     @type bool $not_found
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @return \CrazyGoat\Proto\Errorpb\Error|null
     */
    public function getRegionError()
    {
        return $this->region_error;
    }

    public function hasRegionError()
    {
        return isset($this->region_error);
    }

    public function clearRegionError()
    {
        unset($this->region_error);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @param \CrazyGoat\Proto\Errorpb\Error $var
     * @return $this
     */
    public function setRegionError($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Errorpb\Error::class);
        $this->region_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error = 2;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>bytes value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool not_found = 4;</code>
     * @return bool
     */
    public function getNotFound()
    {
        return $this->not_found;
    }

    /**
     * Generated from protobuf field <code>bool not_found = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotFound($var)
    {
        GPBUtil::checkBool($var);
        $this->not_found = $var;

        return $this;
    }

}

