<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.RawGetResponse</code>
 */
class RawGetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Field 3 to match TiKV proto
     *
     * Generated from protobuf field <code>bytes value = 3;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>bool not_found = 4;</code>
     */
    protected $not_found = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *           Field 3 to match TiKV proto
     *     @type bool $not_found
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Field 3 to match TiKV proto
     *
     * Generated from protobuf field <code>bytes value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Field 3 to match TiKV proto
     *
     * Generated from protobuf field <code>bytes value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool not_found = 4;</code>
     * @return bool
     */
    public function getNotFound()
    {
        return $this->not_found;
    }

    /**
     * Generated from protobuf field <code>bool not_found = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotFound($var)
    {
        GPBUtil::checkBool($var);
        $this->not_found = $var;

        return $this;
    }

}

