<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.RawScanRequest</code>
 */
class RawScanRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     */
    protected $context = null;
    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     */
    protected $start_key = '';
    /**
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     */
    protected $limit = 0;
    /**
     * Generated from protobuf field <code>bool key_only = 4;</code>
     */
    protected $key_only = false;
    /**
     * Generated from protobuf field <code>string cf = 5;</code>
     */
    protected $cf = '';
    /**
     * Generated from protobuf field <code>bool reverse = 6;</code>
     */
    protected $reverse = false;
    /**
     * For compatibility, when scanning forward, the range to scan is [start_key, end_key), where start_key < end_key;
     * and when scanning backward, it scans [end_key, start_key) in descending order, where end_key < start_key.
     *
     * Generated from protobuf field <code>bytes end_key = 7;</code>
     */
    protected $end_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Kvrpcpb\Context $context
     *     @type string $start_key
     *     @type int $limit
     *     @type bool $key_only
     *     @type string $cf
     *     @type bool $reverse
     *     @type string $end_key
     *           For compatibility, when scanning forward, the range to scan is [start_key, end_key), where start_key < end_key;
     *           and when scanning backward, it scans [end_key, start_key) in descending order, where end_key < start_key.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @return \Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @param \Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Kvrpcpb\Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Generated from protobuf field <code>bytes start_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>uint32 limit = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool key_only = 4;</code>
     * @return bool
     */
    public function getKeyOnly()
    {
        return $this->key_only;
    }

    /**
     * Generated from protobuf field <code>bool key_only = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setKeyOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->key_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cf = 5;</code>
     * @return string
     */
    public function getCf()
    {
        return $this->cf;
    }

    /**
     * Generated from protobuf field <code>string cf = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCf($var)
    {
        GPBUtil::checkString($var, True);
        $this->cf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool reverse = 6;</code>
     * @return bool
     */
    public function getReverse()
    {
        return $this->reverse;
    }

    /**
     * Generated from protobuf field <code>bool reverse = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setReverse($var)
    {
        GPBUtil::checkBool($var);
        $this->reverse = $var;

        return $this;
    }

    /**
     * For compatibility, when scanning forward, the range to scan is [start_key, end_key), where start_key < end_key;
     * and when scanning backward, it scans [end_key, start_key) in descending order, where end_key < start_key.
     *
     * Generated from protobuf field <code>bytes end_key = 7;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * For compatibility, when scanning forward, the range to scan is [start_key, end_key), where start_key < end_key;
     * and when scanning backward, it scans [end_key, start_key) in descending order, where end_key < start_key.
     *
     * Generated from protobuf field <code>bytes end_key = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->end_key = $var;

        return $this;
    }

}

