<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.ReadIndexResponse</code>
 */
class ReadIndexResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     */
    protected $region_error = null;
    /**
     * Generated from protobuf field <code>uint64 read_index = 2;</code>
     */
    protected $read_index = 0;
    /**
     * If `locked` is set, this read request is blocked by a lock.
     * The lock should be returned to the client.
     *
     * Generated from protobuf field <code>.kvrpcpb.LockInfo locked = 3;</code>
     */
    protected $locked = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Errorpb\Error $region_error
     *     @type int|string $read_index
     *     @type \Kvrpcpb\LockInfo $locked
     *           If `locked` is set, this read request is blocked by a lock.
     *           The lock should be returned to the client.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @return \Errorpb\Error|null
     */
    public function getRegionError()
    {
        return $this->region_error;
    }

    public function hasRegionError()
    {
        return isset($this->region_error);
    }

    public function clearRegionError()
    {
        unset($this->region_error);
    }

    /**
     * Generated from protobuf field <code>.errorpb.Error region_error = 1;</code>
     * @param \Errorpb\Error $var
     * @return $this
     */
    public function setRegionError($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\Error::class);
        $this->region_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 read_index = 2;</code>
     * @return int|string
     */
    public function getReadIndex()
    {
        return $this->read_index;
    }

    /**
     * Generated from protobuf field <code>uint64 read_index = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReadIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->read_index = $var;

        return $this;
    }

    /**
     * If `locked` is set, this read request is blocked by a lock.
     * The lock should be returned to the client.
     *
     * Generated from protobuf field <code>.kvrpcpb.LockInfo locked = 3;</code>
     * @return \Kvrpcpb\LockInfo|null
     */
    public function getLocked()
    {
        return $this->locked;
    }

    public function hasLocked()
    {
        return isset($this->locked);
    }

    public function clearLocked()
    {
        unset($this->locked);
    }

    /**
     * If `locked` is set, this read request is blocked by a lock.
     * The lock should be returned to the client.
     *
     * Generated from protobuf field <code>.kvrpcpb.LockInfo locked = 3;</code>
     * @param \Kvrpcpb\LockInfo $var
     * @return $this
     */
    public function setLocked($var)
    {
        GPBUtil::checkMessage($var, \Kvrpcpb\LockInfo::class);
        $this->locked = $var;

        return $this;
    }

}

