<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.ReadState</code>
 */
class ReadState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 applied_index = 1;</code>
     */
    protected $applied_index = 0;
    /**
     * Generated from protobuf field <code>uint64 safe_ts = 2;</code>
     */
    protected $safe_ts = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $applied_index
     *     @type int|string $safe_ts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 applied_index = 1;</code>
     * @return int|string
     */
    public function getAppliedIndex()
    {
        return $this->applied_index;
    }

    /**
     * Generated from protobuf field <code>uint64 applied_index = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAppliedIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->applied_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 safe_ts = 2;</code>
     * @return int|string
     */
    public function getSafeTs()
    {
        return $this->safe_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 safe_ts = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSafeTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->safe_ts = $var;

        return $this;
    }

}

