<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Sent from TiFlash to a TiKV node.
 *
 * Generated from protobuf message <code>kvrpcpb.ReadIndexRequest</code>
 */
class ReadIndexRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     */
    protected $context = null;
    /**
     * TiKV checks the given range if there is any unapplied lock
     * blocking the read request.
     *
     * Generated from protobuf field <code>uint64 start_ts = 2;</code>
     */
    protected $start_ts = 0;
    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange ranges = 3;</code>
     */
    private $ranges;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     *     @type int|string $start_ts
     *           TiKV checks the given range if there is any unapplied lock
     *           blocking the read request.
     *     @type \CrazyGoat\Proto\Kvrpcpb\KeyRange[] $ranges
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * TiKV checks the given range if there is any unapplied lock
     * blocking the read request.
     *
     * Generated from protobuf field <code>uint64 start_ts = 2;</code>
     * @return int|string
     */
    public function getStartTs()
    {
        return $this->start_ts;
    }

    /**
     * TiKV checks the given range if there is any unapplied lock
     * blocking the read request.
     *
     * Generated from protobuf field <code>uint64 start_ts = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange ranges = 3;</code>
     * @return RepeatedField<\CrazyGoat\Proto\Kvrpcpb\KeyRange>
     */
    public function getRanges()
    {
        return $this->ranges;
    }

    /**
     * Generated from protobuf field <code>repeated .kvrpcpb.KeyRange ranges = 3;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\KeyRange[] $var
     * @return $this
     */
    public function setRanges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \CrazyGoat\Proto\Kvrpcpb\KeyRange::class);
        $this->ranges = $arr;

        return $this;
    }

}

