<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Scan the database for locks. Used at the start of the GC process to find all
 * old locks.
 *
 * Generated from protobuf message <code>kvrpcpb.ScanLockRequest</code>
 */
class ScanLockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     */
    protected $context = null;
    /**
     * Returns all locks with a start timestamp before `max_version`.
     *
     * Generated from protobuf field <code>uint64 max_version = 2;</code>
     */
    protected $max_version = 0;
    /**
     * Start scanning from this key.
     *
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     */
    protected $start_key = '';
    /**
     * The maximum number of locks to return.
     *
     * Generated from protobuf field <code>uint32 limit = 4;</code>
     */
    protected $limit = 0;
    /**
     * The exclusive upperbound for scanning.
     *
     * Generated from protobuf field <code>bytes end_key = 5;</code>
     */
    protected $end_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     *     @type int|string $max_version
     *           Returns all locks with a start timestamp before `max_version`.
     *     @type string $start_key
     *           Start scanning from this key.
     *     @type int $limit
     *           The maximum number of locks to return.
     *     @type string $end_key
     *           The exclusive upperbound for scanning.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Returns all locks with a start timestamp before `max_version`.
     *
     * Generated from protobuf field <code>uint64 max_version = 2;</code>
     * @return int|string
     */
    public function getMaxVersion()
    {
        return $this->max_version;
    }

    /**
     * Returns all locks with a start timestamp before `max_version`.
     *
     * Generated from protobuf field <code>uint64 max_version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->max_version = $var;

        return $this;
    }

    /**
     * Start scanning from this key.
     *
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Start scanning from this key.
     *
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->start_key = $var;

        return $this;
    }

    /**
     * The maximum number of locks to return.
     *
     * Generated from protobuf field <code>uint32 limit = 4;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * The maximum number of locks to return.
     *
     * Generated from protobuf field <code>uint32 limit = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * The exclusive upperbound for scanning.
     *
     * Generated from protobuf field <code>bytes end_key = 5;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * The exclusive upperbound for scanning.
     *
     * Generated from protobuf field <code>bytes end_key = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->end_key = $var;

        return $this;
    }

}

