<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.ScanInfo</code>
 */
class ScanInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 total = 1;</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>int64 processed = 2;</code>
     */
    protected $processed = 0;
    /**
     * Generated from protobuf field <code>int64 read_bytes = 3;</code>
     */
    protected $read_bytes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $total
     *     @type int|string $processed
     *     @type int|string $read_bytes
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 total = 1;</code>
     * @return int|string
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int64 total = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt64($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 processed = 2;</code>
     * @return int|string
     */
    public function getProcessed()
    {
        return $this->processed;
    }

    /**
     * Generated from protobuf field <code>int64 processed = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProcessed($var)
    {
        GPBUtil::checkInt64($var);
        $this->processed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 read_bytes = 3;</code>
     * @return int|string
     */
    public function getReadBytes()
    {
        return $this->read_bytes;
    }

    /**
     * Generated from protobuf field <code>int64 read_bytes = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReadBytes($var)
    {
        GPBUtil::checkInt64($var);
        $this->read_bytes = $var;

        return $this;
    }

}

