<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Only reserved for compatibility.
 *
 * Generated from protobuf message <code>kvrpcpb.ScanDetail</code>
 */
class ScanDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo write = 1;</code>
     */
    protected $write = null;
    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo lock = 2;</code>
     */
    protected $lock = null;
    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo data = 3;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Kvrpcpb\ScanInfo $write
     *     @type \Kvrpcpb\ScanInfo $lock
     *     @type \Kvrpcpb\ScanInfo $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo write = 1;</code>
     * @return \Kvrpcpb\ScanInfo|null
     */
    public function getWrite()
    {
        return $this->write;
    }

    public function hasWrite()
    {
        return isset($this->write);
    }

    public function clearWrite()
    {
        unset($this->write);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo write = 1;</code>
     * @param \Kvrpcpb\ScanInfo $var
     * @return $this
     */
    public function setWrite($var)
    {
        GPBUtil::checkMessage($var, \Kvrpcpb\ScanInfo::class);
        $this->write = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo lock = 2;</code>
     * @return \Kvrpcpb\ScanInfo|null
     */
    public function getLock()
    {
        return $this->lock;
    }

    public function hasLock()
    {
        return isset($this->lock);
    }

    public function clearLock()
    {
        unset($this->lock);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo lock = 2;</code>
     * @param \Kvrpcpb\ScanInfo $var
     * @return $this
     */
    public function setLock($var)
    {
        GPBUtil::checkMessage($var, \Kvrpcpb\ScanInfo::class);
        $this->lock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo data = 3;</code>
     * @return \Kvrpcpb\ScanInfo|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.ScanInfo data = 3;</code>
     * @param \Kvrpcpb\ScanInfo $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Kvrpcpb\ScanInfo::class);
        $this->data = $var;

        return $this;
    }

}

