<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace CrazyGoat\Proto\Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Used to update the lock_ttl of a psessimistic and/or large transaction to prevent it from been killed.
 *
 * Generated from protobuf message <code>kvrpcpb.TxnHeartBeatRequest</code>
 */
class TxnHeartBeatRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     */
    protected $context = null;
    /**
     * The key of the lock to update.
     *
     * Generated from protobuf field <code>bytes primary_lock = 2;</code>
     */
    protected $primary_lock = '';
    /**
     * Start timestamp of the large transaction.
     *
     * Generated from protobuf field <code>uint64 start_version = 3;</code>
     */
    protected $start_version = 0;
    /**
     * The new TTL the sender would like.
     *
     * Generated from protobuf field <code>uint64 advise_lock_ttl = 4;</code>
     */
    protected $advise_lock_ttl = 0;
    /**
     * Optionally update PK's min_commit_ts.
     * Only for non-async-commmit and non-1PC transactions.
     * If it is 0, ignore this field.
     *
     * Generated from protobuf field <code>uint64 min_commit_ts = 5;</code>
     */
    protected $min_commit_ts = 0;
    /**
     * Reserved for file based transaction.
     *
     * Generated from protobuf field <code>bool is_txn_file = 100;</code>
     */
    protected $is_txn_file = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \CrazyGoat\Proto\Kvrpcpb\Context $context
     *     @type string $primary_lock
     *           The key of the lock to update.
     *     @type int|string $start_version
     *           Start timestamp of the large transaction.
     *     @type int|string $advise_lock_ttl
     *           The new TTL the sender would like.
     *     @type int|string $min_commit_ts
     *           Optionally update PK's min_commit_ts.
     *           Only for non-async-commmit and non-1PC transactions.
     *           If it is 0, ignore this field.
     *     @type bool $is_txn_file
     *           Reserved for file based transaction.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @return \CrazyGoat\Proto\Kvrpcpb\Context|null
     */
    public function getContext()
    {
        return $this->context;
    }

    public function hasContext()
    {
        return isset($this->context);
    }

    public function clearContext()
    {
        unset($this->context);
    }

    /**
     * Generated from protobuf field <code>.kvrpcpb.Context context = 1;</code>
     * @param \CrazyGoat\Proto\Kvrpcpb\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \CrazyGoat\Proto\Kvrpcpb\Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * The key of the lock to update.
     *
     * Generated from protobuf field <code>bytes primary_lock = 2;</code>
     * @return string
     */
    public function getPrimaryLock()
    {
        return $this->primary_lock;
    }

    /**
     * The key of the lock to update.
     *
     * Generated from protobuf field <code>bytes primary_lock = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimaryLock($var)
    {
        GPBUtil::checkString($var, False);
        $this->primary_lock = $var;

        return $this;
    }

    /**
     * Start timestamp of the large transaction.
     *
     * Generated from protobuf field <code>uint64 start_version = 3;</code>
     * @return int|string
     */
    public function getStartVersion()
    {
        return $this->start_version;
    }

    /**
     * Start timestamp of the large transaction.
     *
     * Generated from protobuf field <code>uint64 start_version = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_version = $var;

        return $this;
    }

    /**
     * The new TTL the sender would like.
     *
     * Generated from protobuf field <code>uint64 advise_lock_ttl = 4;</code>
     * @return int|string
     */
    public function getAdviseLockTtl()
    {
        return $this->advise_lock_ttl;
    }

    /**
     * The new TTL the sender would like.
     *
     * Generated from protobuf field <code>uint64 advise_lock_ttl = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAdviseLockTtl($var)
    {
        GPBUtil::checkUint64($var);
        $this->advise_lock_ttl = $var;

        return $this;
    }

    /**
     * Optionally update PK's min_commit_ts.
     * Only for non-async-commmit and non-1PC transactions.
     * If it is 0, ignore this field.
     *
     * Generated from protobuf field <code>uint64 min_commit_ts = 5;</code>
     * @return int|string
     */
    public function getMinCommitTs()
    {
        return $this->min_commit_ts;
    }

    /**
     * Optionally update PK's min_commit_ts.
     * Only for non-async-commmit and non-1PC transactions.
     * If it is 0, ignore this field.
     *
     * Generated from protobuf field <code>uint64 min_commit_ts = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinCommitTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->min_commit_ts = $var;

        return $this;
    }

    /**
     * Reserved for file based transaction.
     *
     * Generated from protobuf field <code>bool is_txn_file = 100;</code>
     * @return bool
     */
    public function getIsTxnFile()
    {
        return $this->is_txn_file;
    }

    /**
     * Reserved for file based transaction.
     *
     * Generated from protobuf field <code>bool is_txn_file = 100;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTxnFile($var)
    {
        GPBUtil::checkBool($var);
        $this->is_txn_file = $var;

        return $this;
    }

}

