<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvrpcpb.proto

namespace Kvrpcpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>kvrpcpb.TxnNotFound</code>
 */
class TxnNotFound extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 start_ts = 1;</code>
     */
    protected $start_ts = 0;
    /**
     * Generated from protobuf field <code>bytes primary_key = 2;</code>
     */
    protected $primary_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $start_ts
     *     @type string $primary_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kvrpcpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 start_ts = 1;</code>
     * @return int|string
     */
    public function getStartTs()
    {
        return $this->start_ts;
    }

    /**
     * Generated from protobuf field <code>uint64 start_ts = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTs($var)
    {
        GPBUtil::checkUint64($var);
        $this->start_ts = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes primary_key = 2;</code>
     * @return string
     */
    public function getPrimaryKey()
    {
        return $this->primary_key;
    }

    /**
     * Generated from protobuf field <code>bytes primary_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimaryKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->primary_key = $var;

        return $this;
    }

}

