<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_serverpb.proto

namespace Raft_serverpb;

use UnexpectedValueException;

/**
 * Protobuf type <code>raft_serverpb.ExtraMessageType</code>
 */
class ExtraMessageType
{
    /**
     * Generated from protobuf enum <code>MsgRegionWakeUp = 0;</code>
     */
    const MsgRegionWakeUp = 0;
    /**
     * Generated from protobuf enum <code>MsgWantRollbackMerge = 1;</code>
     */
    const MsgWantRollbackMerge = 1;
    /**
     * Generated from protobuf enum <code>MsgCheckStalePeer = 2;</code>
     */
    const MsgCheckStalePeer = 2;
    /**
     * Generated from protobuf enum <code>MsgCheckStalePeerResponse = 3;</code>
     */
    const MsgCheckStalePeerResponse = 3;
    /**
     * If leader is going to sleep, it will send requests to all its followers
     * to make sure they all agree to sleep.
     *
     * Generated from protobuf enum <code>MsgHibernateRequest = 4;</code>
     */
    const MsgHibernateRequest = 4;
    /**
     * Generated from protobuf enum <code>MsgHibernateResponse = 5;</code>
     */
    const MsgHibernateResponse = 5;
    /**
     * Generated from protobuf enum <code>MsgRejectRaftLogCausedByMemoryUsage = 6;</code>
     */
    const MsgRejectRaftLogCausedByMemoryUsage = 6;
    /**
     * Generated from protobuf enum <code>MsgAvailabilityRequest = 7;</code>
     */
    const MsgAvailabilityRequest = 7;
    /**
     * Generated from protobuf enum <code>MsgAvailabilityResponse = 8;</code>
     */
    const MsgAvailabilityResponse = 8;
    /**
     * Generated from protobuf enum <code>MsgVoterReplicatedIndexRequest = 9;</code>
     */
    const MsgVoterReplicatedIndexRequest = 9;
    /**
     * Generated from protobuf enum <code>MsgVoterReplicatedIndexResponse = 10;</code>
     */
    const MsgVoterReplicatedIndexResponse = 10;
    /**
     * Message means that `from` is tombstone. Leader can then update removed_records.
     *
     * Generated from protobuf enum <code>MsgGcPeerRequest = 11;</code>
     */
    const MsgGcPeerRequest = 11;
    /**
     * Generated from protobuf enum <code>MsgGcPeerResponse = 12;</code>
     */
    const MsgGcPeerResponse = 12;
    /**
     * Generated from protobuf enum <code>MsgFlushMemtable = 13;</code>
     */
    const MsgFlushMemtable = 13;
    /**
     * Generated from protobuf enum <code>MsgRefreshBuckets = 14;</code>
     */
    const MsgRefreshBuckets = 14;
    /**
     * Messages for the snapshot gen precheck process.
     *
     * Generated from protobuf enum <code>MsgSnapGenPrecheckRequest = 15;</code>
     */
    const MsgSnapGenPrecheckRequest = 15;
    /**
     * Generated from protobuf enum <code>MsgSnapGenPrecheckResponse = 16;</code>
     */
    const MsgSnapGenPrecheckResponse = 16;
    /**
     * Used in transfer leader process for leader to inform follower to load the
     * region into in-memory engine if the relevant region is cached.
     *
     * Generated from protobuf enum <code>MsgPreLoadRegionRequest = 17;</code>
     */
    const MsgPreLoadRegionRequest = 17;
    /**
     * Used in transfer leader process for follower to inform leader the completes
     * of the region cache
     *
     * Generated from protobuf enum <code>MsgPreLoadRegionResponse = 18;</code>
     */
    const MsgPreLoadRegionResponse = 18;

    private static $valueToName = [
        self::MsgRegionWakeUp => 'MsgRegionWakeUp',
        self::MsgWantRollbackMerge => 'MsgWantRollbackMerge',
        self::MsgCheckStalePeer => 'MsgCheckStalePeer',
        self::MsgCheckStalePeerResponse => 'MsgCheckStalePeerResponse',
        self::MsgHibernateRequest => 'MsgHibernateRequest',
        self::MsgHibernateResponse => 'MsgHibernateResponse',
        self::MsgRejectRaftLogCausedByMemoryUsage => 'MsgRejectRaftLogCausedByMemoryUsage',
        self::MsgAvailabilityRequest => 'MsgAvailabilityRequest',
        self::MsgAvailabilityResponse => 'MsgAvailabilityResponse',
        self::MsgVoterReplicatedIndexRequest => 'MsgVoterReplicatedIndexRequest',
        self::MsgVoterReplicatedIndexResponse => 'MsgVoterReplicatedIndexResponse',
        self::MsgGcPeerRequest => 'MsgGcPeerRequest',
        self::MsgGcPeerResponse => 'MsgGcPeerResponse',
        self::MsgFlushMemtable => 'MsgFlushMemtable',
        self::MsgRefreshBuckets => 'MsgRefreshBuckets',
        self::MsgSnapGenPrecheckRequest => 'MsgSnapGenPrecheckRequest',
        self::MsgSnapGenPrecheckResponse => 'MsgSnapGenPrecheckResponse',
        self::MsgPreLoadRegionRequest => 'MsgPreLoadRegionRequest',
        self::MsgPreLoadRegionResponse => 'MsgPreLoadRegionResponse',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

