<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_serverpb.proto

namespace Raft_serverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>raft_serverpb.RaftApplyState</code>
 */
class RaftApplyState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 applied_index = 1;</code>
     */
    protected $applied_index = 0;
    /**
     * Generated from protobuf field <code>uint64 last_commit_index = 3;</code>
     */
    protected $last_commit_index = 0;
    /**
     * Generated from protobuf field <code>uint64 commit_index = 4;</code>
     */
    protected $commit_index = 0;
    /**
     * Generated from protobuf field <code>uint64 commit_term = 5;</code>
     */
    protected $commit_term = 0;
    /**
     * Generated from protobuf field <code>.raft_serverpb.RaftTruncatedState truncated_state = 2;</code>
     */
    protected $truncated_state = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $applied_index
     *     @type int|string $last_commit_index
     *     @type int|string $commit_index
     *     @type int|string $commit_term
     *     @type \Raft_serverpb\RaftTruncatedState $truncated_state
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RaftServerpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 applied_index = 1;</code>
     * @return int|string
     */
    public function getAppliedIndex()
    {
        return $this->applied_index;
    }

    /**
     * Generated from protobuf field <code>uint64 applied_index = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAppliedIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->applied_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 last_commit_index = 3;</code>
     * @return int|string
     */
    public function getLastCommitIndex()
    {
        return $this->last_commit_index;
    }

    /**
     * Generated from protobuf field <code>uint64 last_commit_index = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastCommitIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->last_commit_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 commit_index = 4;</code>
     * @return int|string
     */
    public function getCommitIndex()
    {
        return $this->commit_index;
    }

    /**
     * Generated from protobuf field <code>uint64 commit_index = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommitIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->commit_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 commit_term = 5;</code>
     * @return int|string
     */
    public function getCommitTerm()
    {
        return $this->commit_term;
    }

    /**
     * Generated from protobuf field <code>uint64 commit_term = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommitTerm($var)
    {
        GPBUtil::checkUint64($var);
        $this->commit_term = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.RaftTruncatedState truncated_state = 2;</code>
     * @return \Raft_serverpb\RaftTruncatedState|null
     */
    public function getTruncatedState()
    {
        return $this->truncated_state;
    }

    public function hasTruncatedState()
    {
        return isset($this->truncated_state);
    }

    public function clearTruncatedState()
    {
        unset($this->truncated_state);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.RaftTruncatedState truncated_state = 2;</code>
     * @param \Raft_serverpb\RaftTruncatedState $var
     * @return $this
     */
    public function setTruncatedState($var)
    {
        GPBUtil::checkMessage($var, \Raft_serverpb\RaftTruncatedState::class);
        $this->truncated_state = $var;

        return $this;
    }

}

