<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_serverpb.proto

namespace Raft_serverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>raft_serverpb.RefreshBuckets</code>
 */
class RefreshBuckets extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>repeated bytes keys = 2;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>repeated uint64 sizes = 3;</code>
     */
    private $sizes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $version
     *     @type string[] $keys
     *     @type int[]|string[] $sizes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RaftServerpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 version = 1;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint64 version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes keys = 2;</code>
     * @return RepeatedField<string>
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Generated from protobuf field <code>repeated bytes keys = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 sizes = 3;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getSizes()
    {
        return $this->sizes;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 sizes = 3;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setSizes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->sizes = $arr;

        return $this;
    }

}

