<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_serverpb.proto

namespace Raft_serverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>raft_serverpb.TabletSnapshotResponse</code>
 */
class TabletSnapshotResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.raft_serverpb.AcceptedSnapshotFiles files = 1;</code>
     */
    protected $files = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Raft_serverpb\AcceptedSnapshotFiles $files
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RaftServerpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.AcceptedSnapshotFiles files = 1;</code>
     * @return \Raft_serverpb\AcceptedSnapshotFiles|null
     */
    public function getFiles()
    {
        return $this->files;
    }

    public function hasFiles()
    {
        return isset($this->files);
    }

    public function clearFiles()
    {
        unset($this->files);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.AcceptedSnapshotFiles files = 1;</code>
     * @param \Raft_serverpb\AcceptedSnapshotFiles $var
     * @return $this
     */
    public function setFiles($var)
    {
        GPBUtil::checkMessage($var, \Raft_serverpb\AcceptedSnapshotFiles::class);
        $this->files = $var;

        return $this;
    }

}

