<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_serverpb.proto

namespace Raft_serverpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>raft_serverpb.TabletSnapshotRequest</code>
 */
class TabletSnapshotRequest extends \Google\Protobuf\Internal\Message
{
    protected $payload;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Raft_serverpb\TabletSnapshotHead $head
     *     @type \Raft_serverpb\TabletSnapshotPreview $preview
     *     @type \Raft_serverpb\TabletSnapshotFileChunk $chunk
     *     @type \Raft_serverpb\TabletSnapshotEnd $end
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RaftServerpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.TabletSnapshotHead head = 1;</code>
     * @return \Raft_serverpb\TabletSnapshotHead|null
     */
    public function getHead()
    {
        return $this->readOneof(1);
    }

    public function hasHead()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.TabletSnapshotHead head = 1;</code>
     * @param \Raft_serverpb\TabletSnapshotHead $var
     * @return $this
     */
    public function setHead($var)
    {
        GPBUtil::checkMessage($var, \Raft_serverpb\TabletSnapshotHead::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.TabletSnapshotPreview preview = 2;</code>
     * @return \Raft_serverpb\TabletSnapshotPreview|null
     */
    public function getPreview()
    {
        return $this->readOneof(2);
    }

    public function hasPreview()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.TabletSnapshotPreview preview = 2;</code>
     * @param \Raft_serverpb\TabletSnapshotPreview $var
     * @return $this
     */
    public function setPreview($var)
    {
        GPBUtil::checkMessage($var, \Raft_serverpb\TabletSnapshotPreview::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.TabletSnapshotFileChunk chunk = 3;</code>
     * @return \Raft_serverpb\TabletSnapshotFileChunk|null
     */
    public function getChunk()
    {
        return $this->readOneof(3);
    }

    public function hasChunk()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.TabletSnapshotFileChunk chunk = 3;</code>
     * @param \Raft_serverpb\TabletSnapshotFileChunk $var
     * @return $this
     */
    public function setChunk($var)
    {
        GPBUtil::checkMessage($var, \Raft_serverpb\TabletSnapshotFileChunk::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.TabletSnapshotEnd end = 4;</code>
     * @return \Raft_serverpb\TabletSnapshotEnd|null
     */
    public function getEnd()
    {
        return $this->readOneof(4);
    }

    public function hasEnd()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.raft_serverpb.TabletSnapshotEnd end = 4;</code>
     * @param \Raft_serverpb\TabletSnapshotEnd $var
     * @return $this
     */
    public function setEnd($var)
    {
        GPBUtil::checkMessage($var, \Raft_serverpb\TabletSnapshotEnd::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getPayload()
    {
        return $this->whichOneof("payload");
    }

}

