<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: disaggregated.proto

namespace Disaggregated;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Error caused by concurrency conflict,
 * request cancel
 *
 * Generated from protobuf message <code>disaggregated.Conflict</code>
 */
class Conflict extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string reason = 1;</code>
     */
    protected $reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reason
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Disaggregated::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string reason = 1;</code>
     * @return string
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * Generated from protobuf field <code>string reason = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->reason = $var;

        return $this;
    }

}

