<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: errorpb.proto

namespace Errorpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Error wraps all region errors, indicates an error encountered by a request.
 *
 * Generated from protobuf message <code>errorpb.Error</code>
 */
class Error extends \Google\Protobuf\Internal\Message
{
    /**
     * The error message
     *
     * Generated from protobuf field <code>string message = 1;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.errorpb.NotLeader not_leader = 2;</code>
     */
    protected $not_leader = null;
    /**
     * Generated from protobuf field <code>.errorpb.RegionNotFound region_not_found = 3;</code>
     */
    protected $region_not_found = null;
    /**
     * Generated from protobuf field <code>.errorpb.KeyNotInRegion key_not_in_region = 4;</code>
     */
    protected $key_not_in_region = null;
    /**
     * Generated from protobuf field <code>.errorpb.EpochNotMatch epoch_not_match = 5;</code>
     */
    protected $epoch_not_match = null;
    /**
     * Generated from protobuf field <code>.errorpb.ServerIsBusy server_is_busy = 6;</code>
     */
    protected $server_is_busy = null;
    /**
     * Generated from protobuf field <code>.errorpb.StaleCommand stale_command = 7;</code>
     */
    protected $stale_command = null;
    /**
     * Generated from protobuf field <code>.errorpb.StoreNotMatch store_not_match = 8;</code>
     */
    protected $store_not_match = null;
    /**
     * Generated from protobuf field <code>.errorpb.RaftEntryTooLarge raft_entry_too_large = 9;</code>
     */
    protected $raft_entry_too_large = null;
    /**
     * Generated from protobuf field <code>.errorpb.MaxTimestampNotSynced max_timestamp_not_synced = 10;</code>
     */
    protected $max_timestamp_not_synced = null;
    /**
     * Generated from protobuf field <code>.errorpb.ReadIndexNotReady read_index_not_ready = 11;</code>
     */
    protected $read_index_not_ready = null;
    /**
     * Generated from protobuf field <code>.errorpb.ProposalInMergingMode proposal_in_merging_mode = 12;</code>
     */
    protected $proposal_in_merging_mode = null;
    /**
     * Generated from protobuf field <code>.errorpb.DataIsNotReady data_is_not_ready = 13;</code>
     */
    protected $data_is_not_ready = null;
    /**
     * Generated from protobuf field <code>.errorpb.RegionNotInitialized region_not_initialized = 14;</code>
     */
    protected $region_not_initialized = null;
    /**
     * Generated from protobuf field <code>.errorpb.DiskFull disk_full = 15;</code>
     */
    protected $disk_full = null;
    /**
     * Online recovery is still in performing, reject writes to avoid potential issues
     *
     * Generated from protobuf field <code>.errorpb.RecoveryInProgress RecoveryInProgress = 16;</code>
     */
    protected $RecoveryInProgress = null;
    /**
     * Flashback is still in performing, reject any read or write to avoid potential issues.
     * NOTICE: this error is non-retryable, the request should fail ASAP when it meets this error.
     *
     * Generated from protobuf field <code>.errorpb.FlashbackInProgress FlashbackInProgress = 17;</code>
     */
    protected $FlashbackInProgress = null;
    /**
     * If the second phase flashback request is sent to a region that is not prepared for the flashback,
     * this error will be returned.
     * NOTICE: this error is non-retryable, the client should retry the first phase flashback request when it meets this error.
     *
     * Generated from protobuf field <code>.errorpb.FlashbackNotPrepared FlashbackNotPrepared = 18;</code>
     */
    protected $FlashbackNotPrepared = null;
    /**
     * IsWitness is the error variant that tells a request be handle by witness
     * which should be forbidden and retry.
     *
     * Generated from protobuf field <code>.errorpb.IsWitness is_witness = 19;</code>
     */
    protected $is_witness = null;
    /**
     * Generated from protobuf field <code>.errorpb.MismatchPeerId mismatch_peer_id = 20;</code>
     */
    protected $mismatch_peer_id = null;
    /**
     * BucketVersionNotMatch is the error variant that tells the request buckets version is not match.
     *
     * Generated from protobuf field <code>.errorpb.BucketVersionNotMatch bucket_version_not_match = 21;</code>
     */
    protected $bucket_version_not_match = null;
    /**
     * UndeterminedResult is the error variant that tells the result is not determined yet.
     *
     * Generated from protobuf field <code>.errorpb.UndeterminedResult undetermined_result = 22;</code>
     */
    protected $undetermined_result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *           The error message
     *     @type \Errorpb\NotLeader $not_leader
     *     @type \Errorpb\RegionNotFound $region_not_found
     *     @type \Errorpb\KeyNotInRegion $key_not_in_region
     *     @type \Errorpb\EpochNotMatch $epoch_not_match
     *     @type \Errorpb\ServerIsBusy $server_is_busy
     *     @type \Errorpb\StaleCommand $stale_command
     *     @type \Errorpb\StoreNotMatch $store_not_match
     *     @type \Errorpb\RaftEntryTooLarge $raft_entry_too_large
     *     @type \Errorpb\MaxTimestampNotSynced $max_timestamp_not_synced
     *     @type \Errorpb\ReadIndexNotReady $read_index_not_ready
     *     @type \Errorpb\ProposalInMergingMode $proposal_in_merging_mode
     *     @type \Errorpb\DataIsNotReady $data_is_not_ready
     *     @type \Errorpb\RegionNotInitialized $region_not_initialized
     *     @type \Errorpb\DiskFull $disk_full
     *     @type \Errorpb\RecoveryInProgress $RecoveryInProgress
     *           Online recovery is still in performing, reject writes to avoid potential issues
     *     @type \Errorpb\FlashbackInProgress $FlashbackInProgress
     *           Flashback is still in performing, reject any read or write to avoid potential issues.
     *           NOTICE: this error is non-retryable, the request should fail ASAP when it meets this error.
     *     @type \Errorpb\FlashbackNotPrepared $FlashbackNotPrepared
     *           If the second phase flashback request is sent to a region that is not prepared for the flashback,
     *           this error will be returned.
     *           NOTICE: this error is non-retryable, the client should retry the first phase flashback request when it meets this error.
     *     @type \Errorpb\IsWitness $is_witness
     *           IsWitness is the error variant that tells a request be handle by witness
     *           which should be forbidden and retry.
     *     @type \Errorpb\MismatchPeerId $mismatch_peer_id
     *     @type \Errorpb\BucketVersionNotMatch $bucket_version_not_match
     *           BucketVersionNotMatch is the error variant that tells the request buckets version is not match.
     *     @type \Errorpb\UndeterminedResult $undetermined_result
     *           UndeterminedResult is the error variant that tells the result is not determined yet.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Errorpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The error message
     *
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * The error message
     *
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.NotLeader not_leader = 2;</code>
     * @return \Errorpb\NotLeader|null
     */
    public function getNotLeader()
    {
        return $this->not_leader;
    }

    public function hasNotLeader()
    {
        return isset($this->not_leader);
    }

    public function clearNotLeader()
    {
        unset($this->not_leader);
    }

    /**
     * Generated from protobuf field <code>.errorpb.NotLeader not_leader = 2;</code>
     * @param \Errorpb\NotLeader $var
     * @return $this
     */
    public function setNotLeader($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\NotLeader::class);
        $this->not_leader = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.RegionNotFound region_not_found = 3;</code>
     * @return \Errorpb\RegionNotFound|null
     */
    public function getRegionNotFound()
    {
        return $this->region_not_found;
    }

    public function hasRegionNotFound()
    {
        return isset($this->region_not_found);
    }

    public function clearRegionNotFound()
    {
        unset($this->region_not_found);
    }

    /**
     * Generated from protobuf field <code>.errorpb.RegionNotFound region_not_found = 3;</code>
     * @param \Errorpb\RegionNotFound $var
     * @return $this
     */
    public function setRegionNotFound($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\RegionNotFound::class);
        $this->region_not_found = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.KeyNotInRegion key_not_in_region = 4;</code>
     * @return \Errorpb\KeyNotInRegion|null
     */
    public function getKeyNotInRegion()
    {
        return $this->key_not_in_region;
    }

    public function hasKeyNotInRegion()
    {
        return isset($this->key_not_in_region);
    }

    public function clearKeyNotInRegion()
    {
        unset($this->key_not_in_region);
    }

    /**
     * Generated from protobuf field <code>.errorpb.KeyNotInRegion key_not_in_region = 4;</code>
     * @param \Errorpb\KeyNotInRegion $var
     * @return $this
     */
    public function setKeyNotInRegion($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\KeyNotInRegion::class);
        $this->key_not_in_region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.EpochNotMatch epoch_not_match = 5;</code>
     * @return \Errorpb\EpochNotMatch|null
     */
    public function getEpochNotMatch()
    {
        return $this->epoch_not_match;
    }

    public function hasEpochNotMatch()
    {
        return isset($this->epoch_not_match);
    }

    public function clearEpochNotMatch()
    {
        unset($this->epoch_not_match);
    }

    /**
     * Generated from protobuf field <code>.errorpb.EpochNotMatch epoch_not_match = 5;</code>
     * @param \Errorpb\EpochNotMatch $var
     * @return $this
     */
    public function setEpochNotMatch($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\EpochNotMatch::class);
        $this->epoch_not_match = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.ServerIsBusy server_is_busy = 6;</code>
     * @return \Errorpb\ServerIsBusy|null
     */
    public function getServerIsBusy()
    {
        return $this->server_is_busy;
    }

    public function hasServerIsBusy()
    {
        return isset($this->server_is_busy);
    }

    public function clearServerIsBusy()
    {
        unset($this->server_is_busy);
    }

    /**
     * Generated from protobuf field <code>.errorpb.ServerIsBusy server_is_busy = 6;</code>
     * @param \Errorpb\ServerIsBusy $var
     * @return $this
     */
    public function setServerIsBusy($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\ServerIsBusy::class);
        $this->server_is_busy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.StaleCommand stale_command = 7;</code>
     * @return \Errorpb\StaleCommand|null
     */
    public function getStaleCommand()
    {
        return $this->stale_command;
    }

    public function hasStaleCommand()
    {
        return isset($this->stale_command);
    }

    public function clearStaleCommand()
    {
        unset($this->stale_command);
    }

    /**
     * Generated from protobuf field <code>.errorpb.StaleCommand stale_command = 7;</code>
     * @param \Errorpb\StaleCommand $var
     * @return $this
     */
    public function setStaleCommand($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\StaleCommand::class);
        $this->stale_command = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.StoreNotMatch store_not_match = 8;</code>
     * @return \Errorpb\StoreNotMatch|null
     */
    public function getStoreNotMatch()
    {
        return $this->store_not_match;
    }

    public function hasStoreNotMatch()
    {
        return isset($this->store_not_match);
    }

    public function clearStoreNotMatch()
    {
        unset($this->store_not_match);
    }

    /**
     * Generated from protobuf field <code>.errorpb.StoreNotMatch store_not_match = 8;</code>
     * @param \Errorpb\StoreNotMatch $var
     * @return $this
     */
    public function setStoreNotMatch($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\StoreNotMatch::class);
        $this->store_not_match = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.RaftEntryTooLarge raft_entry_too_large = 9;</code>
     * @return \Errorpb\RaftEntryTooLarge|null
     */
    public function getRaftEntryTooLarge()
    {
        return $this->raft_entry_too_large;
    }

    public function hasRaftEntryTooLarge()
    {
        return isset($this->raft_entry_too_large);
    }

    public function clearRaftEntryTooLarge()
    {
        unset($this->raft_entry_too_large);
    }

    /**
     * Generated from protobuf field <code>.errorpb.RaftEntryTooLarge raft_entry_too_large = 9;</code>
     * @param \Errorpb\RaftEntryTooLarge $var
     * @return $this
     */
    public function setRaftEntryTooLarge($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\RaftEntryTooLarge::class);
        $this->raft_entry_too_large = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.MaxTimestampNotSynced max_timestamp_not_synced = 10;</code>
     * @return \Errorpb\MaxTimestampNotSynced|null
     */
    public function getMaxTimestampNotSynced()
    {
        return $this->max_timestamp_not_synced;
    }

    public function hasMaxTimestampNotSynced()
    {
        return isset($this->max_timestamp_not_synced);
    }

    public function clearMaxTimestampNotSynced()
    {
        unset($this->max_timestamp_not_synced);
    }

    /**
     * Generated from protobuf field <code>.errorpb.MaxTimestampNotSynced max_timestamp_not_synced = 10;</code>
     * @param \Errorpb\MaxTimestampNotSynced $var
     * @return $this
     */
    public function setMaxTimestampNotSynced($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\MaxTimestampNotSynced::class);
        $this->max_timestamp_not_synced = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.ReadIndexNotReady read_index_not_ready = 11;</code>
     * @return \Errorpb\ReadIndexNotReady|null
     */
    public function getReadIndexNotReady()
    {
        return $this->read_index_not_ready;
    }

    public function hasReadIndexNotReady()
    {
        return isset($this->read_index_not_ready);
    }

    public function clearReadIndexNotReady()
    {
        unset($this->read_index_not_ready);
    }

    /**
     * Generated from protobuf field <code>.errorpb.ReadIndexNotReady read_index_not_ready = 11;</code>
     * @param \Errorpb\ReadIndexNotReady $var
     * @return $this
     */
    public function setReadIndexNotReady($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\ReadIndexNotReady::class);
        $this->read_index_not_ready = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.ProposalInMergingMode proposal_in_merging_mode = 12;</code>
     * @return \Errorpb\ProposalInMergingMode|null
     */
    public function getProposalInMergingMode()
    {
        return $this->proposal_in_merging_mode;
    }

    public function hasProposalInMergingMode()
    {
        return isset($this->proposal_in_merging_mode);
    }

    public function clearProposalInMergingMode()
    {
        unset($this->proposal_in_merging_mode);
    }

    /**
     * Generated from protobuf field <code>.errorpb.ProposalInMergingMode proposal_in_merging_mode = 12;</code>
     * @param \Errorpb\ProposalInMergingMode $var
     * @return $this
     */
    public function setProposalInMergingMode($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\ProposalInMergingMode::class);
        $this->proposal_in_merging_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.DataIsNotReady data_is_not_ready = 13;</code>
     * @return \Errorpb\DataIsNotReady|null
     */
    public function getDataIsNotReady()
    {
        return $this->data_is_not_ready;
    }

    public function hasDataIsNotReady()
    {
        return isset($this->data_is_not_ready);
    }

    public function clearDataIsNotReady()
    {
        unset($this->data_is_not_ready);
    }

    /**
     * Generated from protobuf field <code>.errorpb.DataIsNotReady data_is_not_ready = 13;</code>
     * @param \Errorpb\DataIsNotReady $var
     * @return $this
     */
    public function setDataIsNotReady($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\DataIsNotReady::class);
        $this->data_is_not_ready = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.RegionNotInitialized region_not_initialized = 14;</code>
     * @return \Errorpb\RegionNotInitialized|null
     */
    public function getRegionNotInitialized()
    {
        return $this->region_not_initialized;
    }

    public function hasRegionNotInitialized()
    {
        return isset($this->region_not_initialized);
    }

    public function clearRegionNotInitialized()
    {
        unset($this->region_not_initialized);
    }

    /**
     * Generated from protobuf field <code>.errorpb.RegionNotInitialized region_not_initialized = 14;</code>
     * @param \Errorpb\RegionNotInitialized $var
     * @return $this
     */
    public function setRegionNotInitialized($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\RegionNotInitialized::class);
        $this->region_not_initialized = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.DiskFull disk_full = 15;</code>
     * @return \Errorpb\DiskFull|null
     */
    public function getDiskFull()
    {
        return $this->disk_full;
    }

    public function hasDiskFull()
    {
        return isset($this->disk_full);
    }

    public function clearDiskFull()
    {
        unset($this->disk_full);
    }

    /**
     * Generated from protobuf field <code>.errorpb.DiskFull disk_full = 15;</code>
     * @param \Errorpb\DiskFull $var
     * @return $this
     */
    public function setDiskFull($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\DiskFull::class);
        $this->disk_full = $var;

        return $this;
    }

    /**
     * Online recovery is still in performing, reject writes to avoid potential issues
     *
     * Generated from protobuf field <code>.errorpb.RecoveryInProgress RecoveryInProgress = 16;</code>
     * @return \Errorpb\RecoveryInProgress|null
     */
    public function getRecoveryInProgress()
    {
        return $this->RecoveryInProgress;
    }

    public function hasRecoveryInProgress()
    {
        return isset($this->RecoveryInProgress);
    }

    public function clearRecoveryInProgress()
    {
        unset($this->RecoveryInProgress);
    }

    /**
     * Online recovery is still in performing, reject writes to avoid potential issues
     *
     * Generated from protobuf field <code>.errorpb.RecoveryInProgress RecoveryInProgress = 16;</code>
     * @param \Errorpb\RecoveryInProgress $var
     * @return $this
     */
    public function setRecoveryInProgress($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\RecoveryInProgress::class);
        $this->RecoveryInProgress = $var;

        return $this;
    }

    /**
     * Flashback is still in performing, reject any read or write to avoid potential issues.
     * NOTICE: this error is non-retryable, the request should fail ASAP when it meets this error.
     *
     * Generated from protobuf field <code>.errorpb.FlashbackInProgress FlashbackInProgress = 17;</code>
     * @return \Errorpb\FlashbackInProgress|null
     */
    public function getFlashbackInProgress()
    {
        return $this->FlashbackInProgress;
    }

    public function hasFlashbackInProgress()
    {
        return isset($this->FlashbackInProgress);
    }

    public function clearFlashbackInProgress()
    {
        unset($this->FlashbackInProgress);
    }

    /**
     * Flashback is still in performing, reject any read or write to avoid potential issues.
     * NOTICE: this error is non-retryable, the request should fail ASAP when it meets this error.
     *
     * Generated from protobuf field <code>.errorpb.FlashbackInProgress FlashbackInProgress = 17;</code>
     * @param \Errorpb\FlashbackInProgress $var
     * @return $this
     */
    public function setFlashbackInProgress($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\FlashbackInProgress::class);
        $this->FlashbackInProgress = $var;

        return $this;
    }

    /**
     * If the second phase flashback request is sent to a region that is not prepared for the flashback,
     * this error will be returned.
     * NOTICE: this error is non-retryable, the client should retry the first phase flashback request when it meets this error.
     *
     * Generated from protobuf field <code>.errorpb.FlashbackNotPrepared FlashbackNotPrepared = 18;</code>
     * @return \Errorpb\FlashbackNotPrepared|null
     */
    public function getFlashbackNotPrepared()
    {
        return $this->FlashbackNotPrepared;
    }

    public function hasFlashbackNotPrepared()
    {
        return isset($this->FlashbackNotPrepared);
    }

    public function clearFlashbackNotPrepared()
    {
        unset($this->FlashbackNotPrepared);
    }

    /**
     * If the second phase flashback request is sent to a region that is not prepared for the flashback,
     * this error will be returned.
     * NOTICE: this error is non-retryable, the client should retry the first phase flashback request when it meets this error.
     *
     * Generated from protobuf field <code>.errorpb.FlashbackNotPrepared FlashbackNotPrepared = 18;</code>
     * @param \Errorpb\FlashbackNotPrepared $var
     * @return $this
     */
    public function setFlashbackNotPrepared($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\FlashbackNotPrepared::class);
        $this->FlashbackNotPrepared = $var;

        return $this;
    }

    /**
     * IsWitness is the error variant that tells a request be handle by witness
     * which should be forbidden and retry.
     *
     * Generated from protobuf field <code>.errorpb.IsWitness is_witness = 19;</code>
     * @return \Errorpb\IsWitness|null
     */
    public function getIsWitness()
    {
        return $this->is_witness;
    }

    public function hasIsWitness()
    {
        return isset($this->is_witness);
    }

    public function clearIsWitness()
    {
        unset($this->is_witness);
    }

    /**
     * IsWitness is the error variant that tells a request be handle by witness
     * which should be forbidden and retry.
     *
     * Generated from protobuf field <code>.errorpb.IsWitness is_witness = 19;</code>
     * @param \Errorpb\IsWitness $var
     * @return $this
     */
    public function setIsWitness($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\IsWitness::class);
        $this->is_witness = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.errorpb.MismatchPeerId mismatch_peer_id = 20;</code>
     * @return \Errorpb\MismatchPeerId|null
     */
    public function getMismatchPeerId()
    {
        return $this->mismatch_peer_id;
    }

    public function hasMismatchPeerId()
    {
        return isset($this->mismatch_peer_id);
    }

    public function clearMismatchPeerId()
    {
        unset($this->mismatch_peer_id);
    }

    /**
     * Generated from protobuf field <code>.errorpb.MismatchPeerId mismatch_peer_id = 20;</code>
     * @param \Errorpb\MismatchPeerId $var
     * @return $this
     */
    public function setMismatchPeerId($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\MismatchPeerId::class);
        $this->mismatch_peer_id = $var;

        return $this;
    }

    /**
     * BucketVersionNotMatch is the error variant that tells the request buckets version is not match.
     *
     * Generated from protobuf field <code>.errorpb.BucketVersionNotMatch bucket_version_not_match = 21;</code>
     * @return \Errorpb\BucketVersionNotMatch|null
     */
    public function getBucketVersionNotMatch()
    {
        return $this->bucket_version_not_match;
    }

    public function hasBucketVersionNotMatch()
    {
        return isset($this->bucket_version_not_match);
    }

    public function clearBucketVersionNotMatch()
    {
        unset($this->bucket_version_not_match);
    }

    /**
     * BucketVersionNotMatch is the error variant that tells the request buckets version is not match.
     *
     * Generated from protobuf field <code>.errorpb.BucketVersionNotMatch bucket_version_not_match = 21;</code>
     * @param \Errorpb\BucketVersionNotMatch $var
     * @return $this
     */
    public function setBucketVersionNotMatch($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\BucketVersionNotMatch::class);
        $this->bucket_version_not_match = $var;

        return $this;
    }

    /**
     * UndeterminedResult is the error variant that tells the result is not determined yet.
     *
     * Generated from protobuf field <code>.errorpb.UndeterminedResult undetermined_result = 22;</code>
     * @return \Errorpb\UndeterminedResult|null
     */
    public function getUndeterminedResult()
    {
        return $this->undetermined_result;
    }

    public function hasUndeterminedResult()
    {
        return isset($this->undetermined_result);
    }

    public function clearUndeterminedResult()
    {
        unset($this->undetermined_result);
    }

    /**
     * UndeterminedResult is the error variant that tells the result is not determined yet.
     *
     * Generated from protobuf field <code>.errorpb.UndeterminedResult undetermined_result = 22;</code>
     * @param \Errorpb\UndeterminedResult $var
     * @return $this
     */
    public function setUndeterminedResult($var)
    {
        GPBUtil::checkMessage($var, \Errorpb\UndeterminedResult::class);
        $this->undetermined_result = $var;

        return $this;
    }

}

