<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: errorpb.proto

namespace CrazyGoat\Proto\Errorpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * KeyNotInRegion is the error variant that tells the key the request requires isn't present in
 * this region.
 *
 * Generated from protobuf message <code>errorpb.KeyNotInRegion</code>
 */
class KeyNotInRegion extends \Google\Protobuf\Internal\Message
{
    /**
     * The requested key
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     */
    protected $key = '';
    /**
     * The requested region ID
     *
     * Generated from protobuf field <code>uint64 region_id = 2;</code>
     */
    protected $region_id = 0;
    /**
     * Start key of the requested region
     *
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     */
    protected $start_key = '';
    /**
     * Snd key of the requested region
     *
     * Generated from protobuf field <code>bytes end_key = 4;</code>
     */
    protected $end_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *           The requested key
     *     @type int|string $region_id
     *           The requested region ID
     *     @type string $start_key
     *           Start key of the requested region
     *     @type string $end_key
     *           Snd key of the requested region
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Errorpb::initOnce();
        parent::__construct($data);
    }

    /**
     * The requested key
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * The requested key
     *
     * Generated from protobuf field <code>bytes key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * The requested region ID
     *
     * Generated from protobuf field <code>uint64 region_id = 2;</code>
     * @return int|string
     */
    public function getRegionId()
    {
        return $this->region_id;
    }

    /**
     * The requested region ID
     *
     * Generated from protobuf field <code>uint64 region_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->region_id = $var;

        return $this;
    }

    /**
     * Start key of the requested region
     *
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     * @return string
     */
    public function getStartKey()
    {
        return $this->start_key;
    }

    /**
     * Start key of the requested region
     *
     * Generated from protobuf field <code>bytes start_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStartKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->start_key = $var;

        return $this;
    }

    /**
     * Snd key of the requested region
     *
     * Generated from protobuf field <code>bytes end_key = 4;</code>
     * @return string
     */
    public function getEndKey()
    {
        return $this->end_key;
    }

    /**
     * Snd key of the requested region
     *
     * Generated from protobuf field <code>bytes end_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->end_key = $var;

        return $this;
    }

}

