<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: errorpb.proto

namespace CrazyGoat\Proto\Errorpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * StaleCommand is the error variant that tells the command is stale, that is,
 * the current request term is lower than current raft term.
 * This can be retried at most time.
 *
 * Generated from protobuf message <code>errorpb.StaleCommand</code>
 */
class StaleCommand extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Errorpb::initOnce();
        parent::__construct($data);
    }

}

