<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eraftpb.proto

namespace Eraftpb;

use UnexpectedValueException;

/**
 * Protobuf type <code>eraftpb.ConfChangeTransition</code>
 */
class ConfChangeTransition
{
    /**
     * Automatically use the simple protocol if possible, otherwise fall back
     * to ConfChangeType::Implicit. Most applications will want to use this.
     *
     * Generated from protobuf enum <code>Auto = 0;</code>
     */
    const Auto = 0;
    /**
     * Use joint consensus unconditionally, and transition out of them
     * automatically (by proposing a zero configuration change).
     * This option is suitable for applications that want to minimize the time
     * spent in the joint configuration and do not store the joint configuration
     * in the state machine (outside of InitialState).
     *
     * Generated from protobuf enum <code>Implicit = 1;</code>
     */
    const Implicit = 1;
    /**
     * Use joint consensus and remain in the joint configuration until the
     * application proposes a no-op configuration change. This is suitable for
     * applications that want to explicitly control the transitions, for example
     * to use a custom payload (via the Context field).
     *
     * Generated from protobuf enum <code>Explicit = 2;</code>
     */
    const Explicit = 2;

    private static $valueToName = [
        self::Auto => 'Auto',
        self::Implicit => 'Implicit',
        self::Explicit => 'Explicit',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

