<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eraftpb.proto

namespace CrazyGoat\Proto\Eraftpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The entry is a type of change that needs to be applied. It contains two data fields.
 * While the fields are built into the model; their usage is determined by the entry_type.
 * For normal entries, the data field should contain the data change that should be applied.
 * The context field can be used for any contextual data that might be relevant to the
 * application of the data.
 * For configuration changes, the data will contain the ConfChange message and the
 * context will provide anything needed to assist the configuration change. The context
 * if for the user to set and use in this case.
 *
 * Generated from protobuf message <code>eraftpb.Entry</code>
 */
class Entry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.eraftpb.EntryType entry_type = 1;</code>
     */
    protected $entry_type = 0;
    /**
     * Generated from protobuf field <code>uint64 term = 2;</code>
     */
    protected $term = 0;
    /**
     * Generated from protobuf field <code>uint64 index = 3;</code>
     */
    protected $index = 0;
    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>bytes context = 6;</code>
     */
    protected $context = '';
    /**
     * Deprecated! It is kept for backward compatibility.
     * TODO: remove it in the next major release.
     *
     * Generated from protobuf field <code>bool sync_log = 5;</code>
     */
    protected $sync_log = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $entry_type
     *     @type int|string $term
     *     @type int|string $index
     *     @type string $data
     *     @type string $context
     *     @type bool $sync_log
     *           Deprecated! It is kept for backward compatibility.
     *           TODO: remove it in the next major release.
     * }
     */
    public function __construct($data = NULL) {
        \CrazyGoat\Proto\GPBMetadata\Eraftpb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.eraftpb.EntryType entry_type = 1;</code>
     * @return int
     */
    public function getEntryType()
    {
        return $this->entry_type;
    }

    /**
     * Generated from protobuf field <code>.eraftpb.EntryType entry_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setEntryType($var)
    {
        GPBUtil::checkEnum($var, \CrazyGoat\Proto\Eraftpb\EntryType::class);
        $this->entry_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 term = 2;</code>
     * @return int|string
     */
    public function getTerm()
    {
        return $this->term;
    }

    /**
     * Generated from protobuf field <code>uint64 term = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTerm($var)
    {
        GPBUtil::checkUint64($var);
        $this->term = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 index = 3;</code>
     * @return int|string
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>uint64 index = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes context = 6;</code>
     * @return string
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>bytes context = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->context = $var;

        return $this;
    }

    /**
     * Deprecated! It is kept for backward compatibility.
     * TODO: remove it in the next major release.
     *
     * Generated from protobuf field <code>bool sync_log = 5;</code>
     * @return bool
     */
    public function getSyncLog()
    {
        return $this->sync_log;
    }

    /**
     * Deprecated! It is kept for backward compatibility.
     * TODO: remove it in the next major release.
     *
     * Generated from protobuf field <code>bool sync_log = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setSyncLog($var)
    {
        GPBUtil::checkBool($var);
        $this->sync_log = $var;

        return $this;
    }

}

